table GSPM_YFJFTRGLZB
	lineageTag: 5ac2c152-bec5-45c2-8da2-7fd13fc2280f

	column FID
		dataType: string
		lineageTag: d26ab21c-a5ed-4b13-84b9-410dd3c7be52
		summarizeBy: none
		sourceColumn: FID

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		lineageTag: 260a1e04-9f9f-44c2-8e22-9efb1381dee5
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 课题编号
		dataType: string
		lineageTag: cbf341c6-b28f-4bc9-9f08-2e2f4fe4a1be
		summarizeBy: none
		sourceColumn: 课题编号

		annotation SummarizationSetBy = Automatic

	column 课题名称
		dataType: string
		lineageTag: 7374a3f8-f38c-49d2-aadd-102729bffd97
		summarizeBy: none
		sourceColumn: 课题名称

		annotation SummarizationSetBy = Automatic

	column 客商名称
		dataType: string
		lineageTag: 06b07531-b72c-42ff-8dfd-13a2ca8030fd
		summarizeBy: none
		sourceColumn: 客商名称

		annotation SummarizationSetBy = Automatic

	column 费用期间
		dataType: dateTime
		formatString: General Date
		lineageTag: c5ca9f5c-ac28-48ff-b411-390f798491b8
		summarizeBy: none
		sourceColumn: 费用期间

		variation 变体
			isDefault
			relationship: 3b90759a-dc96-4c5d-b058-0d640fb26d15
			defaultHierarchy: LocalDateTable_54536e4c-6b49-4b35-a806-7f0dc8b048d2.日期层次结构

		annotation SummarizationSetBy = Automatic

	column 直管机构
		dataType: string
		lineageTag: 0c3cb51d-df6e-44df-9332-ea559c2a3469
		summarizeBy: none
		sourceColumn: 直管机构

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 6a70e741-c1d1-4453-a295-b0bcac77aa78
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 财务一体化利润中心编码
		dataType: string
		lineageTag: 8552a1c7-45d8-47dc-86df-be221d43be93
		summarizeBy: none
		sourceColumn: 财务一体化利润中心编码

		annotation SummarizationSetBy = Automatic

	column 财务一体化利润中心名称
		dataType: string
		lineageTag: d9f37ba7-bfff-4019-b060-5d69b4081ad0
		summarizeBy: none
		sourceColumn: 财务一体化利润中心名称

		annotation SummarizationSetBy = Automatic

	column 评审状态
		dataType: string
		lineageTag: 84f6377c-d47f-4acc-afae-f0b1e33ab393
		summarizeBy: none
		sourceColumn: 评审状态

		annotation SummarizationSetBy = Automatic

	partition GSPM_YFJFTRGLZB-8e835834-3136-44e5-af6c-5f149e76282f = m
		mode: import
		source =
				let
				    源 = Oracle.Database("172.16.8.76/oracledb", [HierarchicalNavigation=true]),
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_YFJFTRGLZB1 = GSPM{[Name="GSPM_YFJFTRGLZB"]}[Data],
				    重命名的列 = Table.RenameColumns(GSPM_YFJFTRGLZB1,{{"SCREATOROGNCODE", "项目编码"}, {"FCWYTHLRZXBM", "财务一体化利润中心编码"}, {"FCWYTHLRZXMC", "财务一体化利润中心名称"}, {"FKSMC", "客商名称"}, {"FFYQJ", "费用期间"}, {"FYFXMKTBH", "课题编号"}, {"FYFXMKTMC", "课题名称"}, {"SCREATOROGNNAME", "项目名称"}, {"FPINGSHENZHUANGTAI", "评审状态"}}),
				    删除的其他列 = Table.SelectColumns(重命名的列,{"FID", "评审状态", "项目名称", "项目编码", "课题编号", "课题名称", "客商名称", "费用期间"}),
				    合并的查询 = Table.NestedJoin(删除的其他列, {"项目编码"}, MD_XMYTHDZXX, {"FXMBIANMA"}, "MD_XMYTHDZXX", JoinKind.LeftOuter),
				    #"展开的“MD_XMYTHDZXX”" = Table.ExpandTableColumn(合并的查询, "MD_XMYTHDZXX", {"FGFYTHLRZXBM", "FGFYTHLRZXMC"}, {"FGFYTHLRZXBM", "FGFYTHLRZXMC"}),
				    合并的查询1 = Table.NestedJoin(#"展开的“MD_XMYTHDZXX”", {"项目编码"}, MD_XIANGMUXINXI, {"FXMBIANMA"}, "MD_XIANGMUXINXI", JoinKind.LeftOuter),
				    #"展开的“MD_XIANGMUXINXI”" = Table.ExpandTableColumn(合并的查询1, "MD_XIANGMUXINXI", {"直管机构"}, {"直管机构"}),
				    重命名的列1 = Table.RenameColumns(#"展开的“MD_XIANGMUXINXI”",{{"FGFYTHLRZXBM", "财务一体化利润中心编码"}, {"FGFYTHLRZXMC", "财务一体化利润中心名称"}})
				in
				    重命名的列1

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

