table 流程数据
	lineageTag: b5bd6022-b9a1-47c1-925c-5fddab1610ff

	measure 节点完成时间 = SUM('流程数据'[自定义])
		formatString: 0
		lineageTag: 711732c8-dcd2-4018-aebc-54d44876f4fa

	column FID
		dataType: string
		lineageTag: b1c502ec-acf9-47da-b19b-e046d39067d2
		summarizeBy: none
		sourceColumn: FID

		annotation SummarizationSetBy = Automatic

	column FPINGSHENZHUANGTAI
		dataType: string
		lineageTag: 957e02df-314b-4079-b908-30e599cfdfbc
		summarizeBy: none
		sourceColumn: FPINGSHENZHUANGTAI

		annotation SummarizationSetBy = Automatic

	column SCREATOROGNNAME
		dataType: string
		lineageTag: be1f7450-666e-42ff-8ce2-cf77b3565c7d
		summarizeBy: none
		sourceColumn: SCREATOROGNNAME

		annotation SummarizationSetBy = Automatic

	column SCREATOROGNCODE
		dataType: string
		lineageTag: 90193b83-9f3e-4aab-9e22-71cabef6c268
		summarizeBy: none
		sourceColumn: SCREATOROGNCODE

		annotation SummarizationSetBy = Automatic

	column FYFXMKTBH
		dataType: string
		lineageTag: e953bf38-9625-439c-a8a0-638be8f75e2f
		summarizeBy: none
		sourceColumn: FYFXMKTBH

		annotation SummarizationSetBy = Automatic

	column FYFXMKTMC
		dataType: string
		lineageTag: b60af14e-b048-443c-be32-5c0d4031f209
		summarizeBy: none
		sourceColumn: FYFXMKTMC

		annotation SummarizationSetBy = Automatic

	column SNAME
		dataType: string
		lineageTag: 9243e2aa-ae37-48bb-a280-efe303575060
		summarizeBy: none
		sourceColumn: SNAME

		annotation SummarizationSetBy = Automatic

	column SCATALOGID
		dataType: string
		lineageTag: b5cbe470-93cc-435b-8063-a19ab66a9505
		summarizeBy: none
		sourceColumn: SCATALOGID

		annotation SummarizationSetBy = Automatic

	column SKINDID
		dataType: string
		lineageTag: 7a6d5d62-aaa9-4b20-9bdd-44b287cb50c6
		summarizeBy: none
		sourceColumn: SKINDID

		annotation SummarizationSetBy = Automatic

	column STYPENAME
		dataType: string
		lineageTag: e49f9719-40e0-457b-8b21-4c5641309281
		summarizeBy: none
		sourceColumn: STYPENAME

		annotation SummarizationSetBy = Automatic

	column SACTIVITY
		dataType: string
		lineageTag: 91e971c3-b42f-4944-94cf-b5774accb76f
		summarizeBy: none
		sourceColumn: SACTIVITY

		annotation SummarizationSetBy = Automatic

	column SCREATETIME
		dataType: dateTime
		formatString: General Date
		lineageTag: ccacc4ba-f573-4d4a-bc6b-af0a8cd67cec
		summarizeBy: none
		sourceColumn: SCREATETIME

		variation 变体
			isDefault
			relationship: 6cef97f2-8af4-4ecd-ba96-d1e5b9dfc649
			defaultHierarchy: LocalDateTable_5b560baf-944f-4174-8deb-7643e94a7f8b.日期层次结构

		annotation SummarizationSetBy = Automatic

	column SACTUALSTARTTIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 7c26ebfd-2e34-4847-947d-8bbeebbb8007
		summarizeBy: none
		sourceColumn: SACTUALSTARTTIME

		variation 变体
			isDefault
			relationship: 910d71b7-0247-4e10-afb8-506166abd7db
			defaultHierarchy: LocalDateTable_c46062ec-925d-424d-93ca-a38663a0726a.日期层次结构

		annotation SummarizationSetBy = Automatic

	column SACTUALFINISHTIME
		dataType: dateTime
		formatString: General Date
		lineageTag: 194f795d-d41c-4cf2-a857-001c4b361694
		summarizeBy: none
		sourceColumn: SACTUALFINISHTIME

		variation 变体
			isDefault
			relationship: 4d1ec35b-9ff1-44fa-b441-50f6e2996333
			defaultHierarchy: LocalDateTable_8eef6462-98a8-4535-b6e7-4aeb65cebf72.日期层次结构

		annotation SummarizationSetBy = Automatic

	column SEXECUTORPERSONNAME
		dataType: string
		lineageTag: b5c2b787-0104-4c08-bc35-adc76102f9c8
		summarizeBy: none
		sourceColumn: SEXECUTORPERSONNAME

		annotation SummarizationSetBy = Automatic

	column SEXECUTORPOSNAME
		dataType: string
		lineageTag: 0459792e-87af-4255-924b-a438a2f39c9c
		summarizeBy: none
		sourceColumn: SEXECUTORPOSNAME

		annotation SummarizationSetBy = Automatic

	column 索引
		dataType: int64
		formatString: 0
		lineageTag: a9216942-b628-498f-a8a0-9b1e0b14b271
		summarizeBy: sum
		sourceColumn: 索引

		annotation SummarizationSetBy = Automatic

	column 自定义
		dataType: int64
		formatString: 0
		lineageTag: c97d29f7-37f1-4fbd-88a6-34d3e392ede4
		summarizeBy: sum
		sourceColumn: 自定义

		annotation SummarizationSetBy = Automatic

	column FYEWUDANHAO
		dataType: string
		lineageTag: e0859d24-f922-4e16-b72e-673a9a8a6a3f
		summarizeBy: none
		sourceColumn: FYEWUDANHAO

		annotation SummarizationSetBy = Automatic

	partition 流程数据-adaa1046-5572-4413-a15e-c24c29277f5b = m
		mode: import
		source =
				let
				    源 = Oracle.Database("172.16.8.76/oracledb", [HierarchicalNavigation=true]),
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_YFJFTRGLZB1 = GSPM{[Name="GSPM_YFJFTRGLZB"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_YFJFTRGLZB1,{"FID", "FPINGSHENZHUANGTAI", "SCREATOROGNNAME", "SCREATOROGNCODE", "FYEWUDANHAO", "FYFXMKTBH", "FYFXMKTMC"}),
				    筛选的行1 = Table.SelectRows(删除的其他列, each ([FPINGSHENZHUANGTAI] <> "已完成")),
				    合并的查询 = Table.NestedJoin(筛选的行1, {"FID"}, SA_TASK, {"SDATA1"}, "SA_TASK", JoinKind.LeftOuter),
				    #"展开的“SA_TASK”" = Table.ExpandTableColumn(合并的查询, "SA_TASK", {"SNAME", "SCATALOGID", "SKINDID", "STYPENAME", "SACTIVITY", "SCREATETIME", "SACTUALSTARTTIME", "SACTUALFINISHTIME", "SEXECUTORPERSONNAME", "SEXECUTORPOSNAME"}, {"SNAME", "SCATALOGID", "SKINDID", "STYPENAME", "SACTIVITY", "SCREATETIME", "SACTUALSTARTTIME", "SACTUALFINISHTIME", "SEXECUTORPERSONNAME", "SEXECUTORPOSNAME"}),
				    筛选的行 = Table.SelectRows(#"展开的“SA_TASK”", each ([SKINDID] = "tkTask")),
				    排序的行 = Table.Sort(筛选的行,{{"FID", Order.Ascending}, {"SCREATETIME", Order.Ascending}}),
				    已添加索引 = Table.AddIndexColumn(排序的行, "索引", 1, 1, Int64.Type),
				    已添加条件列 = Table.AddColumn(已添加索引, "自定义", each if [SACTUALFINISHTIME] = null then 1 else 0),
				    更改的类型 = Table.TransformColumnTypes(已添加条件列,{{"自定义", Int64.Type}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

