{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "name": "模型",
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "Oracle/172 16 8 78/oracledb",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.76/oracledb"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "Oracle",
          "path": "172.16.8.76/oracledb",
          "Username": "gspm",
          "PrivacySetting": "Public"
        }
      },
      {
        "type": "structured",
        "name": "Oracle/172 16 8 87/cscecdb",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.87/cscecdb"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "Oracle",
          "path": "172.16.8.87/cscecdb",
          "Username": "fzhr",
          "PrivacySetting": "Public"
        }
      }
    ],
    "tables": [
      {
        "name": "离职年龄段",
        "columns": [
          {
            "name": "数值",
            "dataType": "string",
            "sourceColumn": "数值"
          },
          {
            "name": "段数",
            "dataType": "string",
            "sourceColumn": "段数"
          },
          {
            "name": "下限",
            "dataType": "string",
            "sourceColumn": "下限"
          },
          {
            "name": "上限",
            "dataType": "string",
            "sourceColumn": "上限"
          },
          {
            "name": "段名称",
            "dataType": "string",
            "sourceColumn": "段名称"
          },
          {
            "name": "段名称2",
            "dataType": "string",
            "sourceColumn": "段名称2"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = CreateS(设置区间值),",
                "    已添加自定义 = Table.AddColumn(源, \"段名称2\", each if[数值]<=35 then \"35-\" else if [数值]>35 and [数值]<=45 then \"36-45\" else if [数值]>45 and [数值]<= 60 then \"46-60\" else \"61+\"),",
                "    筛选的行 = Table.SelectRows(已添加自定义, each [数值] <> null)",
                "in",
                "    筛选的行"
              ]
            }
          }
        ]
      },
      {
        "name": "员工信息表",
        "columns": [
          {
            "name": "FGUID",
            "dataType": "string",
            "sourceColumn": "FGUID"
          },
          {
            "name": "FSTATE",
            "dataType": "string",
            "sourceColumn": "FSTATE"
          },
          {
            "name": "FBILLSTATE",
            "dataType": "string",
            "sourceColumn": "FBILLSTATE"
          },
          {
            "name": "编码",
            "dataType": "string",
            "sourceColumn": "编码"
          },
          {
            "name": "姓名",
            "dataType": "string",
            "sourceColumn": "姓名"
          },
          {
            "name": "性别",
            "dataType": "string",
            "sourceColumn": "性别"
          },
          {
            "name": "民族",
            "dataType": "string",
            "sourceColumn": "民族"
          },
          {
            "name": "籍贯",
            "dataType": "string",
            "sourceColumn": "籍贯"
          },
          {
            "name": "出生日期",
            "dataType": "dateTime",
            "sourceColumn": "出生日期"
          },
          {
            "name": "离职日期",
            "dataType": "dateTime",
            "sourceColumn": "离职日期"
          },
          {
            "name": "单位类别",
            "dataType": "string",
            "sourceColumn": "单位类别"
          },
          {
            "name": "档案出生日期",
            "dataType": "dateTime",
            "sourceColumn": "档案出生日期"
          },
          {
            "name": "参加工作日期",
            "dataType": "dateTime",
            "sourceColumn": "参加工作日期"
          },
          {
            "name": "职务编码",
            "dataType": "string",
            "sourceColumn": "职务编码"
          },
          {
            "name": "岗位编码",
            "dataType": "string",
            "sourceColumn": "岗位编码"
          },
          {
            "name": "部门编码",
            "dataType": "string",
            "sourceColumn": "部门编码"
          },
          {
            "name": "本单位入职日期",
            "dataType": "dateTime",
            "sourceColumn": "本单位入职日期"
          },
          {
            "name": "员工状态",
            "dataType": "string",
            "sourceColumn": "员工状态"
          },
          {
            "name": "政治面貌",
            "dataType": "string",
            "sourceColumn": "政治面貌"
          },
          {
            "name": "职称",
            "dataType": "string",
            "sourceColumn": "职称"
          },
          {
            "name": "学历",
            "dataType": "string",
            "sourceColumn": "学历"
          },
          {
            "name": "FIDENTITY",
            "dataType": "string",
            "sourceColumn": "FIDENTITY"
          },
          {
            "name": "入职类别",
            "dataType": "string",
            "sourceColumn": "入职类别"
          },
          {
            "name": "聘用形式",
            "dataType": "string",
            "sourceColumn": "聘用形式"
          },
          {
            "name": "员工类别",
            "dataType": "string",
            "sourceColumn": "员工类别"
          },
          {
            "name": "起薪日期",
            "dataType": "dateTime",
            "sourceColumn": "起薪日期"
          },
          {
            "name": "档案存放地",
            "dataType": "string",
            "sourceColumn": "档案存放地"
          },
          {
            "name": "员工属地",
            "dataType": "string",
            "sourceColumn": "员工属地"
          },
          {
            "name": "京内外",
            "dataType": "string",
            "sourceColumn": "京内外"
          },
          {
            "type": "calculated",
            "name": "离职年龄",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK('员工信息表'[离职日期]),BLANK(),INT(YEARFRAC('员工信息表'[出生日期],'员工信息表'[离职日期])))",
            "lineageTag": "3e4a8c2d-36d5-43da-8fce-61ae5cdf859a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "年龄",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "INT(YEARFRAC('员工信息表'[出生日期],NOW()))",
            "formatString": "0",
            "lineageTag": "528fdd27-0179-4b03-819e-c5c7d3d431b1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "司龄",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "INT(YEARFRAC('员工信息表'[本单位入职日期],NOW()))",
            "formatString": "0",
            "lineageTag": "69fc01c1-a61e-4dbf-8f0f-d9f446dfee8d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "学历 (groups)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('员工信息表'[学历]),",
              "  \"(空白)\",",
              "  '员工信息表'[学历] IN {\"初级中学\",",
              "    \"高级中学\",",
              "    \"未知\",",
              "    \"无\",",
              "    \"小学\",",
              "    \"职业高中\",",
              "    \"中等专科\",",
              "    \"专业中专\"},",
              "  \"中专及以下\",",
              "  '员工信息表'[学历] IN {\"大学专科\",",
              "    \"专业大专\"},",
              "  \"大专\",",
              "  '员工信息表'[学历] IN {\"大学本科\",",
              "    \"大学本科双学位\"},",
              "  \"本科\",",
              "  '员工信息表'[学历] IN {\"博士研究生\",",
              "    \"硕士研究生\"},",
              "  \"硕士及以上\",",
              "  '员工信息表'[学历]",
              ")"
            ],
            "lineageTag": "9d646f9f-4894-475e-9ea2-e9b42fee30c0",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "员工信息表"
                          }
                        },
                        "Property": "学历"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"员\",\"Entity\":\"员工信息表\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"学历\"}}],\"GroupItems\":[{\"DisplayName\":\"(空白)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"中专及以下\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"学历\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'初级中学'\"}}],[{\"Literal\":{\"Value\":\"'高级中学'\"}}],[{\"Literal\":{\"Value\":\"'未知'\"}}],[{\"Literal\":{\"Value\":\"'无'\"}}],[{\"Literal\":{\"Value\":\"'小学'\"}}],[{\"Literal\":{\"Value\":\"'职业高中'\"}}],[{\"Literal\":{\"Value\":\"'中等专科'\"}}],[{\"Literal\":{\"Value\":\"'专业中专'\"}}]]}}},{\"DisplayName\":\"大专\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"学历\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'大学专科'\"}}],[{\"Literal\":{\"Value\":\"'专业大专'\"}}]]}}},{\"DisplayName\":\"本科\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"学历\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'大学本科'\"}}],[{\"Literal\":{\"Value\":\"'大学本科双学位'\"}}]]}}},{\"DisplayName\":\"硕士及以上\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"学历\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'博士研究生'\"}}],[{\"Literal\":{\"Value\":\"'硕士研究生'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "入职类别 (组)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('员工信息表'[入职类别]),",
              "  \"(空白)\",",
              "  '员工信息表'[入职类别] IN {\"外单位借入\",",
              "    \"在职调入\"},",
              "  \"调入\",",
              "  '员工信息表'[入职类别] IN {\"退休返聘\",",
              "    \"退休返聘（特殊）\"},",
              "  \"返聘\",",
              "  '员工信息表'[入职类别] IN {\"军队转业\"},",
              "  \"军队转业\",",
              "  '员工信息表'[入职类别] IN {\"劳务公司派遣\",",
              "    \"劳务公司派遣（协议）\",",
              "    \"劳务公司派遣新生\"},",
              "  \"劳务派遣\",",
              "  '员工信息表'[入职类别] IN {\"未知\"},",
              "  \"未知\",",
              "  '员工信息表'[入职类别] IN {\"新生分配\"},",
              "  \"新生分配\",",
              "  '员工信息表'[入职类别] IN {\"公司招工\",",
              "    \"社会招聘\",",
              "    \"社会招聘（协议）\",",
              "    \"新生落户\"},",
              "  \"招聘\",",
              "  '员工信息表'[入职类别] IN {\"政府安置\"},",
              "  \"政府安置\",",
              "  '员工信息表'[入职类别]",
              ")"
            ],
            "lineageTag": "675e7091-5fb6-4fd3-90f5-18dd1b46d2aa",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "员工信息表"
                          }
                        },
                        "Property": "入职类别"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"员\",\"Entity\":\"员工信息表\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"GroupItems\":[{\"DisplayName\":\"(空白)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"调入\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'外单位借入'\"}}],[{\"Literal\":{\"Value\":\"'在职调入'\"}}]]}}},{\"DisplayName\":\"返聘\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'退休返聘'\"}}],[{\"Literal\":{\"Value\":\"'退休返聘（特殊）'\"}}]]}}},{\"DisplayName\":\"军队转业\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'军队转业'\"}}]]}}},{\"DisplayName\":\"劳务派遣\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'劳务公司派遣'\"}}],[{\"Literal\":{\"Value\":\"'劳务公司派遣（协议）'\"}}],[{\"Literal\":{\"Value\":\"'劳务公司派遣新生'\"}}]]}}},{\"DisplayName\":\"未知\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'未知'\"}}]]}}},{\"DisplayName\":\"新生分配\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'新生分配'\"}}]]}}},{\"DisplayName\":\"招聘\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'公司招工'\"}}],[{\"Literal\":{\"Value\":\"'社会招聘'\"}}],[{\"Literal\":{\"Value\":\"'社会招聘（协议）'\"}}],[{\"Literal\":{\"Value\":\"'新生落户'\"}}]]}}},{\"DisplayName\":\"政府安置\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"员\"}},\"Property\":\"入职类别\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'政府安置'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = cscecdb,",
                "    FZHR = 源{[Schema=\"FZHR\"]}[Data],",
                "    HR_EMPLOYEEINFO1 = FZHR{[Name=\"HR_EMPLOYEEINFO\"]}[Data],",
                "    重命名的列 = Table.RenameColumns(HR_EMPLOYEEINFO1,{{\"FCODE\", \"编码\"}, {\"FNAME\", \"姓名\"}, {\"FSEX\", \"性别\"}, {\"FNATIONALITY\", \"民族\"}, {\"FNATIVEPLACE\", \"籍贯\"}, {\"FBIRTHDATE\", \"出生日期\"}, {\"FDIMISSDATE\", \"离职日期\"}, {\"FFILEBIRTHDATE\", \"档案出生日期\"}, {\"FJOINWORKDATE\", \"参加工作日期\"}, {\"FPOSITIONCODE\", \"职务编码\"}, {\"FSTATIONCODE\", \"岗位编码\"}, {\"FDEPTCODE\", \"部门编码\"}, {\"FINTOCOMPANYDATE\", \"本单位入职日期\"}, {\"FEMPLOYEESTATE\", \"员工状态\"}, {\"FPOLITICSSTATUS\", \"政治面貌\"}, {\"FOFFICE\", \"职称\"}, {\"FEDUCATION\", \"学历\"}, {\"FFOLDTYPE\", \"入职类别\"}, {\"FEMPLOYFORM\", \"聘用形式\"}, {\"FEMPLOYEETYPE\", \"员工类别\"}, {\"FSTARTINGSALARYDATE\", \"起薪日期\"}, {\"FFILEDEPOSITSTATE\", \"档案存放地\"}, {\"FEXTENSIONVAR2\", \"员工属地\"}, {\"FDEPTKIND\", \"单位类别\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"本单位入职日期\", type date}, {\"出生日期\", type date}}),",
                "    删除的其他列 = Table.SelectColumns(更改的类型,{\"FGUID\", \"FSTATE\", \"FBILLSTATE\", \"编码\", \"姓名\", \"性别\", \"民族\", \"籍贯\", \"出生日期\", \"离职日期\", \"单位类别\", \"档案出生日期\", \"参加工作日期\", \"职务编码\", \"岗位编码\", \"部门编码\", \"本单位入职日期\", \"员工状态\", \"政治面貌\", \"职称\", \"学历\", \"FIDENTITY\", \"入职类别\", \"聘用形式\", \"员工类别\", \"起薪日期\", \"档案存放地\", \"员工属地\"}),",
                "    合并的查询 = Table.NestedJoin(删除的其他列,{\"部门编码\"},单位,{\"单位编码\"},\"单位\",JoinKind.LeftOuter),",
                "    #\"展开的“单位”\" = Table.ExpandTableColumn(合并的查询, \"单位\", {\"京内外\"}, {\"京内外\"})",
                "in",
                "    #\"展开的“单位”\""
              ]
            }
          }
        ]
      },
      {
        "name": "单位",
        "columns": [
          {
            "name": "单位编码",
            "dataType": "string",
            "sourceColumn": "单位编码"
          },
          {
            "name": "单位名称",
            "dataType": "string",
            "sourceColumn": "单位名称"
          },
          {
            "name": "京内外",
            "dataType": "string",
            "sourceColumn": "京内外"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": "单位"
            }
          }
        ]
      },
      {
        "name": "岗位",
        "columns": [
          {
            "name": "FGUID",
            "dataType": "string",
            "sourceColumn": "FGUID"
          },
          {
            "name": "岗位名称",
            "dataType": "string",
            "sourceColumn": "岗位名称"
          },
          {
            "name": "所属系统",
            "dataType": "string",
            "sourceColumn": "所属系统"
          },
          {
            "type": "calculated",
            "name": "所属系统 (组)",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "SWITCH(",
              "  TRUE,",
              "  ISBLANK('岗位'[所属系统]),",
              "  \"(空白)\",",
              "  '岗位'[所属系统] IN {\"公司领导\",",
              "    \"公司领导-安全\",",
              "    \"公司领导-财务\",",
              "    \"公司领导-技术\",",
              "    \"公司领导-商务\",",
              "    \"公司领导-现场\",",
              "    \"公司领导-综合管理\"},",
              "  \"公司领导\",",
              "  '岗位'[所属系统] IN {\"安全\"},",
              "  \"安全\",",
              "  '岗位'[所属系统] IN {\"投资建造\"},",
              "  \"投资建造\",",
              "  '岗位'[所属系统] IN {\"机电\",",
              "    \"机电商务\"},",
              "  \"机电\",",
              "  '岗位'[所属系统] IN {\"技术\",",
              "    \"专家\"},",
              "  \"科技研发\",",
              "  '岗位'[所属系统] IN {\"操作\",",
              "    \"党群\",",
              "    \"综合\",",
              "    \"综合管理\"},",
              "  \"综合管理\",",
              "  '岗位'[所属系统] IN {\"商务\",",
              "    \"营销\"},",
              "  \"营销商务\",",
              "  '岗位'[所属系统] IN {\"财务\"},",
              "  \"财务\",",
              "  '岗位'[所属系统] IN {\"质量\"},",
              "  \"质量\",",
              "  '岗位'[所属系统] IN {\"钢结构\"},",
              "  \"钢结构与工业化\",",
              "  '岗位'[所属系统] IN {\"现场\"},",
              "  \"项目管理\",",
              "  '岗位'[所属系统]",
              ")"
            ],
            "lineageTag": "7a774650-f2d4-4b21-8fca-ef2bbdaad8c5",
            "summarizeBy": "none",
            "extendedProperties": [
              {
                "type": "json",
                "name": "GroupingMetadata",
                "value": {
                  "version": 0,
                  "groupedColumns": [
                    {
                      "Column": {
                        "Expression": {
                          "SourceRef": {
                            "Entity": "岗位"
                          }
                        },
                        "Property": "所属系统"
                      }
                    }
                  ]
                }
              }
            ],
            "annotations": [
              {
                "name": "GroupingDesignState",
                "value": "{\"Version\":0,\"Sources\":[{\"Name\":\"岗\",\"Entity\":\"岗位\"}],\"GroupedColumns\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"GroupItems\":[{\"DisplayName\":\"(空白)\",\"BlankDefaultPlaceholder\":true},{\"DisplayName\":\"公司领导\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'公司领导'\"}}],[{\"Literal\":{\"Value\":\"'公司领导-安全'\"}}],[{\"Literal\":{\"Value\":\"'公司领导-财务'\"}}],[{\"Literal\":{\"Value\":\"'公司领导-技术'\"}}],[{\"Literal\":{\"Value\":\"'公司领导-商务'\"}}],[{\"Literal\":{\"Value\":\"'公司领导-现场'\"}}],[{\"Literal\":{\"Value\":\"'公司领导-综合管理'\"}}]]}}},{\"DisplayName\":\"安全\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'安全'\"}}]]}}},{\"DisplayName\":\"投资建造\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'投资建造'\"}}]]}}},{\"DisplayName\":\"机电\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'机电'\"}}],[{\"Literal\":{\"Value\":\"'机电商务'\"}}]]}}},{\"DisplayName\":\"科技研发\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'技术'\"}}],[{\"Literal\":{\"Value\":\"'专家'\"}}]]}}},{\"DisplayName\":\"综合管理\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'操作'\"}}],[{\"Literal\":{\"Value\":\"'党群'\"}}],[{\"Literal\":{\"Value\":\"'综合'\"}}],[{\"Literal\":{\"Value\":\"'综合管理'\"}}]]}}},{\"DisplayName\":\"营销商务\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'商务'\"}}],[{\"Literal\":{\"Value\":\"'营销'\"}}]]}}},{\"DisplayName\":\"财务\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'财务'\"}}]]}}},{\"DisplayName\":\"质量\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'质量'\"}}]]}}},{\"DisplayName\":\"钢结构与工业化\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'钢结构'\"}}]]}}},{\"DisplayName\":\"项目管理\",\"Expression\":{\"In\":{\"Expressions\":[{\"Column\":{\"Expression\":{\"SourceRef\":{\"Source\":\"岗\"}},\"Property\":\"所属系统\"}}],\"Values\":[[{\"Literal\":{\"Value\":\"'现场'\"}}]]}}}]}"
              },
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = cscecdb,",
                "    FZHR = 源{[Schema=\"FZHR\"]}[Data],",
                "    HR_STATION = FZHR{[Name=\"HR_STATION\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(HR_STATION,{\"FGUID\", \"FNAME\", \"FOWNEDSPECIAL\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FNAME\", \"岗位名称\"}, {\"FOWNEDSPECIAL\", \"所属系统\"}})",
                "in",
                "    重命名的列"
              ]
            }
          }
        ]
      },
      {
        "name": "职务",
        "columns": [
          {
            "name": "FGUID",
            "dataType": "string",
            "sourceColumn": "FGUID"
          },
          {
            "name": "FSTATE",
            "dataType": "string",
            "sourceColumn": "FSTATE"
          },
          {
            "name": "FCODE",
            "dataType": "string",
            "sourceColumn": "FCODE"
          },
          {
            "name": "职务名称",
            "dataType": "string",
            "sourceColumn": "职务名称"
          },
          {
            "name": "FKIND",
            "dataType": "string",
            "sourceColumn": "FKIND"
          },
          {
            "name": "FLEVEL",
            "dataType": "string",
            "sourceColumn": "FLEVEL"
          },
          {
            "name": "FPUBLICOFFICE",
            "dataType": "string",
            "sourceColumn": "FPUBLICOFFICE"
          },
          {
            "name": "FDISNABLED",
            "dataType": "string",
            "sourceColumn": "FDISNABLED"
          },
          {
            "name": "FREMARK",
            "dataType": "string",
            "sourceColumn": "FREMARK"
          },
          {
            "name": "FORDER",
            "dataType": "double",
            "sourceColumn": "FORDER"
          },
          {
            "name": "FDATE",
            "dataType": "dateTime",
            "sourceColumn": "FDATE"
          },
          {
            "name": "FDEPT",
            "dataType": "string",
            "sourceColumn": "FDEPT"
          },
          {
            "name": "FPOSITION",
            "dataType": "string",
            "sourceColumn": "FPOSITION"
          },
          {
            "name": "FOPERATOR",
            "dataType": "string",
            "sourceColumn": "FOPERATOR"
          },
          {
            "name": "FCREATORID",
            "dataType": "string",
            "sourceColumn": "FCREATORID"
          },
          {
            "name": "FCREATORNAME",
            "dataType": "string",
            "sourceColumn": "FCREATORNAME"
          },
          {
            "name": "FCREATDEPTID",
            "dataType": "string",
            "sourceColumn": "FCREATDEPTID"
          },
          {
            "name": "FCREATDEPTNAME",
            "dataType": "string",
            "sourceColumn": "FCREATDEPTNAME"
          },
          {
            "name": "FCREATTIME",
            "dataType": "dateTime",
            "sourceColumn": "FCREATTIME"
          },
          {
            "name": "FREVISEID",
            "dataType": "string",
            "sourceColumn": "FREVISEID"
          },
          {
            "name": "FREVISENAME",
            "dataType": "string",
            "sourceColumn": "FREVISENAME"
          },
          {
            "name": "FREVISEDEPTID",
            "dataType": "string",
            "sourceColumn": "FREVISEDEPTID"
          },
          {
            "name": "FREVISEDEPTNAME",
            "dataType": "string",
            "sourceColumn": "FREVISEDEPTNAME"
          },
          {
            "name": "FREVISETIME",
            "dataType": "dateTime",
            "sourceColumn": "FREVISETIME"
          },
          {
            "name": "FEXTENSIONVAR1",
            "dataType": "string",
            "sourceColumn": "FEXTENSIONVAR1"
          },
          {
            "name": "FEXTENSIONVAR2",
            "dataType": "string",
            "sourceColumn": "FEXTENSIONVAR2"
          },
          {
            "name": "FEXTENSIONVAR3",
            "dataType": "string",
            "sourceColumn": "FEXTENSIONVAR3"
          },
          {
            "name": "LSFL",
            "dataType": "string",
            "sourceColumn": "LSFL"
          },
          {
            "name": "VERSION",
            "dataType": "double",
            "sourceColumn": "VERSION"
          },
          {
            "name": "FZWXS",
            "dataType": "double",
            "sourceColumn": "FZWXS"
          },
          {
            "name": "FFBZ1",
            "dataType": "double",
            "sourceColumn": "FFBZ1"
          },
          {
            "name": "FFBZ2",
            "dataType": "double",
            "sourceColumn": "FFBZ2"
          },
          {
            "name": "FFBZ3",
            "dataType": "double",
            "sourceColumn": "FFBZ3"
          },
          {
            "name": "FFBZ4",
            "dataType": "double",
            "sourceColumn": "FFBZ4"
          },
          {
            "name": "ZWDJ",
            "dataType": "string",
            "sourceColumn": "ZWDJ"
          },
          {
            "name": "XJQSZ",
            "dataType": "string",
            "sourceColumn": "XJQSZ"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = cscecdb,",
                "    FZHR = 源{[Schema=\"FZHR\"]}[Data],",
                "    HR_POSITION1 = FZHR{[Name=\"HR_POSITION\"]}[Data],",
                "    重命名的列 = Table.RenameColumns(HR_POSITION1,{{\"FNAME\", \"职务名称\"}})",
                "in",
                "    重命名的列"
              ]
            }
          }
        ]
      },
      {
        "name": "执证情况",
        "columns": [
          {
            "name": "员工编码",
            "dataType": "string",
            "sourceColumn": "员工编码"
          },
          {
            "name": "姓名",
            "dataType": "string",
            "sourceColumn": "姓名"
          },
          {
            "name": "证书编号",
            "dataType": "string",
            "sourceColumn": "证书编号"
          },
          {
            "name": "证书名称",
            "dataType": "string",
            "sourceColumn": "证书名称"
          },
          {
            "name": "发证机关",
            "dataType": "string",
            "sourceColumn": "发证机关"
          },
          {
            "name": "等级",
            "dataType": "string",
            "sourceColumn": "等级"
          },
          {
            "name": "发证日期",
            "dataType": "dateTime",
            "sourceColumn": "发证日期"
          },
          {
            "name": "专业",
            "dataType": "string",
            "sourceColumn": "专业"
          },
          {
            "name": "注册专业证书名称",
            "dataType": "string",
            "sourceColumn": "注册专业证书名称"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = cscecdb,",
                "    FZHR = 源{[Schema=\"FZHR\"]}[Data],",
                "    V_BOOKNAME2 = FZHR{[Name=\"HR_QUALIFICATION\"]}[Data],",
                "    重命名的列 = Table.RenameColumns(V_BOOKNAME2,{{\"FCODE\", \"员工编码\"}, {\"FNAME\", \"姓名\"}, {\"FBOOKCODE\", \"证书编号\"}, {\"FBOOKNAME\", \"证书名称\"}, {\"FISSUER\", \"发证机关\"}, {\"FQUALIFICATION\", \"等级\"}, {\"FFZDATE\", \"发证日期\"}, {\"FSPECIAL\", \"专业\"}, {\"FZYNAME\", \"注册专业证书名称\"}, {\"ZSLB\", \"证书类别\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"员工编码\", \"姓名\", \"证书编号\", \"证书名称\", \"发证机关\", \"等级\", \"发证日期\", \"专业\", \"注册专业证书名称\"})",
                "in",
                "    删除的其他列"
              ]
            }
          }
        ]
      },
      {
        "name": "员工离职表",
        "columns": [
          {
            "name": "员工编码",
            "dataType": "string",
            "sourceColumn": "员工编码"
          },
          {
            "name": "姓名",
            "dataType": "string",
            "sourceColumn": "姓名"
          },
          {
            "name": "性别",
            "dataType": "string",
            "sourceColumn": "性别"
          },
          {
            "name": "离职时单位",
            "dataType": "string",
            "sourceColumn": "离职时单位"
          },
          {
            "name": "离职时职务",
            "dataType": "string",
            "sourceColumn": "离职时职务"
          },
          {
            "name": "离职时岗位",
            "dataType": "string",
            "sourceColumn": "离职时岗位"
          },
          {
            "name": "离职类型",
            "dataType": "string",
            "sourceColumn": "离职类型"
          },
          {
            "name": "离职时间",
            "dataType": "dateTime",
            "sourceColumn": "离职时间"
          },
          {
            "name": "去向",
            "dataType": "string",
            "sourceColumn": "去向"
          },
          {
            "type": "calculated",
            "name": "离职年龄",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK('员工离职表'[离职时间]),BLANK(),INT(YEARFRAC('员工离职表'[出生日期],'员工离职表'[离职时间])))",
            "formatString": "0",
            "lineageTag": "0a915bc4-21f9-4429-8fd9-4f70dc411c10",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "出生日期",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": "RELATED('员工生日表'[出生日期])",
            "formatString": "General Date",
            "lineageTag": "cb4b8573-3d10-4e5d-a046-63ce8e2e16ce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = cscecdb,",
                "    FZHR = 源{[Schema=\"FZHR\"]}[Data],",
                "    HR_SEPARATION1 = FZHR{[Name=\"HR_SEPARATION\"]}[Data],",
                "    重命名的列 = Table.RenameColumns(HR_SEPARATION1,{{\"FCODE\", \"员工编码\"}, {\"FNAME\", \"姓名\"}, {\"FSEX\", \"性别\"}, {\"FDEPTNAME\", \"离职时单位\"}, {\"FPOSITIONNAME\", \"离职时职务\"}, {\"FSTATIONNAME\", \"离职时岗位\"}, {\"FSEPARATIONKIND\", \"离职类型\"}, {\"FGOWHERE\", \"去向\"}, {\"FSEPARATIONDATE\", \"离职时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"员工编码\", \"姓名\", \"性别\", \"离职时单位\", \"离职时职务\", \"离职时岗位\", \"离职类型\", \"离职时间\", \"去向\"}),",
                "    替换的值 = Table.ReplaceValue(删除的其他列,\"转行回老家\",\"回老家\",Replacer.ReplaceText,{\"去向\"})",
                "in",
                "    替换的值"
              ]
            }
          }
        ]
      },
      {
        "name": "司龄段",
        "columns": [
          {
            "name": "数值",
            "dataType": "int64",
            "sourceColumn": "数值"
          },
          {
            "name": "段数",
            "dataType": "int64",
            "sourceColumn": "段数"
          },
          {
            "name": "下限",
            "dataType": "string",
            "sourceColumn": "下限"
          },
          {
            "name": "上限",
            "dataType": "string",
            "sourceColumn": "上限"
          },
          {
            "name": "段名称",
            "dataType": "string",
            "sourceColumn": "段名称"
          },
          {
            "name": "段名称2",
            "dataType": "string",
            "sourceColumn": "段名称2"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = CreateS(5),",
                "    已添加自定义 = Table.AddColumn(源, \"段名称2\", each if[数值]<=35 then \"35-\" else if [数值]>35 and [数值]<=45 then \"36-45\" else if [数值]>45 and [数值]<= 60 then \"46-60\" else \"61+\"),",
                "    筛选的行 = Table.SelectRows(已添加自定义, each [数值] <> null),",
                "    更改的类型 = Table.TransformColumnTypes(筛选的行,{{\"段数\", Int64.Type}, {\"数值\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ]
      },
      {
        "name": "年龄段",
        "columns": [
          {
            "name": "数值",
            "dataType": "string",
            "sourceColumn": "数值"
          },
          {
            "name": "段数",
            "dataType": "string",
            "sourceColumn": "段数"
          },
          {
            "name": "下限",
            "dataType": "string",
            "sourceColumn": "下限"
          },
          {
            "name": "上限",
            "dataType": "string",
            "sourceColumn": "上限"
          },
          {
            "name": "段名称",
            "dataType": "string",
            "sourceColumn": "段名称"
          },
          {
            "name": "段名称2",
            "dataType": "string",
            "sourceColumn": "段名称2"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = CreateS(设置区间值),",
                "    已添加自定义 = Table.AddColumn(源, \"段名称2\", each if[数值]<=35 then \"35-\" else if [数值]>35 and [数值]<=45 then \"36-45\" else if [数值]>45 and [数值]<= 60 then \"46-60\" else \"61+\"),",
                "    筛选的行 = Table.SelectRows(已添加自定义, each [数值] <> null)",
                "in",
                "    筛选的行"
              ]
            }
          }
        ]
      },
      {
        "name": "业务口人员司龄段",
        "columns": [
          {
            "name": "数值",
            "dataType": "int64",
            "sourceColumn": "数值"
          },
          {
            "name": "段数",
            "dataType": "int64",
            "sourceColumn": "段数"
          },
          {
            "name": "下限",
            "dataType": "int64",
            "sourceColumn": "下限"
          },
          {
            "name": "上限",
            "dataType": "int64",
            "sourceColumn": "上限"
          },
          {
            "name": "段名称",
            "dataType": "string",
            "sourceColumn": "段名称"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = CreateS(3),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"数值\", Int64.Type}, {\"段数\", Int64.Type}, {\"下限\", Int64.Type}, {\"上限\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ]
      },
      {
        "name": "项目信息",
        "columns": [
          {
            "name": "项目编码",
            "dataType": "string",
            "sourceColumn": "项目编码"
          },
          {
            "name": "项目名称",
            "dataType": "string",
            "sourceColumn": "项目名称"
          },
          {
            "name": "省",
            "dataType": "string",
            "sourceColumn": "省"
          },
          {
            "name": "市",
            "dataType": "string",
            "sourceColumn": "市"
          },
          {
            "name": "县",
            "dataType": "string",
            "sourceColumn": "县"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Oracle.Database(\"172.16.8.76/oracledb\", [HierarchicalNavigation=true]),",
                "    MD = 源{[Schema=\"MD\"]}[Data],",
                "    MD_XIANGMUXINXI1 = MD{[Name=\"MD_XIANGMUXINXI\"]}[Data],",
                "    删除的其他列 = Table.SelectColumns(MD_XIANGMUXINXI1,{\"FXMBIANMA\", \"FXMQUANCHENG\", \"FSHENG\", \"FCHENGSHI\", \"FXIAN\"}),",
                "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FXMBIANMA\", \"项目编码\"}, {\"FSHENG\", \"省\"}, {\"FCHENGSHI\", \"市\"}, {\"FXIAN\", \"县\"}, {\"FXMQUANCHENG\", \"项目名称\"}}),",
                "    筛选的行 = Table.SelectRows(重命名的列, each ([项目名称] <> null))",
                "in",
                "    筛选的行"
              ]
            }
          }
        ]
      },
      {
        "name": "日历",
        "lineageTag": "fcc0a863-ad50-40a1-92e4-b56b9b7993fa",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "日期",
            "dataType": "dateTime",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Date]",
            "formatString": "General Date",
            "lineageTag": "721291e7-5b8a-4f34-8de8-9a2ec14b0181",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "年",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('日历'[日期],\"yyyy\")",
            "lineageTag": "53d685ae-d54c-45d2-9aa7-32aca9d5353a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "月",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('日历'[日期],\"yyyy-MM\")",
            "lineageTag": "d64001e1-14f6-40d4-a10f-f776e6d3a5d9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "日",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('日历'[日期],\"yyyy-MM-dd\")",
            "lineageTag": "0ddc669f-b83c-47a0-b98c-77a603acb54f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "表-b0676706-d910-4c1c-949b-e334bda80451",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "CALENDAR(\"2005-1-1\",TODAY())"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "年 层次结构",
            "lineageTag": "4bb6f936-058f-42f5-a223-21b360e39e77",
            "levels": [
              {
                "name": "年",
                "ordinal": 0,
                "column": "年",
                "lineageTag": "6dbf3fc6-e193-4bd4-964c-eff3d8d0db4c"
              },
              {
                "name": "日",
                "ordinal": 2,
                "column": "日",
                "lineageTag": "d47be5fa-9129-4717-9fb0-669c33e8e9cc"
              },
              {
                "name": "月",
                "ordinal": 1,
                "column": "月",
                "lineageTag": "3c95fa80-9aec-4fe9-9d8a-a454cf0fd45a"
              }
            ]
          }
        ]
      },
      {
        "name": "员工单位类别",
        "lineageTag": "6f0d84b7-b766-4ccf-be16-fd9404958768",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "编码",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "员工信息表[编码]",
            "lineageTag": "4f95a014-120e-4850-aefb-a77362fa9d07",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "单位类别",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "员工信息表[单位类别]",
            "lineageTag": "433b68e2-a86a-4402-a19e-870f757339af",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "员工单位类别-c3ccd662-6633-46f2-92cb-2e3cc2528077",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('员工信息表','员工信息表'[编码],'员工信息表'[单位类别])"
            }
          }
        ]
      },
      {
        "name": "员工生日表",
        "lineageTag": "f4f3fd81-40b4-4300-bc43-72900d5d72bf",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "编码",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "员工信息表[编码]",
            "lineageTag": "b40703fd-ac6e-4c8f-9448-cfaadfaa0c62",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "出生日期",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "员工信息表[出生日期]",
            "formatString": "General Date",
            "lineageTag": "049cab69-63ce-4b6d-b17b-731a13fe68de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "员工生日表-3717c903-6c34-4208-85fb-36c6b9069f7f",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "GROUPBY('员工信息表','员工信息表'[编码],'员工信息表'[出生日期])"
            }
          }
        ]
      },
      {
        "name": "度量值表",
        "lineageTag": "078acb26-332d-4f6e-b722-f1b0393e208b",
        "columns": [
          {
            "name": "列 1",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "列 1",
            "lineageTag": "c81e3257-2600-4b7f-95c4-250c7528052c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_ChangedProperties",
                "value": "[\"IsHidden\"]"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "度量值表-2739992d-3e1b-4d7a-ba33-537f7dab83e6",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [#\"列 1\" = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"列 1\", type text}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【人员计数】",
            "expression": "DISTINCTCOUNT('员工信息表'[编码])",
            "formatString": "0",
            "lineageTag": "584abf6a-2439-491d-a6fd-a606ff3e7df3"
          },
          {
            "name": "岗位离职前20",
            "expression": [
              "IF ( ",
              "        RANKX(ALL('岗位'),  [【人员计数】]) <= 15, ",
              "        [【人员计数】],",
              "        BLANK() ",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "00380e55-8463-4477-b84d-50bb37c6777f"
          },
          {
            "name": "【离职计数】",
            "expression": "DISTINCTCOUNT('员工离职表'[员工编码])",
            "formatString": "0",
            "lineageTag": "5c36a96f-2831-4ec4-a7ac-4c9addbbc7e4"
          },
          {
            "name": "【平均年龄】",
            "expression": "AVERAGE('员工信息表'[年龄])",
            "lineageTag": "5948f3ac-4c3a-49a7-b771-eeac9927826e",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "【县】",
            "expression": "SELECTEDVALUE('项目信息'[县])",
            "lineageTag": "64b1d17d-4a69-450d-a4da-d5721478f5e0"
          },
          {
            "name": "【人员增减】",
            "expression": "[【人员计数】]-[【离职人数】]",
            "formatString": "0",
            "lineageTag": "56fc2eab-4566-49c7-8908-7b1b9a1d5c50"
          },
          {
            "name": "【离职人数】",
            "expression": "DISTINCTCOUNT('员工离职表'[员工编码])",
            "formatString": "0",
            "lineageTag": "88f1c8f5-cba1-47aa-888b-d48c2a09a8fe"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "TopN",
        "lineageTag": "19a09ccd-af16-4e83-ab66-be876b410872",
        "columns": [
          {
            "name": "N",
            "dataType": "int64",
            "sourceColumn": "N",
            "formatString": "0",
            "lineageTag": "9711ecdc-ab6d-4f1a-aa4f-4b23733878c5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "TopN-84b37491-f0ea-4f97-bc6c-7d0e39db62f0",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i45WMlWK1YlWMjSAUBCeEYRnBOEZA3mxAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type text) meta [Serialized.Text = true]) in type table [N = _t]),",
                "    更改的类型 = Table.TransformColumnTypes(源,{{\"N\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "选择的N值",
            "expression": "SELECTEDVALUE('TopN'[N])",
            "formatString": "0",
            "lineageTag": "107c31d0-5c00-4cb6-baf5-491a5080e9a3"
          },
          {
            "name": "离职岗位排名",
            "expression": "RANKX(ALLSELECTED('员工离职表'[离职时岗位]),[【离职计数】],,DESC)",
            "formatString": "0",
            "lineageTag": "8c67ecf7-9834-4b88-9e8d-459bb98d7791"
          },
          {
            "name": "离职岗位在N值内",
            "expression": "SWITCH(TRUE(),ISBLANK([选择的N值]),1,[离职岗位排名]<=[选择的N值],1,0)",
            "formatString": "0",
            "lineageTag": "6215aa0e-0057-4ea7-9983-1a36d133ab3f"
          },
          {
            "name": "离职年龄段排名",
            "expression": "RANKX(ALLSELECTED('离职年龄段'[段名称]),[【离职计数】],,DESC)",
            "formatString": "0",
            "lineageTag": "9b1ef2d4-6664-4d9c-9b5b-0ce9c0922d41"
          },
          {
            "name": "离职年龄段在N值内",
            "expression": "SWITCH(TRUE(),ISBLANK([选择的N值]),1,[离职年龄段排名]<=[选择的N值],1,0)",
            "formatString": "0",
            "lineageTag": "01439211-c2f1-4545-a58e-7dc85b485a9f"
          },
          {
            "name": "离职职务排名",
            "expression": "RANKX(ALLSELECTED('员工离职表'[离职时职务]),[【离职计数】],,DESC)",
            "formatString": "0",
            "lineageTag": "e3347317-7da1-4cc1-9895-ec8752adf5b9"
          },
          {
            "name": "离职职务在N值内",
            "expression": "SWITCH(TRUE(),ISBLANK([选择的N值]),1,[离职职务排名]<=[选择的N值],1,0)",
            "formatString": "0",
            "lineageTag": "5cdc11fd-8486-4a54-983a-929d7df25380"
          }
        ],
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "91598e5e-6e72-44e1-8466-838080854bd9",
        "fromTable": "员工离职表",
        "fromColumn": "离职年龄",
        "toTable": "离职年龄段",
        "toColumn": "数值"
      },
      {
        "name": "c9077e80-8d5f-473c-a7ae-84e6663d20a9",
        "fromTable": "员工离职表",
        "fromColumn": "离职时间",
        "toTable": "日历",
        "toColumn": "日期"
      },
      {
        "name": "572f3bf8-8d1a-4b9a-a934-bda5e26d9e22",
        "fromTable": "员工离职表",
        "fromColumn": "员工编码",
        "toTable": "员工单位类别",
        "toColumn": "编码"
      },
      {
        "name": "4cf0bea0-527c-4fd7-82f5-ca87e5b847c4",
        "fromTable": "员工离职表",
        "fromColumn": "员工编码",
        "toTable": "员工生日表",
        "toColumn": "编码"
      },
      {
        "name": "847fa9bb-14c1-401a-9ed0-21703fb5400f",
        "fromTable": "员工信息表",
        "fromColumn": "本单位入职日期",
        "toTable": "日历",
        "toColumn": "日期"
      },
      {
        "name": "6bd2cdb5-41d3-4d93-8d30-27dd4cb23efa",
        "fromTable": "员工信息表",
        "fromColumn": "部门编码",
        "toTable": "项目信息",
        "toColumn": "项目编码"
      },
      {
        "name": "9cc97fe7-7d50-4852-8830-2d52824d40aa",
        "fromTable": "员工信息表",
        "fromColumn": "部门编码",
        "toTable": "单位",
        "toColumn": "单位编码",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d42893c1-fce2-427e-8910-81227d935301",
        "fromTable": "员工信息表",
        "fromColumn": "岗位编码",
        "toTable": "岗位",
        "toColumn": "FGUID"
      },
      {
        "name": "b6335bff-310c-4ffb-995e-ccadf04a89b5",
        "fromTable": "员工信息表",
        "fromColumn": "年龄",
        "toTable": "年龄段",
        "toColumn": "数值"
      },
      {
        "name": "89849323-252f-41e0-b297-4eefa349eb80",
        "fromTable": "员工信息表",
        "fromColumn": "司龄",
        "toTable": "司龄段",
        "toColumn": "数值"
      },
      {
        "name": "b1891527-669e-4dbe-9bdb-31a2fdaa0e74",
        "fromTable": "员工信息表",
        "fromColumn": "司龄",
        "toTable": "业务口人员司龄段",
        "toColumn": "数值"
      },
      {
        "name": "2a58171b-71eb-480b-b26f-ab3d558c7df8",
        "fromTable": "员工信息表",
        "fromColumn": "职务编码",
        "toTable": "职务",
        "toColumn": "FGUID"
      },
      {
        "name": "aab53a39-d1de-451e-9bd5-c76b2dedd240",
        "fromTable": "执证情况",
        "fromColumn": "员工编码",
        "toTable": "员工信息表",
        "toColumn": "编码",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "expressions": [
      {
        "name": "设置区间值",
        "kind": "m",
        "expression": [
          "let",
          "    源 = 5 meta [IsParameterQuery=true, Type=\"Number\", IsParameterQueryRequired=true]",
          "in",
          "    源"
        ]
      },
      {
        "name": "CreateS",
        "kind": "m",
        "expression": [
          "let",
          "    源 = (d as number) => let",
          "        源 = List.Numbers(1,150),",
          "        转换为表 = Table.FromList(源, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
          "        重命名的列 = Table.RenameColumns(转换为表,{{\"Column1\", \"数值\"}}),",
          "        已添加自定义 = Table.AddColumn(重命名的列, \"段数\", each Number.IntegerDivide([数值]-1,d)),",
          "        已添加自定义1 = Table.AddColumn(已添加自定义, \"下限\", each [段数]*d+1),",
          "        已添加自定义2 = Table.AddColumn(已添加自定义1, \"上限\", each ([段数]+1)*d),",
          "        已添加自定义3 = Table.AddColumn(已添加自定义2, \"段名称\", each Text.From([下限]) &\"-\"&Text.From([上限]))",
          "    in",
          "        已添加自定义3",
          "in",
          "    源"
        ]
      },
      {
        "name": "cscecdb",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.87/cscecdb\", [HierarchicalNavigation=true])",
          "in",
          "    源"
        ]
      },
      {
        "name": "单位",
        "kind": "m",
        "expression": [
          "let",
          "    源 = cscecdb,",
          "    FZHR = 源{[Schema=\"FZHR\"]}[Data],",
          "    HR_DEPT = FZHR{[Name=\"HR_DEPT\"]}[Data],",
          "    删除的其他列 = Table.SelectColumns(HR_DEPT,{\"FCODE\", \"FNAME\", \"FPROJECTREGIONAL\"}),",
          "    重命名的列 = Table.RenameColumns(删除的其他列,{{\"FCODE\", \"单位编码\"}, {\"FNAME\", \"单位名称\"}, {\"FPROJECTREGIONAL\", \"京内外\"}})",
          "in",
          "    重命名的列"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  },
  "id": "SemanticModel"
}