table D_科目
	lineageTag: 3bc691a8-cab5-48bc-9200-cf62f3d61388

	measure 【级次】 = MAX('D_科目'[级次])
		formatString: 0
		lineageTag: 3229b2ce-3eff-4480-a015-458c4f940c90

	measure 【当前级次】 = ISINSCOPE('D_科目'[L1])+ISINSCOPE('D_科目'[L2])+ISINSCOPE('D_科目'[L3])+ISINSCOPE('D_科目'[L4])
		formatString: 0
		lineageTag: a55b0ed5-b213-4341-b557-59f2e0e03d79

	column KM1
		dataType: string
		lineageTag: 2903d90b-1a67-4eab-a51a-d0e1ffe42aa0
		summarizeBy: none
		sourceColumn: KM1

		annotation SummarizationSetBy = Automatic

	column KM2
		dataType: string
		lineageTag: 70eba99b-a7c5-4806-932c-24df7a570fe3
		summarizeBy: none
		sourceColumn: KM2

		annotation SummarizationSetBy = Automatic

	column KM3
		dataType: string
		lineageTag: d9e518c9-9a31-4654-aeb7-6c4595acedce
		summarizeBy: none
		sourceColumn: KM3

		annotation SummarizationSetBy = Automatic

	column KM4
		dataType: string
		lineageTag: c6ebc421-5a18-4b84-97ab-a6076674d14a
		summarizeBy: none
		sourceColumn: KM4

		annotation SummarizationSetBy = Automatic

	column 标准合同名称
		dataType: string
		lineageTag: 5d0d3065-9568-454e-88f6-9412a52adbfb
		summarizeBy: none
		sourceColumn: 标准合同名称

		annotation SummarizationSetBy = Automatic

	hierarchy 科目层次
		lineageTag: cc9a288f-54c3-4187-aa80-a171a61674d6

		level KM1
			lineageTag: 12ad0622-f547-4281-8c64-436c50cd1a07
			column: KM1

		level KM2
			lineageTag: 3e84f377-8a7a-4687-960a-29a66036ca83
			column: KM2

		level KM3
			lineageTag: e9992b9c-a89b-47ec-8c84-ba913afd4be2
			column: KM3

		level KM4
			lineageTag: d6e8e3cb-85c3-45bb-bc56-fc5753e732c9
			column: KM4

	partition D_科目 = m
		mode: import
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("xVrbUhpNEH6XXKe2EkBNrnP1P0Mq7yIq53MgCnISUMGIiBERQeRhwszsXuUV/p7p", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [KM1 = _t, KM2 = _t, KM3 = _t, KM4 = _t, 标准合同 = _t]),
				    替换的值2 = Table.ReplaceValue(源,"","同上",Replacer.ReplaceValue,{"KM3"}),
				    替换的值3 = Table.ReplaceValue(替换的值2,"","同上",Replacer.ReplaceValue,{"KM4"}),
				    替换的值 = Table.ReplaceValue(替换的值3,"《","",Replacer.ReplaceText,{"标准合同"}),
				    替换的值1 = Table.ReplaceValue(替换的值,"》","",Replacer.ReplaceText,{"标准合同"}),
				    已添加自定义 = Table.AddColumn(替换的值1, "标准合同名称", each Text.Split([标准合同],"、")),
				    删除的列 = Table.RemoveColumns(已添加自定义,{"标准合同"}),
				    #"展开的“标准合同名称”" = Table.ExpandListColumn(删除的列, "标准合同名称"),
				    更改的类型 = Table.TransformColumnTypes(#"展开的“标准合同名称”",{{"标准合同名称", type text}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

