table F_合同
	lineageTag: f2eeb47a-34a9-4a22-b41f-5624dbdc8d8b

	column 项目编码
		dataType: string
		lineageTag: b0a7b40e-5890-4b8b-b249-4368b7aba4d7
		summarizeBy: none
		sourceColumn: 项目编码

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: f8a99697-a7f4-40f2-9c5b-5eca9088a7d9
		summarizeBy: none
		sourceColumn: 项目名称

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 标准合同编号
		dataType: string
		lineageTag: f5016531-1382-4881-833f-7fcdf43ec95a
		summarizeBy: none
		sourceColumn: 标准合同编号

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 标准合同名称
		dataType: string
		lineageTag: 1cee17cb-5ab5-4694-a6d9-5861ac942328
		summarizeBy: none
		sourceColumn: 标准合同名称

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'M.下游合同.价税合计.Sum'
		dataType: double
		formatString: "¥"#,0.###############;"¥"-#,0.###############;"¥"#,0.###############
		lineageTag: 0464f150-c133-4286-834a-b304b09c48af
		summarizeBy: sum
		sourceColumn: M.下游合同.价税合计.Sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"zh-CN"}

	column 'M.下游合同.金额.Sum'
		dataType: double
		formatString: "¥"#,0.###############;"¥"-#,0.###############;"¥"#,0.###############
		lineageTag: 8220b2d2-fd28-43ab-bba0-a28abb6139ee
		summarizeBy: sum
		sourceColumn: M.下游合同.金额.Sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"zh-CN"}

	column 'M.下游合同.税金.Sum'
		dataType: double
		formatString: "¥"#,0.###############;"¥"-#,0.###############;"¥"#,0.###############
		lineageTag: 6dd418c5-7d51-4654-b68a-bce3f6ec4bfd
		summarizeBy: sum
		sourceColumn: M.下游合同.税金.Sum

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"zh-CN"}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 8947edbb-98fa-43dd-a973-9a96293a13f3
		summarizeBy: none
		sourceColumn: 日期

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition F_合同 = m
		mode: import
		source =
				let
				    查询1 = AnalysisServices.Database("sql1.chinaonebuild.com", "BAM", [Query="/* START QUERY BUILDER */#(lf)EVALUATE#(lf)SUMMARIZECOLUMNS(#(lf)    'D_项目信息'[项目编码],#(lf)    'D_项目信息'[项目名称],#(lf)    'D_下游合同'[标准合同编号],#(lf)    'D_下游合同'[标准合同名称],#(lf)    'D_日历'[日期],#(lf)    KEEPFILTERS( FILTER( ALL( 'D_下游合同'[合同编号] ), NOT( ISBLANK( 'D_下游合同'[合同编号] )))),#(lf)    ""M.下游合同.价税合计.Sum"", [M.下游合同.价税合计.Sum],#(lf)    ""M.下游合同.金额.Sum"", [M.下游合同.金额.Sum],#(lf)    ""M.下游合同.税金.Sum"", [M.下游合同.税金.Sum])#(lf)", Implementation="2.0"]),
				    重命名列 = Table.TransformColumnNames(查询1,each Text.BetweenDelimiters(_,"[","]")),
				    更改的类型 = Table.TransformColumnTypes(重命名列,{{"M.下游合同.价税合计.Sum", type number}, {"M.下游合同.金额.Sum", type number}, {"M.下游合同.税金.Sum", type number}})
				in
				    更改的类型

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

