table 专项物资付款表
	lineageTag: 3bcfc2f2-94a4-41d3-8f4b-72fee179acce

	column 年
		dataType: double
		lineageTag: 770ef354-4a02-4aee-986b-b1265ea7750f
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: f863c3de-67f0-4aca-8f81-e2214523e5d7
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 合同编号
		dataType: string
		lineageTag: 9268de8f-0df9-43c3-b152-cb8fe8965633
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 本期付款
		dataType: double
		lineageTag: cb56ec88-8df6-4e26-b5d8-64415b5fae4f
		summarizeBy: sum
		sourceColumn: 本期付款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: f3131274-ae8c-4b92-b7f6-f4d0951da2ee
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 单据状态
		dataType: string
		lineageTag: cefe5322-b960-4f74-8e86-816dc037922b
		summarizeBy: none
		sourceColumn: 单据状态

		annotation SummarizationSetBy = Automatic

	partition 专项物资付款表-0d026017-efe1-473d-b4ca-1ebeacfe5813 = m
		mode: import
		queryGroup: 专项物资
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_DANXIANGWUZIFUKUAN = GSPM{[Name="GSPM_DANXIANGWUZIFUKUAN"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_DANXIANGWUZIFUKUAN,{"FNIAN", "FYUE", "FHETONGBIANHAO", "FBENQISHIJIFUKUAN", "FPINGSHENZHUANGTAI2"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FNIAN", "年"}, {"FYUE", "月"}, {"FHETONGBIANHAO", "合同编号"}, {"FBENQISHIJIFUKUAN", "本期付款"}, {"FPINGSHENZHUANGTAI2", "单据状态"}}),
				    已添加自定义 = Table.AddColumn(重命名的列, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":6,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FNIAN,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FYUE,5}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FHETONGBIANHAO,12}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FBENQISHIJIFUKUAN,33}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FPINGSHENZHUANGTAI2,72}","Section1/专项物资付款表/更改的类型.{日期,5}"],"ColumnCount":6,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FNIAN,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FYUE,5}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FHETONGBIANHAO,12}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FBENQISHIJIFUKUAN,33}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_DANXIANGWUZIFUKUAN.{FPINGSHENZHUANGTAI2,72}","Section1/专项物资付款表/更改的类型.{日期,5}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

