table 专项物资进场
	lineageTag: ff387649-02ce-4398-82c4-84c98e514cb8

	column 年
		dataType: double
		lineageTag: da5d7edd-b8a4-42e1-a47d-bbfc7dbababb
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: b1bde113-cb35-44f3-b545-b9a4f8419075
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目名称
		dataType: string
		lineageTag: 96ffe1a5-36cf-46bd-901e-ec5ad49ef832
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 191e61f8-56cd-4989-8aab-fe4a2f02ebb5
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: 1bb8086d-467e-47d4-a913-028d9efcbd14
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 金额
		dataType: double
		lineageTag: edeaa8b7-b3d3-423d-8693-0759c10de642
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: fe6dfc1c-fd04-4655-bca9-45117c945a5e
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: fd39865f-d131-4a8d-8502-ab39addfc1e3
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	partition 专项物资进场-60181ddc-5682-4ce2-9c31-5b527dfe112a = m
		mode: import
		queryGroup: 专项物资
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_WUZIJINCHANG_ZB = GSPM{[Name="GSPM_WUZIJINCHANG_ZB"]}[Data],
				    筛选的行 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB, each ([FYEWUXIAOLEI] = "专项进场") and ([FDANJUZHUANGTAI] = "已完成")),
				    删除的其他列 = Table.SelectColumns(筛选的行,{"FNIAN", "FYUE", "FXIANGMUMINGCHENG", "FHETONGBIANHAO", "FHANSHUIJINCHANGJINE", "FBUHANSHUIJINCHANGJINE", "FSHUIJIN"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FNIAN", "年"}, {"FYUE", "月"}, {"FXIANGMUMINGCHENG", "项目名称"}, {"FHETONGBIANHAO", "合同编号"}, {"FHANSHUIJINCHANGJINE", "价税合计"}, {"FBUHANSHUIJINCHANGJINE", "金额"}, {"FSHUIJIN", "税金"}}),
				    已添加自定义 = Table.AddColumn(重命名的列, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":8,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHETONGBIANHAO,9}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHANSHUIJINCHANGJINE,42}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FBUHANSHUIJINCHANGJINE,43}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FSHUIJIN,44}","Section1/专项物资进场/更改的类型.{日期,7}"],"ColumnCount":8,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHETONGBIANHAO,9}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHANSHUIJINCHANGJINE,42}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FBUHANSHUIJINCHANGJINE,43}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FSHUIJIN,44}","Section1/专项物资进场/更改的类型.{日期,7}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Exception

