table 专项物资退场
	lineageTag: e26b70cb-fe62-44c4-b79c-6c19531e93f8

	column 退场单
		dataType: string
		lineageTag: 7a420c9d-354f-44f1-ab4c-a48f3b07ef87
		summarizeBy: none
		sourceColumn: 退场单

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 3b5119ea-43c2-4cbe-baf9-04b341442213
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		lineageTag: 6a018cd6-3fbf-4a99-87d0-1d96b31088de
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: be5608f9-873f-4151-9acc-166d2893d0df
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 价税合计
		dataType: double
		lineageTag: 52921d6d-2738-48e8-a679-a79fb75eda94
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 年
		dataType: double
		lineageTag: db5ee66c-ab12-4fa2-98a8-760b199da867
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: 3772a6d1-01f8-41ed-966c-16cbad5f8878
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 单据状态
		dataType: string
		lineageTag: 0ba9c35d-c670-4982-870e-f479bc769271
		summarizeBy: none
		sourceColumn: 单据状态

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: defefefb-0455-4177-8bbe-8e7058ba24c3
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	partition 专项物资退场-8c58ea9b-a993-48fb-a32c-ee743354b4f6 = m
		mode: import
		queryGroup: 专项物资
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_WUZITUICHANG_CB = GSPM{[Name="GSPM_WUZITUICHANG_CB"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_CB,{"FTUICHANGDANID", "FHETONGBIANHAO", "FJINE", "FSHUIE", "FJIASHUIHEJI"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FTUICHANGDANID", "退场单"}, {"FHETONGBIANHAO", "合同编号"}, {"FJINE", "金额"}, {"FSHUIE", "税金"}, {"FJIASHUIHEJI", "价税合计"}}),
				    合并的查询 = Table.NestedJoin(重命名的列,{"退场单"},专项物资退场主表,{"FID"},"专项物资退场主表",JoinKind.Inner),
				    #"展开的“专项物资退场主表”" = Table.ExpandTableColumn(合并的查询, "专项物资退场主表", {"年", "月", "单据状态"}, {"年", "月", "单据状态"}),
				    筛选的行 = Table.SelectRows(#"展开的“专项物资退场主表”", each ([单据状态] = "已完成")),
				    已添加自定义 = Table.AddColumn(筛选的行, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":9,"keyColumnNames":[],"queryRelationships":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FID,0}","KeyColumnCount":1}],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FTUICHANGDANID,1}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FHETONGBIANHAO,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJINE,38}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FSHUIE,55}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJIASHUIHEJI,56}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FDANJUZHUANGTAI,11}","Section1/专项物资退场/更改的类型.{日期,8}"],"ColumnCount":9,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FTUICHANGDANID,1}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FHETONGBIANHAO,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJINE,38}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FSHUIE,55}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJIASHUIHEJI,56}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FDANJUZHUANGTAI,11}","Section1/专项物资退场/更改的类型.{日期,8}"],"RelationshipInfo":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FID,0}","KeyColumnCount":1}]}

	annotation PBI_ResultType = Exception

