table 分包减报量
	lineageTag: e6609243-bb50-4117-ad3d-aa34f9387fa9

	column 合同编号
		dataType: string
		lineageTag: caaf2873-4efc-4be7-a47d-c056489343d6
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 分包名称
		dataType: string
		lineageTag: 4e4cbae2-99e7-478e-9693-f94e39c95a0b
		summarizeBy: none
		sourceColumn: 分包名称

		annotation SummarizationSetBy = Automatic

	column 减报量金额
		dataType: double
		lineageTag: a1a84221-e52a-4d15-933a-5a20571959f4
		summarizeBy: sum
		sourceColumn: 减报量金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 减报量税额
		dataType: double
		lineageTag: a83cf627-7b0a-4225-a9e9-d1b311cfb4b9
		summarizeBy: sum
		sourceColumn: 减报量税额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 减报量价税合计
		dataType: double
		lineageTag: 565fcc56-bf07-448b-a147-c6c5a72b4081
		summarizeBy: sum
		sourceColumn: 减报量价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目名称
		dataType: string
		lineageTag: d0853bc1-3fee-4f42-a25e-b73de15533b1
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 年
		dataType: double
		lineageTag: 982b9e04-b370-4a1d-a937-0e2941d5da9d
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: de59d268-cda7-4758-b2d8-29b22ccdbd9c
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 专业
		dataType: string
		lineageTag: 65aea1db-ab1d-49a9-94f6-f61c84444e71
		summarizeBy: none
		sourceColumn: 专业

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: b23100ee-5d31-45ee-b69c-bda8088630b2
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	partition 分包减报量-55acc587-166f-4031-8173-fea573a46319 = m
		mode: import
		source =
				let
				    源 = Table.NestedJoin(分包减报量明细,{"FSHENPIBIAOID"},分包减报量主表,{"FID"},"分包减报量主表",JoinKind.Inner),
				    #"展开的“分包减报量主表”" = Table.ExpandTableColumn(源, "分包减报量主表", {"项目名称", "年", "月", "专业"}, {"项目名称", "年", "月", "专业"}),
				    删除的列 = Table.RemoveColumns(#"展开的“分包减报量主表”",{"FSHENPIBIAOID"}),
				    已添加自定义 = Table.AddColumn(删除的列, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":10,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FHETONGBIANHAO,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FFENBAODANWEI,8}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FBAOLIANGJINE,35}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FBAOLIANGSHUIE,36}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FDQBLJIASHUIHEJI,37}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FXIANGMUMINGCHENG,5}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FNIAN,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FYUE,8}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FSHIGONGZHUANYE,10}","Section1/分包减报量/更改的类型.{日期,9}"],"ColumnCount":10,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FHETONGBIANHAO,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FFENBAODANWEI,8}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FBAOLIANGJINE,35}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FBAOLIANGSHUIE,36}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_SHANGWUJIANBAOLIANG.{FDQBLJIASHUIHEJI,37}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FXIANGMUMINGCHENG,5}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FNIAN,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FYUE,8}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FBJIANBAOLIANGSHENPIBIAO.{FSHIGONGZHUANYE,10}","Section1/分包减报量/更改的类型.{日期,9}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Exception

