table 分包报量表
	lineageTag: 96166585-29b3-48cc-bed7-d53fbfd3a3b9

	column 合同编号
		dataType: string
		lineageTag: 0759066e-a984-49fd-85f8-75aa2db21df3
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 合同名称
		dataType: string
		lineageTag: 4eb283e5-91b4-4680-b2e7-7171c5c8a5ac
		summarizeBy: none
		sourceColumn: 合同名称

		annotation SummarizationSetBy = Automatic

	column 分包名称
		dataType: string
		lineageTag: bac089f4-3cd8-460b-9de1-c7baed4be3cb
		summarizeBy: none
		sourceColumn: 分包名称

		annotation SummarizationSetBy = Automatic

	column 税率
		dataType: double
		lineageTag: baf1ad3c-d5af-4f84-8187-62273aa04cee
		summarizeBy: sum
		sourceColumn: 税率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 报量价税合计
		dataType: double
		lineageTag: ad042a89-208c-4e31-9093-e9df8bfd1c41
		summarizeBy: sum
		sourceColumn: 报量价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目编码
		dataType: string
		lineageTag: 1231de64-e8ed-454a-9ae1-33b325d2a6bf
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 7b8d2dec-280a-4201-aec2-2ec2b97e6da1
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 年
		dataType: double
		lineageTag: 6912a0fc-b363-438d-9826-8d22f151eb9d
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: 57d30310-8ca2-437a-964b-44186955eea4
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 报量金额
		dataType: double
		lineageTag: f65e4263-b836-41a3-a306-920fd3f763cd
		summarizeBy: sum
		sourceColumn: 报量金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 报量税额
		dataType: double
		lineageTag: b840eb64-4059-4e2d-81bd-e3e91bc056fe
		summarizeBy: sum
		sourceColumn: 报量税额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: a8588931-2af6-4ccf-8ea6-83ee99027dac
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 专业
		dataType: string
		lineageTag: b00ecc54-0c74-4b2f-a18c-463a035d681f
		summarizeBy: none
		sourceColumn: 专业

		annotation SummarizationSetBy = Automatic

	partition 分包报量表-36aba928-fb81-4643-9b30-8044cb69fe94 = m
		mode: import
		queryGroup: 分包
		source =
				let
				    源 = #"gspm",
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_SHANGWUBAOLIANG_EQ = GSPM{[Name="GSPM_SHANGWUBAOLIANG_EQ"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_SHANGWUBAOLIANG_EQ,{"FSHENPIBIAOID", "FHETONGBIANHAO", "FHETONGMINGCHENG", "FSHIGONGZHUANYE", "FFENBAODANWEI", "FZENGZHISHUILV", "FBYWCBLHS"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FHETONGBIANHAO", "合同编号"}, {"FHETONGMINGCHENG", "合同名称"}, {"FFENBAODANWEI", "分包名称"}, {"FBYWCBLHS", "报量价税合计"}, {"FZENGZHISHUILV", "税率"}, {"FSHIGONGZHUANYE", "专业"}}),
				    替换的值 = Table.ReplaceValue(重命名的列,null,0,Replacer.ReplaceValue,{"税率"}),
				    合并的查询 = Table.NestedJoin(替换的值, {"FSHENPIBIAOID"}, 分包完成量主表, {"FID"}, "分包完成量主表", JoinKind.Inner),
				    删除的列 = Table.RemoveColumns(合并的查询,{"FSHENPIBIAOID"}),
				    #"展开的“分包完成量主表”" = Table.ExpandTableColumn(删除的列, "分包完成量主表", {"项目编码", "项目名称", "年", "月"}, {"项目编码", "项目名称", "年", "月"}),
				    #"已添加自定义（计算报量金额）" = Table.AddColumn(#"展开的“分包完成量主表”", "报量金额", each [报量价税合计]/(1+[税率]),type number),
				    #"已添加自定义（计算税金）" = Table.AddColumn(#"已添加自定义（计算报量金额）", "报量税额", each [报量价税合计]-[报量金额],type number),
				    #"已添加自定义（计算日期）" = Table.AddColumn(#"已添加自定义（计算税金）", "日期", each #date([年],[月],1),type date),
				    筛选的行 = Table.SelectRows(#"已添加自定义（计算日期）", each [日期] >= #date(2022, 5, 1)),
				    追加的查询 = Table.Combine({筛选的行, #"2022年4月之前分包报量"})
				in
				    追加的查询

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

