table 分包付款主表
	lineageTag: dc5b3eeb-bc66-408f-b633-b7d4e6d591d9

	column 年
		dataType: double
		lineageTag: 858e3421-1ed1-41bb-b99f-82301e0b8ccf
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: 3c84721e-aee8-42ef-8edc-c6e2d033e0b3
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 合同编号
		dataType: string
		lineageTag: 57071f44-7b9c-487c-b104-7620d7b0d08f
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 本期实际付款
		dataType: double
		lineageTag: 50cc53c4-6900-46b1-840c-03889c51903a
		summarizeBy: sum
		sourceColumn: 本期实际付款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 244b8f4a-60fa-4bd3-bbca-4ff2e6a2d56b
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 单据状态
		dataType: string
		lineageTag: ec4fc541-4615-4e17-a252-e0cd7c45706c
		summarizeBy: none
		sourceColumn: 单据状态

		annotation SummarizationSetBy = Automatic

	partition 分包付款主表-ec028647-aacf-4452-bc7a-d761dee7bfb7 = m
		mode: import
		queryGroup: 分包
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_FENBAOGONGCHENGFUKUAN = GSPM{[Name="GSPM_FENBAOGONGCHENGFUKUAN"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_FENBAOGONGCHENGFUKUAN,{"FNIAN", "FYUE", "FHETONGBIANHAO", "FBENQISHIJIFUKUAN", "FPINGSHENZHUANGTAI2"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FHETONGBIANHAO", "合同编号"}, {"FBENQISHIJIFUKUAN", "本期实际付款"}, {"FNIAN", "年"}, {"FYUE", "月"}, {"FPINGSHENZHUANGTAI2", "单据状态"}}),
				    已添加自定义 = Table.AddColumn(重命名的列, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":6,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FHETONGBIANHAO,10}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FBENQISHIJIFUKUAN,23}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FPINGSHENZHUANGTAI2,83}","Section1/分包付款主表/更改的类型.{日期,5}"],"ColumnCount":6,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FHETONGBIANHAO,10}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FBENQISHIJIFUKUAN,23}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_FENBAOGONGCHENGFUKUAN.{FPINGSHENZHUANGTAI2,83}","Section1/分包付款主表/更改的类型.{日期,5}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = 导航

