table 分公司总经
	lineageTag: 9757ffca-ae43-424b-91fb-e65668e525af

	column 帐号
		dataType: string
		lineageTag: 8eaa1256-70f7-4a16-b23c-4ea0eb0eb741
		summarizeBy: none
		sourceColumn: 帐号

		annotation SummarizationSetBy = Automatic

	column 姓名
		dataType: string
		lineageTag: c8b7c56d-634e-4e7a-bf1c-e34c3f6e7f0a
		summarizeBy: none
		sourceColumn: 姓名

		annotation SummarizationSetBy = Automatic

	column 责任体
		dataType: string
		lineageTag: eefe927e-d08f-4624-b6bb-77eaf7c27b55
		summarizeBy: none
		sourceColumn: 责任体

		annotation SummarizationSetBy = Automatic

	partition 分公司总经-9da0a09f-64c0-4666-9fd3-61f386b7a0af = m
		mode: import
		queryGroup: 账户-项目对照表
		source =
				let
				    源 = Excel.Workbook(File.Contents("\\172.16.8.66\经营分析\经营分析会\分公司总经.xlsx"), null, true),
				    分公司总经_Table = 源{[Item="分公司总经",Kind="Table"]}[Data],
				    更改的类型 = Table.TransformColumnTypes(分公司总经_Table,{{"帐号", type text}, {"姓名", type text}, {"责任体", type text}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

