table 租赁物资付款表
	lineageTag: e588c638-e1e0-4ba4-9cfa-ada103377b8a

	column 年
		dataType: double
		lineageTag: 8e57ffa1-c975-41a0-b666-2b5c09129e07
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: 28c5effe-e438-4152-b424-a4339ea6e634
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 合同编号
		dataType: string
		lineageTag: 0eb5436f-5d53-4c9c-9377-8bc871a10a47
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		lineageTag: e5393d45-0668-43f7-a0e3-69c9d3d609bc
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 098cee50-788e-467a-beac-038cb34588ea
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 单据状态
		dataType: string
		lineageTag: f304cd61-e821-42bd-b5a2-1d66a020c4b7
		summarizeBy: none
		sourceColumn: 单据状态

		annotation SummarizationSetBy = Automatic

	partition 租赁物资付款表-56191950-24ce-492f-b54f-49886a94d856 = m
		mode: import
		queryGroup: 租赁物资
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_ZZCAILIAOZULINAFK = GSPM{[Name="GSPM_ZZCAILIAOZULINAFK"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_ZZCAILIAOZULINAFK,{"FNIAN", "FYUE", "FHETONGBIANHAO", "FBENQISHIJIFUKUAN", "FPINGSHENZHUANGTAI2"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FNIAN", "年"}, {"FYUE", "月"}, {"FHETONGBIANHAO", "合同编号"}, {"FBENQISHIJIFUKUAN", "金额"}, {"FPINGSHENZHUANGTAI2", "单据状态"}}),
				    已添加自定义 = Table.AddColumn(重命名的列, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":6,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FNIAN,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FYUE,5}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FHETONGBIANHAO,12}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FBENQISHIJIFUKUAN,27}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FPINGSHENZHUANGTAI2,81}","Section1/租赁物资付款表/更改的类型.{日期,5}"],"ColumnCount":6,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FNIAN,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FYUE,5}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FHETONGBIANHAO,12}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FBENQISHIJIFUKUAN,27}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZULINAFK.{FPINGSHENZHUANGTAI2,81}","Section1/租赁物资付款表/更改的类型.{日期,5}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

