table 租赁物资报量表
	lineageTag: 7398fa0c-4e7a-4ecd-b388-a0d158bfcebc

	column FID
		dataType: string
		lineageTag: 9fa560cc-3e00-4a78-bd4f-9afa92e64be6
		summarizeBy: none
		sourceColumn: FID

		annotation SummarizationSetBy = Automatic

	column 年
		dataType: double
		lineageTag: 81ee445c-8e26-4f33-ba7d-738688c92e93
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: 9584cc0c-cbad-4e6e-9ce8-37580301db9a
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目名称
		dataType: string
		lineageTag: eeac5734-4f59-468b-bf39-5b96a0a03a8a
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 单据状态
		dataType: string
		lineageTag: 8693bae8-e8c8-49a8-afca-aeca257505bc
		summarizeBy: none
		sourceColumn: 单据状态

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 952724d5-aa0f-4076-b6b4-6b80124ac7eb
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 报量金额
		dataType: double
		lineageTag: c824997f-f7eb-44a0-8a75-3e2d6f90031c
		summarizeBy: sum
		sourceColumn: 报量金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 供方名称
		dataType: string
		lineageTag: d9ea9f2d-862d-42dd-b871-35b9ce9debe5
		summarizeBy: none
		sourceColumn: 供方名称

		annotation SummarizationSetBy = Automatic

	column 报量税额
		dataType: double
		lineageTag: e2bcaa15-850a-4490-85f7-4a137f86b460
		summarizeBy: sum
		sourceColumn: 报量税额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 报量价税合计
		dataType: double
		lineageTag: 940c06cd-cca5-4ac2-b3d3-10abe87d7458
		summarizeBy: sum
		sourceColumn: 报量价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 4bc9fb2a-e5b6-433e-b159-965859fd5c47
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		lineageTag: 32c20e15-b0df-41f5-ab19-8ff55084b0f8
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	partition 租赁物资报量表-2cfc4b57-02df-476a-88bf-68e81feaa25f = m
		mode: import
		queryGroup: 租赁物资
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_ZZCAILIAOZLDQBL_ZB = GSPM{[Name="GSPM_ZZCAILIAOZLDQBL_ZB"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_ZZCAILIAOZLDQBL_ZB,{"FID", "FNIAN", "FYUE", "FXIANGMUBIANMA", "FXIANGMUMINGCHENG", "FDANJUZHUANGTAI"}),
				    筛选的行 = Table.SelectRows(删除的其他列, each ([FDANJUZHUANGTAI] = "已完成")),
				    重命名的列 = Table.RenameColumns(筛选的行,{{"FNIAN", "年"}, {"FYUE", "月"}, {"FXIANGMUMINGCHENG", "项目名称"}, {"FDANJUZHUANGTAI", "单据状态"}, {"FXIANGMUBIANMA", "项目编码"}}),
				    合并的查询 = Table.NestedJoin(重命名的列,{"FID"},租赁物资报量从表,{"FBAOLIANGID"},"租赁物资报量从表",JoinKind.LeftOuter),
				    #"展开的“租赁物资报量从表”" = Table.ExpandTableColumn(合并的查询, "租赁物资报量从表", {"合同编号", "报量金额", "供方名称", "报量税额", "报量价税合计"}, {"合同编号", "报量金额", "供方名称", "报量税额", "报量价税合计"}),
				    已添加自定义 = Table.AddColumn(#"展开的“租赁物资报量从表”", "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":12,"keyColumnNames":[],"queryRelationships":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGID,1}","KeyColumnCount":1}],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FID,0}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FXIANGMUBIANMA,6}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FDANJUZHUANGTAI,11}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FHETONGBIANHAO,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGJINE,11}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FGONGFANGMINGCHENG,14}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGSHUIE,40}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGJIASHUIHEJI,41}","Section1/租赁物资报量表/更改的类型.{日期,11}"],"ColumnCount":12,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FID,0}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FXIANGMUBIANMA,6}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZCAILIAOZLDQBL_ZB.{FDANJUZHUANGTAI,11}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FHETONGBIANHAO,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGJINE,11}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FGONGFANGMINGCHENG,14}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGSHUIE,40}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGJIASHUIHEJI,41}","Section1/租赁物资报量表/更改的类型.{日期,11}"],"RelationshipInfo":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_ZZZULINDQBLHT_CB.{FBAOLIANGID,1}","KeyColumnCount":1}]}

	annotation PBI_ResultType = Exception

