table 统一转账进场
	lineageTag: 6475974a-eaf9-451a-af86-d304e34464b8

	column 年
		dataType: double
		lineageTag: 770ff849-887c-46b8-aed8-5babcfb88756
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 月
		dataType: double
		lineageTag: 06a032da-bb9c-47af-bfb8-38acf5aad497
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目编码
		dataType: string
		lineageTag: 60cc3b49-7844-45d5-a95a-b407442bb89d
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: bc9be970-25dc-4d57-a5f0-fdba846abd74
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: fc4a9dd0-aa31-4856-9428-85c05f31fed7
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: 9367d0a8-16ba-4321-9263-f2a0fdcccf9d
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 金额
		dataType: double
		lineageTag: 9028b738-781a-4cf0-b67d-d3ae2a25940b
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: 67a90193-d171-4d64-b399-e4e53782b6aa
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: b2c44431-2960-4883-9af9-550b8bf2b34b
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 付款状态
		dataType: string
		lineageTag: eb5b8987-7e08-4a90-9482-cfdd7c38451f
		summarizeBy: none
		sourceColumn: 付款状态

		annotation SummarizationSetBy = Automatic

	partition 统一转账进场-b54ada9a-b426-4508-a8a8-a34d020a8811 = m
		mode: import
		queryGroup: 统一转账
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_WUZIJINCHANG_ZB = GSPM{[Name="GSPM_WUZIJINCHANG_ZB"]}[Data],
				    筛选的行1 = Table.SelectRows(GSPM_WUZIJINCHANG_ZB, each ([FWUZIJINCHANGLEIBIE] = "统一转账物资") and ([FDANJUZHUANGTAI] = "已完成")),
				    删除的其他列 = Table.SelectColumns(筛选的行1,{"FNIAN", "FYUE", "FXIANGMUBIANMA", "FXIANGMUMINGCHENG", "FHETONGBIANHAO", "FHANSHUIJINCHANGJINE", "FBUHANSHUIJINCHANGJINE", "FSHUIJIN", "FFUKUANZHUANGTAI"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FNIAN", "年"}, {"FYUE", "月"}, {"FXIANGMUMINGCHENG", "项目名称"}, {"FHETONGBIANHAO", "合同编号"}, {"FHANSHUIJINCHANGJINE", "价税合计"}, {"FBUHANSHUIJINCHANGJINE", "金额"}, {"FSHUIJIN", "税金"}, {"FXIANGMUBIANMA", "项目编码"}, {"FFUKUANZHUANGTAI", "付款状态"}}),
				    已添加自定义 = Table.AddColumn(重命名的列, "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":10,"keyColumnNames":[],"queryRelationships":[],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FXIANGMUBIANMA,6}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHETONGBIANHAO,9}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHANSHUIJINCHANGJINE,42}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FBUHANSHUIJINCHANGJINE,43}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FSHUIJIN,44}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FFUKUANZHUANGTAI,70}","Section1/统一转账进场/更改的类型.{日期,9}"],"ColumnCount":10,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FYUE,4}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FXIANGMUBIANMA,6}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHETONGBIANHAO,9}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FHANSHUIJINCHANGJINE,42}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FBUHANSHUIJINCHANGJINE,43}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FSHUIJIN,44}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZIJINCHANG_ZB.{FFUKUANZHUANGTAI,70}","Section1/统一转账进场/更改的类型.{日期,9}"],"RelationshipInfo":[]}

	annotation PBI_ResultType = Table

