table 统一转账退场
	lineageTag: f8cab966-4aa5-421b-b4c4-365689391798

	column 退场单
		dataType: string
		lineageTag: 7f8ec029-860b-459d-9845-840479044d8a
		summarizeBy: none
		sourceColumn: 退场单

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: c6407d43-9bf8-4583-9369-3f569efbf1b0
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		lineageTag: 86ec8a08-dbfa-47aa-8c9d-c552813c1331
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: c9ebcbad-9049-4153-b9a7-f2433907e971
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 价税合计
		dataType: double
		lineageTag: cabefbc2-7410-4492-b8b2-bb0a83d74232
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 年
		dataType: double
		lineageTag: ccbb2b53-8d51-4cc5-9657-a5c1a65644bc
		summarizeBy: sum
		sourceColumn: 年

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目编码
		dataType: string
		lineageTag: e4cb2d74-b032-434c-8276-34572229b828
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: cf2d8721-86fd-46c7-9ed7-8d32333d08dd
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 月
		dataType: double
		lineageTag: 653bd425-0066-4e1f-a2d1-c7869e75bc93
		summarizeBy: sum
		sourceColumn: 月

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: c6e43ee7-ea6e-4c69-be75-414898e84c1f
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	partition 统一转账退场-276f1eb5-4bb8-481e-806e-14fd657e14a8 = m
		mode: import
		queryGroup: 统一转账
		source =
				let
				    源 = gspm,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_WUZITUICHANG_CB = GSPM{[Name="GSPM_WUZITUICHANG_CB"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_WUZITUICHANG_CB,{"FTUICHANGDANID", "FHETONGBIANHAO", "FJINE", "FSHUIE", "FJIASHUIHEJI"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FTUICHANGDANID", "退场单"}, {"FHETONGBIANHAO", "合同编号"}, {"FJINE", "金额"}, {"FSHUIE", "税金"}, {"FJIASHUIHEJI", "价税合计"}}),
				    合并的查询 = Table.NestedJoin(重命名的列, {"退场单"}, 统一转账物资退场主表, {"FID"}, "专项物资退场主表", JoinKind.Inner),
				    #"展开的“专项物资退场主表”" = Table.ExpandTableColumn(合并的查询, "专项物资退场主表", {"年", "项目编码", "项目名称", "月"}, {"年", "项目编码", "项目名称", "月"}),
				    已添加自定义 = Table.AddColumn(#"展开的“专项物资退场主表”", "日期", each #date([年],[月],1)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"日期", type datetime}})
				in
				    更改的类型

	annotation PBI_QueryRelationships = {"columnCount":10,"keyColumnNames":[],"queryRelationships":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FID,0}","KeyColumnCount":1}],"columnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FTUICHANGDANID,1}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FHETONGBIANHAO,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJINE,38}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FSHUIE,55}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJIASHUIHEJI,56}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FXIANGMUBIANMA,6}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FYUE,4}","Section1/统一转账退场/更改的类型.{日期,9}"],"ColumnCount":10,"KeyColumnNames":[],"ColumnIdentities":["Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FTUICHANGDANID,1}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FHETONGBIANHAO,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJINE,38}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FSHUIE,55}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_CB.{FJIASHUIHEJI,56}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FNIAN,3}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FXIANGMUBIANMA,6}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FXIANGMUMINGCHENG,7}","Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FYUE,4}","Section1/统一转账退场/更改的类型.{日期,9}"],"RelationshipInfo":[{"keyColumnCount":1,"keyColumn":0,"otherKeyColumnIdentity":"Server.Database\\/2/Oracle/172.16.8.78\\/oracledb/GSPM/GSPM.GSPM_WUZITUICHANG_ZB.{FID,0}","KeyColumnCount":1}]}

	annotation PBI_ResultType = Exception

