table 维度-责任体
	excludeFromModelRefresh
	lineageTag: 1ed36a23-f009-4a25-9213-f291d02fb33b

	column 责任体
		dataType: string
		lineageTag: ce65f71f-75c6-4c47-a7d6-89334b3959ec
		summarizeBy: none
		sourceColumn: 责任体

		annotation SummarizationSetBy = Automatic

	column 排序
		dataType: int64
		formatString: 0
		lineageTag: 47b07e6c-83be-4572-b9fa-920f48b5db9a
		summarizeBy: sum
		sourceColumn: 排序

		annotation SummarizationSetBy = Automatic

	partition 维度-责任体-7404d404-b0c3-49ca-a74e-cd1150a321fb = m
		mode: import
		queryGroup: 账户-项目对照表
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wetq65mn/juezt7yYsFRJR8lQKVYnWunJjjlPe6Y/7WiDyALFjcDiT3v70MSNYeIgLUjiJnD1vSjqTcHiL5buRxM3A4s/X7PmyY6GJ7u6n+yY9bJ5BVDcHC6+qwdZ3AKhvhNZ3BIm/nT2bGRxQwOwxLOt258umQbiAz0aCwA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [责任体 = _t, 排序 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"责任体", type text}, {"排序", Int64.Type}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

