table 项目信息
	lineageTag: d5e9b684-2fd8-4eb6-abdc-7d9f2a5bff8d

	column 项目编码
		dataType: string
		lineageTag: c5ac65af-37f3-4d3b-b0fd-5ce8e0ea04ea
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 63cf4dd0-1947-4a26-8ef7-32f0f274721c
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 责任体区域
		dataType: string
		lineageTag: ad5b8231-56bd-4821-a9d8-ffc7dd6fe475
		summarizeBy: none
		sourceColumn: 责任体区域

		annotation SummarizationSetBy = Automatic

	column 直管机构编码
		dataType: string
		lineageTag: 9cbfb21d-7bc7-4aae-91a6-5ea67b28d256
		summarizeBy: none
		sourceColumn: 直管机构编码

		annotation SummarizationSetBy = Automatic

	partition 项目信息-fa2f8d8d-3136-4311-9968-ab52995e80a6 = m
		mode: import
		queryGroup: 账户-项目对照表
		source =
				let
				    源 = Oracle.Database("172.16.8.78/oracledb", [HierarchicalNavigation=true]),
				    MD = 源{[Schema="MD"]}[Data],
				    MD_XIANGMUXINXI1 = MD{[Name="MD_XIANGMUXINXI"]}[Data],
				    重命名的列 = Table.RenameColumns(MD_XIANGMUXINXI1,{{"FXMBIANMA", "项目编码"}, {"FXMQUANCHENG", "项目名称"}, {"FXMZONGJIAN", "项目总监"}, {"FZHUANYEFL", "专业分类"}, {"FXMXINGZHI", "项目性质"}, {"FJNWFB", "京内外"}, {"FQUYU", "行政区域"}, {"FSHENG", "省"}, {"FCHENGSHI", "城市"}, {"FXIAN", "区县"}, {"FXMSSZT", "项目实施状态"}, {"FGCLBYJ", "工程类别一级"}, {"FGCLBEJ", "工程类别二级"}, {"FXMJSZT", "项目结算状态"}, {"FXMSZDKH", "项目所属大客户"}, {"FSFTZJZXM", "是否投资建造项目"}, {"FPINGSHENZHUANGTAIID", "FPINGSHENZHUANGTAIID"}, {"FZHIGUANJGXG", "直管机构"}, {"FXIANGMULEIXING", "项目类型"}, {"FZONGJIANTUANDUI", "所属总监团队"}, {"FXMCAIWUZHUANGTAI", "项目财务状态"}, {"FYWBK", "业务板块"}, {"FTUJIANHEDINGSYL", "土建核定收益率"}, {"FJIDIANHEDINGSYL", "机电核定收益率"}, {"FZONGHEHEDINGSYL", "综合核定收益率"}, {"FTUJIANHEDINGSYLJZ", "土建甲指核定收益率"}, {"FJIDIANHEDINGSYLJZ", "机电甲指核定收益率"}, {"FCHANGFANGSHIYEBU", "厂房事业部"}}),
				    删除的其他列 = Table.SelectColumns(重命名的列,{"项目编码", "项目名称", "项目总监", "专业分类", "项目性质", "京内外", "行政区域", "省", "城市", "区县", "项目实施状态", "工程类别一级", "工程类别二级", "项目结算状态", "项目所属大客户", "是否投资建造项目", "土建核定收益率", "机电核定收益率", "综合核定收益率", "项目类型", "直管机构", "FZHIGUANJGXGBM", "土建甲指核定收益率", "机电甲指核定收益率", "厂房事业部", "所属总监团队", "项目财务状态", "业务板块"}),
				    Buffer一下预防出错 = Table.Buffer(删除的其他列),
				    已添加条件列 = Table.AddColumn(Buffer一下预防出错, "责任体区域", each if [京内外] = "国际" then "海外" else if [厂房事业部] <> null then [厂房事业部] else if [直管机构] <> "公司" then [直管机构] else "公司直营",type text),
				    删除的其他列1 = Table.SelectColumns(已添加条件列,{"项目编码", "项目名称", "FZHIGUANJGXGBM", "责任体区域"}),
				    重命名的列1 = Table.RenameColumns(删除的其他列1,{{"FZHIGUANJGXGBM", "直管机构编码"}})
				in
				    重命名的列1

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

