{
  "name": "SemanticModel",
  "compatibilityLevel": 1600,
  "model": {
    "name": "模型",
    "culture": "zh-CN",
    "dataSources": [
      {
        "type": "structured",
        "name": "Oracle/172 16 8 127/racdb com",
        "connectionDetails": {
          "protocol": "oracle",
          "address": {
            "server": "172.16.8.127/racdb.com"
          },
          "authentication": null,
          "query": null
        },
        "options": {
          "hierarchicalNavigation": true
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "picc"
        }
      }
    ],
    "tables": [
      {
        "name": "待办事务",
        "columns": [
          {
            "name": "TODO_ID",
            "dataType": "string",
            "sourceColumn": "TODO_ID"
          },
          {
            "name": "系统",
            "dataType": "string",
            "sourceColumn": "系统"
          },
          {
            "name": "任务名称",
            "dataType": "string",
            "sourceColumn": "任务名称"
          },
          {
            "name": "任务标题",
            "dataType": "string",
            "sourceColumn": "任务标题"
          },
          {
            "name": "开始时间",
            "dataType": "dateTime",
            "sourceColumn": "开始时间"
          },
          {
            "name": "完成时间",
            "dataType": "dateTime",
            "sourceColumn": "完成时间"
          },
          {
            "name": "用户名",
            "dataType": "string",
            "sourceColumn": "用户名"
          },
          {
            "name": "单位名称",
            "dataType": "string",
            "sourceColumn": "单位名称"
          },
          {
            "name": "应用系统编码",
            "dataType": "string",
            "sourceColumn": "应用系统编码"
          },
          {
            "name": "创建时间",
            "dataType": "dateTime",
            "sourceColumn": "创建时间"
          },
          {
            "name": "处理时长",
            "dataType": "double",
            "sourceColumn": "处理时长"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          },
          {
            "name": "职务",
            "dataType": "string",
            "sourceColumn": "职务"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_TODO_V = PICC{[Name=\"CC_COUNT_TODO_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                "    重命名的列1 = Table.RenameColumns(筛选的行,{{\"TODO_COAST_MILLSTIME\", \"处理时长\"}}),",
                "    重命名的列 = Table.RenameColumns(重命名的列1,{{\"TODO_CODE\", \"系统\"}, {\"TODO_ALIAS\", \"任务名称\"}, {\"TODO_TITLE\", \"任务标题\"}, {\"DONE_USER_NAME\", \"用户名\"}, {\"DONE_DEPT_NAME\", \"单位名称\"}, {\"APP_CODE\", \"应用系统编码\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"TODO_SEND_TIME\", \"开始时间\"}, {\"TODO_DONE_TIME\", \"完成时间\"}, {\"S_ATIME\", \"创建时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"开始时间\", type datetime}, {\"完成时间\", type datetime}, {\"创建时间\", type datetime}, {\"处理时长\", type number}}),",
                "    被除的列 = Table.TransformColumns(更改的类型, {{\"处理时长\", each _ / 3600000, type number}}),",
                "    重排序的列 = Table.ReorderColumns(被除的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                "    提取的日期 = Table.TransformColumns(重排序的列,{{\"创建时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_TODO_V = PICC{[Name=\"CC_COUNT_TODO_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                  "    重命名的列1 = Table.RenameColumns(筛选的行,{{\"TODO_COAST_MILLSTIME\", \"处理时长\"}}),",
                  "    重命名的列 = Table.RenameColumns(重命名的列1,{{\"TODO_CODE\", \"系统\"}, {\"TODO_ALIAS\", \"任务名称\"}, {\"TODO_TITLE\", \"任务标题\"}, {\"DONE_USER_NAME\", \"用户名\"}, {\"DONE_DEPT_NAME\", \"单位名称\"}, {\"APP_CODE\", \"应用系统编码\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"TODO_SEND_TIME\", \"开始时间\"}, {\"TODO_DONE_TIME\", \"完成时间\"}, {\"S_ATIME\", \"创建时间\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"开始时间\", type datetime}, {\"完成时间\", type datetime}, {\"创建时间\", type datetime}, {\"处理时长\", type number}}),",
                  "    被除的列 = Table.TransformColumns(更改的类型, {{\"处理时长\", each _ / 3600000, type number}}),",
                  "    重排序的列 = Table.ReorderColumns(被除的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"})",
                  "in",
                  "    重排序的列</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_TODO_V = PICC{[Name=\"CC_COUNT_TODO_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                "    重命名的列1 = Table.RenameColumns(筛选的行,{{\"TODO_COAST_MILLSTIME\", \"处理时长\"}}),",
                "    重命名的列 = Table.RenameColumns(重命名的列1,{{\"TODO_CODE\", \"系统\"}, {\"TODO_ALIAS\", \"任务名称\"}, {\"TODO_TITLE\", \"任务标题\"}, {\"DONE_USER_NAME\", \"用户名\"}, {\"DONE_DEPT_NAME\", \"单位名称\"}, {\"APP_CODE\", \"应用系统编码\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"TODO_SEND_TIME\", \"开始时间\"}, {\"TODO_DONE_TIME\", \"完成时间\"}, {\"S_ATIME\", \"创建时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"开始时间\", type datetime}, {\"完成时间\", type datetime}, {\"创建时间\", type datetime}, {\"处理时长\", type number}}),",
                "    被除的列 = Table.TransformColumns(更改的类型, {{\"处理时长\", each _ / 3600000, type number}}),",
                "    重排序的列 = Table.ReorderColumns(被除的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                "    提取的日期 = Table.TransformColumns(重排序的列,{{\"创建时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_TODO_V = PICC{[Name=\"CC_COUNT_TODO_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                  "    重命名的列1 = Table.RenameColumns(筛选的行,{{\"TODO_COAST_MILLSTIME\", \"处理时长\"}}),",
                  "    重命名的列 = Table.RenameColumns(重命名的列1,{{\"TODO_CODE\", \"系统\"}, {\"TODO_ALIAS\", \"任务名称\"}, {\"TODO_TITLE\", \"任务标题\"}, {\"DONE_USER_NAME\", \"用户名\"}, {\"DONE_DEPT_NAME\", \"单位名称\"}, {\"APP_CODE\", \"应用系统编码\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"TODO_SEND_TIME\", \"开始时间\"}, {\"TODO_DONE_TIME\", \"完成时间\"}, {\"S_ATIME\", \"创建时间\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"开始时间\", type datetime}, {\"完成时间\", type datetime}, {\"创建时间\", type datetime}, {\"处理时长\", type number}}),",
                  "    被除的列 = Table.TransformColumns(更改的类型, {{\"处理时长\", each _ / 3600000, type number}}),",
                  "    重排序的列 = Table.ReorderColumns(被除的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"})",
                  "in",
                  "    重排序的列</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_TODO_V = PICC{[Name=\"CC_COUNT_TODO_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_V, each [S_ATIME] >= \"2024-01-01\" and [S_ATIME] < \"2025-01-01\"),",
                "    重命名的列1 = Table.RenameColumns(筛选的行,{{\"TODO_COAST_MILLSTIME\", \"处理时长\"}}),",
                "    重命名的列 = Table.RenameColumns(重命名的列1,{{\"TODO_CODE\", \"系统\"}, {\"TODO_ALIAS\", \"任务名称\"}, {\"TODO_TITLE\", \"任务标题\"}, {\"DONE_USER_NAME\", \"用户名\"}, {\"DONE_DEPT_NAME\", \"单位名称\"}, {\"APP_CODE\", \"应用系统编码\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"TODO_SEND_TIME\", \"开始时间\"}, {\"TODO_DONE_TIME\", \"完成时间\"}, {\"S_ATIME\", \"创建时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"开始时间\", type datetime}, {\"完成时间\", type datetime}, {\"创建时间\", type datetime}, {\"处理时长\", type number}}),",
                "    被除的列 = Table.TransformColumns(更改的类型, {{\"处理时长\", each _ / 3600000, type number}}),",
                "    重排序的列 = Table.ReorderColumns(被除的列,{\"TODO_ID\", \"系统\", \"任务名称\", \"任务标题\", \"开始时间\", \"完成时间\", \"用户名\", \"单位名称\", \"应用系统编码\", \"创建时间\", \"处理时长\", \"岗位\", \"职务\"}),",
                "    提取的日期 = Table.TransformColumns(重排序的列,{{\"创建时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【任务数】",
            "expression": "DISTINCTCOUNT('待办事务'[TODO_ID])",
            "formatString": "0",
            "lineageTag": "86794c69-f1b6-41bc-bf8a-0c802df49773"
          },
          {
            "name": "【处理时长】",
            "expression": "SUM('待办事务'[处理时长])",
            "formatString": "#,0",
            "lineageTag": "31079d81-9051-49ee-b480-e5c067817b67",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "【平均每任务处理时长】",
            "expression": "DIVIDE([【处理时长】],[【完成任务数】])",
            "formatString": "#,0",
            "lineageTag": "590a5597-78e3-428c-86d6-36370464ad0b",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ]
          },
          {
            "name": "【完成任务数】",
            "expression": [
              "",
              "CALCULATE([【任务数】], '待办事务'[处理时长] >0)"
            ],
            "formatString": "0",
            "lineageTag": "29776461-fbb2-4796-9e06-d2ba666b4cce",
            "extendedProperties": [
              {
                "type": "json",
                "name": "MeasureTemplate",
                "value": {
                  "version": 0,
                  "daxTemplateName": "FilteredMeasure"
                }
              }
            ]
          }
        ]
      },
      {
        "name": "处理业务设备",
        "columns": [
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID"
          },
          {
            "name": "设备",
            "dataType": "string",
            "sourceColumn": "设备"
          },
          {
            "name": "用户名",
            "dataType": "string",
            "sourceColumn": "用户名"
          },
          {
            "name": "系统",
            "dataType": "string",
            "sourceColumn": "系统"
          },
          {
            "name": "任务标题",
            "dataType": "string",
            "sourceColumn": "任务标题"
          },
          {
            "name": "最后处理时间",
            "dataType": "dateTime",
            "sourceColumn": "最后处理时间"
          },
          {
            "name": "点击次数",
            "dataType": "string",
            "sourceColumn": "点击次数"
          },
          {
            "name": "登录IP",
            "dataType": "string",
            "sourceColumn": "登录IP"
          },
          {
            "name": "单位",
            "dataType": "string",
            "sourceColumn": "单位"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          },
          {
            "name": "职务",
            "dataType": "string",
            "sourceColumn": "职务"
          },
          {
            "name": "时刻",
            "dataType": "int64",
            "sourceColumn": "时刻"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_TODO_NUM_V = PICC{[Name=\"CC_COUNT_TODO_NUM_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_NUM_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"设备\"}, {\"USER_NAME\", \"用户名\"}, {\"TODO_CODE\", \"系统\"}, {\"TODO_NAME\", \"任务标题\"}, {\"CLICK_NUM\", \"点击次数\"}, {\"LOGIN_IP\", \"登录IP\"}, {\"DEPT_NAME\", \"单位\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"CLICK_LAST_TIME\", \"最后处理时间\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"最后处理时间\", type datetime}}),",
                "    插入的小时 = Table.AddColumn(更改的类型, \"小时\", each Time.Hour([最后处理时间]), Int64.Type),",
                "    重命名的列1 = Table.RenameColumns(插入的小时,{{\"小时\", \"时刻\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列1,{\"ID\", \"设备\", \"用户名\", \"系统\", \"任务标题\", \"最后处理时间\", \"点击次数\", \"登录IP\", \"单位\", \"岗位\", \"职务\", \"时刻\"}),",
                "    提取的日期 = Table.TransformColumns(删除的其他列,{{\"最后处理时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_TODO_NUM_V = PICC{[Name=\"CC_COUNT_TODO_NUM_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_NUM_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"设备\"}, {\"USER_NAME\", \"用户名\"}, {\"TODO_CODE\", \"系统\"}, {\"TODO_NAME\", \"任务标题\"}, {\"CLICK_NUM\", \"点击次数\"}, {\"LOGIN_IP\", \"登录IP\"}, {\"DEPT_NAME\", \"单位\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"CLICK_LAST_TIME\", \"最后处理时间\"}}),",
                  "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"最后处理时间\", type datetime}}),",
                  "    插入的小时 = Table.AddColumn(更改的类型, \"小时\", each Time.Hour([最后处理时间]), Int64.Type),",
                  "    重命名的列1 = Table.RenameColumns(插入的小时,{{\"小时\", \"时刻\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列1,{\"ID\", \"设备\", \"用户名\", \"系统\", \"任务标题\", \"最后处理时间\", \"点击次数\", \"登录IP\", \"单位\", \"岗位\", \"职务\", \"时刻\"})",
                  "in",
                  "    删除的其他列</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_TODO_NUM_V = PICC{[Name=\"CC_COUNT_TODO_NUM_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_NUM_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"设备\"}, {\"USER_NAME\", \"用户名\"}, {\"TODO_CODE\", \"系统\"}, {\"TODO_NAME\", \"任务标题\"}, {\"CLICK_NUM\", \"点击次数\"}, {\"LOGIN_IP\", \"登录IP\"}, {\"DEPT_NAME\", \"单位\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"CLICK_LAST_TIME\", \"最后处理时间\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"最后处理时间\", type datetime}}),",
                "    插入的小时 = Table.AddColumn(更改的类型, \"小时\", each Time.Hour([最后处理时间]), Int64.Type),",
                "    重命名的列1 = Table.RenameColumns(插入的小时,{{\"小时\", \"时刻\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列1,{\"ID\", \"设备\", \"用户名\", \"系统\", \"任务标题\", \"最后处理时间\", \"点击次数\", \"登录IP\", \"单位\", \"岗位\", \"职务\", \"时刻\"}),",
                "    提取的日期 = Table.TransformColumns(删除的其他列,{{\"最后处理时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_TODO_NUM_V = PICC{[Name=\"CC_COUNT_TODO_NUM_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_NUM_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"设备\"}, {\"USER_NAME\", \"用户名\"}, {\"TODO_CODE\", \"系统\"}, {\"TODO_NAME\", \"任务标题\"}, {\"CLICK_NUM\", \"点击次数\"}, {\"LOGIN_IP\", \"登录IP\"}, {\"DEPT_NAME\", \"单位\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"CLICK_LAST_TIME\", \"最后处理时间\"}}),",
                  "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"最后处理时间\", type datetime}}),",
                  "    插入的小时 = Table.AddColumn(更改的类型, \"小时\", each Time.Hour([最后处理时间]), Int64.Type),",
                  "    重命名的列1 = Table.RenameColumns(插入的小时,{{\"小时\", \"时刻\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列1,{\"ID\", \"设备\", \"用户名\", \"系统\", \"任务标题\", \"最后处理时间\", \"点击次数\", \"登录IP\", \"单位\", \"岗位\", \"职务\", \"时刻\"})",
                  "in",
                  "    删除的其他列</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_TODO_NUM_V = PICC{[Name=\"CC_COUNT_TODO_NUM_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_TODO_NUM_V, each [S_ATIME] >= \"2024-01-01\" and [S_ATIME] < \"2025-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"设备\"}, {\"USER_NAME\", \"用户名\"}, {\"TODO_CODE\", \"系统\"}, {\"TODO_NAME\", \"任务标题\"}, {\"CLICK_NUM\", \"点击次数\"}, {\"LOGIN_IP\", \"登录IP\"}, {\"DEPT_NAME\", \"单位\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职务\"}, {\"CLICK_LAST_TIME\", \"最后处理时间\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"最后处理时间\", type datetime}}),",
                "    插入的小时 = Table.AddColumn(更改的类型, \"小时\", each Time.Hour([最后处理时间]), Int64.Type),",
                "    重命名的列1 = Table.RenameColumns(插入的小时,{{\"小时\", \"时刻\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列1,{\"ID\", \"设备\", \"用户名\", \"系统\", \"任务标题\", \"最后处理时间\", \"点击次数\", \"登录IP\", \"单位\", \"岗位\", \"职务\", \"时刻\"}),",
                "    提取的日期 = Table.TransformColumns(删除的其他列,{{\"最后处理时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【处理任务数量】",
            "expression": "DISTINCTCOUNT('处理业务设备'[ID])",
            "formatString": "0",
            "lineageTag": "6f590920-53ee-446e-94b7-b236596364bb"
          }
        ]
      },
      {
        "name": "开屏统计",
        "columns": [
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID"
          },
          {
            "name": "用户名称",
            "dataType": "string",
            "sourceColumn": "用户名称"
          },
          {
            "name": "登录设备",
            "dataType": "string",
            "sourceColumn": "登录设备"
          },
          {
            "name": "最后开屏时间",
            "dataType": "dateTime",
            "sourceColumn": "最后开屏时间"
          },
          {
            "name": "开屏时间",
            "dataType": "dateTime",
            "sourceColumn": "开屏时间"
          },
          {
            "name": "开屏次数",
            "dataType": "int64",
            "sourceColumn": "开屏次数"
          },
          {
            "name": "部门名称",
            "dataType": "string",
            "sourceColumn": "部门名称"
          },
          {
            "name": "职位",
            "dataType": "string",
            "sourceColumn": "职位"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_OPEN_APP_V = PICC{[Name=\"CC_COUNT_OPEN_APP_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_OPEN_APP_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名称\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"OPEN_LAST_TIME\", \"最后开屏时间\"}, {\"OPEN_DATE\", \"开屏时间\"}, {\"OPEN_NUM\", \"开屏次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"开屏时间\", type date}, {\"最后开屏时间\", type datetime}, {\"开屏次数\", Int64.Type}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型,{\"MODULE_CODE\", \"MODULE_NAME\", \"用户编码\", \"IP\", \"S_MTIME\", \"S_ATIME\"}),",
                "    提取的日期 = Table.TransformColumns(删除的列,{{\"最后开屏时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_OPEN_APP_V = PICC{[Name=\"CC_COUNT_OPEN_APP_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_OPEN_APP_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名称\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"OPEN_LAST_TIME\", \"最后开屏时间\"}, {\"OPEN_DATE\", \"开屏时间\"}, {\"OPEN_NUM\", \"开屏次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                  "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"开屏时间\", type date}, {\"最后开屏时间\", type datetime}, {\"开屏次数\", Int64.Type}}),",
                  "    删除的列 = Table.RemoveColumns(更改的类型,{\"MODULE_CODE\", \"MODULE_NAME\", \"用户编码\", \"IP\", \"S_MTIME\", \"S_ATIME\"})",
                  "in",
                  "    删除的列</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_OPEN_APP_V = PICC{[Name=\"CC_COUNT_OPEN_APP_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_OPEN_APP_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名称\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"OPEN_LAST_TIME\", \"最后开屏时间\"}, {\"OPEN_DATE\", \"开屏时间\"}, {\"OPEN_NUM\", \"开屏次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"开屏时间\", type date}, {\"最后开屏时间\", type datetime}, {\"开屏次数\", Int64.Type}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型,{\"MODULE_CODE\", \"MODULE_NAME\", \"用户编码\", \"IP\", \"S_MTIME\", \"S_ATIME\"}),",
                "    提取的日期 = Table.TransformColumns(删除的列,{{\"最后开屏时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_OPEN_APP_V = PICC{[Name=\"CC_COUNT_OPEN_APP_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_OPEN_APP_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名称\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"OPEN_LAST_TIME\", \"最后开屏时间\"}, {\"OPEN_DATE\", \"开屏时间\"}, {\"OPEN_NUM\", \"开屏次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                  "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"开屏时间\", type date}, {\"最后开屏时间\", type datetime}, {\"开屏次数\", Int64.Type}}),",
                  "    删除的列 = Table.RemoveColumns(更改的类型,{\"MODULE_CODE\", \"MODULE_NAME\", \"用户编码\", \"IP\", \"S_MTIME\", \"S_ATIME\"})",
                  "in",
                  "    删除的列</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_OPEN_APP_V = PICC{[Name=\"CC_COUNT_OPEN_APP_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_OPEN_APP_V, each [S_ATIME] >= \"2024-01-01\" and [S_ATIME] < \"2025-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名称\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"OPEN_LAST_TIME\", \"最后开屏时间\"}, {\"OPEN_DATE\", \"开屏时间\"}, {\"OPEN_NUM\", \"开屏次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"开屏时间\", type date}, {\"最后开屏时间\", type datetime}, {\"开屏次数\", Int64.Type}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型,{\"MODULE_CODE\", \"MODULE_NAME\", \"用户编码\", \"IP\", \"S_MTIME\", \"S_ATIME\"}),",
                "    提取的日期 = Table.TransformColumns(删除的列,{{\"最后开屏时间\", DateTime.Date, type date}})",
                "in",
                "    提取的日期"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【开屏次数】",
            "expression": "SUM('开屏统计'[开屏次数])",
            "formatString": "0",
            "lineageTag": "dd8ab5ef-1890-45cf-8f13-343b1a6071a6"
          }
        ]
      },
      {
        "name": "消息推送统计",
        "columns": [
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID"
          },
          {
            "name": "推送时间",
            "dataType": "dateTime",
            "sourceColumn": "推送时间"
          },
          {
            "name": "时刻",
            "dataType": "int64",
            "sourceColumn": "时刻"
          },
          {
            "name": "推送类别",
            "dataType": "string",
            "sourceColumn": "推送类别"
          },
          {
            "name": "用户编码",
            "dataType": "string",
            "sourceColumn": "用户编码"
          },
          {
            "name": "推送类别2",
            "dataType": "string",
            "sourceColumn": "推送类别2"
          },
          {
            "name": "接收用户名称",
            "dataType": "string",
            "sourceColumn": "接收用户名称"
          },
          {
            "name": "用户部门",
            "dataType": "string",
            "sourceColumn": "用户部门"
          },
          {
            "name": "职位",
            "dataType": "string",
            "sourceColumn": "职位"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_MESSAGE_PUSH_V = PICC{[Name=\"CC_COUNT_MESSAGE_PUSH_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_MESSAGE_PUSH_V, each [S_MTIME] >= \"2018-01-01\" and [S_MTIME] < \"2023-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"SEND_TIME\", \"推送时间\"}, {\"SEND_TITLE\", \"推送标题\"}, {\"SEND_TYPE\", \"推送类别\"}, {\"SEND_BODY\", \"推送内容\"}, {\"SEND_USER_CODE\", \"用户编码\"}, {\"SEND_TYPE_NAME\", \"推送类别2\"}, {\"USER_NAME\", \"接收用户名称\"}, {\"DEPT_NAME\", \"用户部门\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    用位置分列 = Table.SplitColumn(重命名的列, \"推送时间\", Splitter.SplitTextByPositions({0, 10}, false), {\"推送时间.1\", \"推送时间.2\"}),",
                "    更改的类型 = Table.TransformColumnTypes(用位置分列,{{\"推送时间.1\", type date}, {\"推送时间.2\", type text}}),",
                "    重命名的列1 = Table.RenameColumns(更改的类型,{{\"推送时间.1\", \"推送时间\"}}),",
                "    按分隔符拆分列 = Table.SplitColumn(重命名的列1, \"推送时间.2\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"推送时间.2.1\", \"推送时间.2.2\"}),",
                "    更改的类型1 = Table.TransformColumnTypes(按分隔符拆分列,{{\"推送时间.2.1\", Int64.Type}, {\"推送时间.2.2\", type text}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型1,{\"推送时间.2.2\"}),",
                "    重命名的列2 = Table.RenameColumns(删除的列,{{\"推送时间.2.1\", \"时刻\"}}),",
                "    删除的列1 = Table.RemoveColumns(重命名的列2,{\"MODULE_CODE\", \"MODULE_NAME\", \"MODULE_URL\", \"S_ATIME\", \"S_MTIME\", \"推送标题\", \"推送内容\", \"SEND_QTIME\", \"SEND_KIND\", \"SEND_USER_ID\"})",
                "in",
                "    删除的列1"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_MESSAGE_PUSH_V = PICC{[Name=\"CC_COUNT_MESSAGE_PUSH_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_MESSAGE_PUSH_V, each [S_MTIME] >= \"2018-01-01\" and [S_MTIME] < \"2023-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"SEND_TIME\", \"推送时间\"}, {\"SEND_TITLE\", \"推送标题\"}, {\"SEND_TYPE\", \"推送类别\"}, {\"SEND_BODY\", \"推送内容\"}, {\"SEND_USER_CODE\", \"用户编码\"}, {\"SEND_TYPE_NAME\", \"推送类别2\"}, {\"USER_NAME\", \"接收用户名称\"}, {\"DEPT_NAME\", \"用户部门\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                  "    用位置分列 = Table.SplitColumn(重命名的列, \"推送时间\", Splitter.SplitTextByPositions({0, 10}, false), {\"推送时间.1\", \"推送时间.2\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(用位置分列,{{\"推送时间.1\", type date}, {\"推送时间.2\", type text}}),",
                  "    重命名的列1 = Table.RenameColumns(更改的类型,{{\"推送时间.1\", \"推送时间\"}}),",
                  "    按分隔符拆分列 = Table.SplitColumn(重命名的列1, \"推送时间.2\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"推送时间.2.1\", \"推送时间.2.2\"}),",
                  "    更改的类型1 = Table.TransformColumnTypes(按分隔符拆分列,{{\"推送时间.2.1\", Int64.Type}, {\"推送时间.2.2\", type text}}),",
                  "    删除的列 = Table.RemoveColumns(更改的类型1,{\"推送时间.2.2\"}),",
                  "    重命名的列2 = Table.RenameColumns(删除的列,{{\"推送时间.2.1\", \"时刻\"}}),",
                  "    删除的列1 = Table.RemoveColumns(重命名的列2,{\"MODULE_CODE\", \"MODULE_NAME\", \"MODULE_URL\", \"S_ATIME\", \"S_MTIME\", \"推送标题\", \"推送内容\", \"SEND_QTIME\", \"SEND_KIND\", \"SEND_USER_ID\"})",
                  "in",
                  "    删除的列1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_MESSAGE_PUSH_V = PICC{[Name=\"CC_COUNT_MESSAGE_PUSH_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_MESSAGE_PUSH_V, each [S_MTIME] >= \"2023-01-01\" and [S_MTIME] < \"2024-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"SEND_TIME\", \"推送时间\"}, {\"SEND_TITLE\", \"推送标题\"}, {\"SEND_TYPE\", \"推送类别\"}, {\"SEND_BODY\", \"推送内容\"}, {\"SEND_USER_CODE\", \"用户编码\"}, {\"SEND_TYPE_NAME\", \"推送类别2\"}, {\"USER_NAME\", \"接收用户名称\"}, {\"DEPT_NAME\", \"用户部门\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    用位置分列 = Table.SplitColumn(重命名的列, \"推送时间\", Splitter.SplitTextByPositions({0, 10}, false), {\"推送时间.1\", \"推送时间.2\"}),",
                "    更改的类型 = Table.TransformColumnTypes(用位置分列,{{\"推送时间.1\", type date}, {\"推送时间.2\", type text}}),",
                "    重命名的列1 = Table.RenameColumns(更改的类型,{{\"推送时间.1\", \"推送时间\"}}),",
                "    按分隔符拆分列 = Table.SplitColumn(重命名的列1, \"推送时间.2\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"推送时间.2.1\", \"推送时间.2.2\"}),",
                "    更改的类型1 = Table.TransformColumnTypes(按分隔符拆分列,{{\"推送时间.2.1\", Int64.Type}, {\"推送时间.2.2\", type text}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型1,{\"推送时间.2.2\"}),",
                "    重命名的列2 = Table.RenameColumns(删除的列,{{\"推送时间.2.1\", \"时刻\"}}),",
                "    删除的列1 = Table.RemoveColumns(重命名的列2,{\"MODULE_CODE\", \"MODULE_NAME\", \"MODULE_URL\", \"S_ATIME\", \"S_MTIME\", \"推送标题\", \"推送内容\", \"SEND_QTIME\", \"SEND_KIND\", \"SEND_USER_ID\"})",
                "in",
                "    删除的列1"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_MESSAGE_PUSH_V = PICC{[Name=\"CC_COUNT_MESSAGE_PUSH_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_MESSAGE_PUSH_V, each [S_MTIME] >= \"2023-01-01\" and [S_MTIME] < \"2024-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"SEND_TIME\", \"推送时间\"}, {\"SEND_TITLE\", \"推送标题\"}, {\"SEND_TYPE\", \"推送类别\"}, {\"SEND_BODY\", \"推送内容\"}, {\"SEND_USER_CODE\", \"用户编码\"}, {\"SEND_TYPE_NAME\", \"推送类别2\"}, {\"USER_NAME\", \"接收用户名称\"}, {\"DEPT_NAME\", \"用户部门\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                  "    用位置分列 = Table.SplitColumn(重命名的列, \"推送时间\", Splitter.SplitTextByPositions({0, 10}, false), {\"推送时间.1\", \"推送时间.2\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(用位置分列,{{\"推送时间.1\", type date}, {\"推送时间.2\", type text}}),",
                  "    重命名的列1 = Table.RenameColumns(更改的类型,{{\"推送时间.1\", \"推送时间\"}}),",
                  "    按分隔符拆分列 = Table.SplitColumn(重命名的列1, \"推送时间.2\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"推送时间.2.1\", \"推送时间.2.2\"}),",
                  "    更改的类型1 = Table.TransformColumnTypes(按分隔符拆分列,{{\"推送时间.2.1\", Int64.Type}, {\"推送时间.2.2\", type text}}),",
                  "    删除的列 = Table.RemoveColumns(更改的类型1,{\"推送时间.2.2\"}),",
                  "    重命名的列2 = Table.RenameColumns(删除的列,{{\"推送时间.2.1\", \"时刻\"}}),",
                  "    删除的列1 = Table.RemoveColumns(重命名的列2,{\"MODULE_CODE\", \"MODULE_NAME\", \"MODULE_URL\", \"S_ATIME\", \"S_MTIME\", \"推送标题\", \"推送内容\", \"SEND_QTIME\", \"SEND_KIND\", \"SEND_USER_ID\"})",
                  "in",
                  "    删除的列1</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_MESSAGE_PUSH_V = PICC{[Name=\"CC_COUNT_MESSAGE_PUSH_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_MESSAGE_PUSH_V, each [S_MTIME] >= \"2024-01-01\" and [S_MTIME] < \"2025-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"SEND_TIME\", \"推送时间\"}, {\"SEND_TITLE\", \"推送标题\"}, {\"SEND_TYPE\", \"推送类别\"}, {\"SEND_BODY\", \"推送内容\"}, {\"SEND_USER_CODE\", \"用户编码\"}, {\"SEND_TYPE_NAME\", \"推送类别2\"}, {\"USER_NAME\", \"接收用户名称\"}, {\"DEPT_NAME\", \"用户部门\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    用位置分列 = Table.SplitColumn(重命名的列, \"推送时间\", Splitter.SplitTextByPositions({0, 10}, false), {\"推送时间.1\", \"推送时间.2\"}),",
                "    更改的类型 = Table.TransformColumnTypes(用位置分列,{{\"推送时间.1\", type date}, {\"推送时间.2\", type text}}),",
                "    重命名的列1 = Table.RenameColumns(更改的类型,{{\"推送时间.1\", \"推送时间\"}}),",
                "    按分隔符拆分列 = Table.SplitColumn(重命名的列1, \"推送时间.2\", Splitter.SplitTextByEachDelimiter({\":\"}, QuoteStyle.Csv, false), {\"推送时间.2.1\", \"推送时间.2.2\"}),",
                "    更改的类型1 = Table.TransformColumnTypes(按分隔符拆分列,{{\"推送时间.2.1\", Int64.Type}, {\"推送时间.2.2\", type text}}),",
                "    删除的列 = Table.RemoveColumns(更改的类型1,{\"推送时间.2.2\"}),",
                "    重命名的列2 = Table.RenameColumns(删除的列,{{\"推送时间.2.1\", \"时刻\"}}),",
                "    删除的列1 = Table.RemoveColumns(重命名的列2,{\"MODULE_CODE\", \"MODULE_NAME\", \"MODULE_URL\", \"S_ATIME\", \"S_MTIME\", \"推送标题\", \"推送内容\", \"SEND_QTIME\", \"SEND_KIND\", \"SEND_USER_ID\"})",
                "in",
                "    删除的列1"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【推送条数】",
            "expression": "DISTINCTCOUNT('消息推送统计'[ID])",
            "formatString": "0",
            "lineageTag": "fbb554a2-80ca-4299-923e-98abe05603c9"
          }
        ]
      },
      {
        "name": "通讯录统计",
        "columns": [
          {
            "name": "ID",
            "dataType": "string",
            "sourceColumn": "ID"
          },
          {
            "name": "MODULE_CODE",
            "dataType": "string",
            "sourceColumn": "MODULE_CODE"
          },
          {
            "name": "MODULE_NAME",
            "dataType": "string",
            "sourceColumn": "MODULE_NAME"
          },
          {
            "name": "访问设备",
            "dataType": "string",
            "sourceColumn": "访问设备"
          },
          {
            "name": "S_ATIME",
            "dataType": "string",
            "sourceColumn": "S_ATIME"
          },
          {
            "name": "S_MTIME",
            "dataType": "string",
            "sourceColumn": "S_MTIME"
          },
          {
            "name": "用户编码",
            "dataType": "string",
            "sourceColumn": "用户编码"
          },
          {
            "name": "访问次数",
            "dataType": "int64",
            "sourceColumn": "访问次数"
          },
          {
            "name": "最后访问时间",
            "dataType": "string",
            "sourceColumn": "最后访问时间"
          },
          {
            "name": "MODULE_URL",
            "dataType": "string",
            "sourceColumn": "MODULE_URL"
          },
          {
            "name": "统计日期",
            "dataType": "dateTime",
            "sourceColumn": "统计日期"
          },
          {
            "name": "用户名",
            "dataType": "string",
            "sourceColumn": "用户名"
          },
          {
            "name": "部门名称",
            "dataType": "string",
            "sourceColumn": "部门名称"
          },
          {
            "name": "职位",
            "dataType": "string",
            "sourceColumn": "职位"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_CONTACT_V = PICC{[Name=\"CC_COUNT_CONTACT_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_CONTACT_V, each [S_MTIME] >= \"2018-01-01\" and [S_MTIME] < \"2023-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"访问设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"CLICK_COUNT\", \"访问次数\"}, {\"CLICK_LAST_TIME\", \"最后访问时间\"}, {\"MODULE_DATE\", \"统计日期\"}, {\"USER_NAME\", \"用户名\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"统计日期\", type date}, {\"访问次数\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_CONTACT_V = PICC{[Name=\"CC_COUNT_CONTACT_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_CONTACT_V, each [S_MTIME] >= \"2018-01-01\" and [S_MTIME] < \"2023-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"访问设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"CLICK_COUNT\", \"访问次数\"}, {\"CLICK_LAST_TIME\", \"最后访问时间\"}, {\"MODULE_DATE\", \"统计日期\"}, {\"USER_NAME\", \"用户名\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                  "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"统计日期\", type date}, {\"访问次数\", Int64.Type}})",
                  "in",
                  "    更改的类型</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_CONTACT_V = PICC{[Name=\"CC_COUNT_CONTACT_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_CONTACT_V, each [S_MTIME] >= \"2023-01-01\" and [S_MTIME] < \"2024-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"访问设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"CLICK_COUNT\", \"访问次数\"}, {\"CLICK_LAST_TIME\", \"最后访问时间\"}, {\"MODULE_DATE\", \"统计日期\"}, {\"USER_NAME\", \"用户名\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"统计日期\", type date}, {\"访问次数\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_CONTACT_V = PICC{[Name=\"CC_COUNT_CONTACT_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_CONTACT_V, each [S_MTIME] >= \"2023-01-01\" and [S_MTIME] < \"2024-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"访问设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"CLICK_COUNT\", \"访问次数\"}, {\"CLICK_LAST_TIME\", \"最后访问时间\"}, {\"MODULE_DATE\", \"统计日期\"}, {\"USER_NAME\", \"用户名\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                  "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"统计日期\", type date}, {\"访问次数\", Int64.Type}})",
                  "in",
                  "    更改的类型</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_CONTACT_V = PICC{[Name=\"CC_COUNT_CONTACT_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_CONTACT_V, each [S_MTIME] >= \"2024-01-01\" and [S_MTIME] < \"2025-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"访问设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"CLICK_COUNT\", \"访问次数\"}, {\"CLICK_LAST_TIME\", \"最后访问时间\"}, {\"MODULE_DATE\", \"统计日期\"}, {\"USER_NAME\", \"用户名\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职位\"}, {\"USER_LEVEL_NAME\", \"岗位\"}}),",
                "    更改的类型 = Table.TransformColumnTypes(重命名的列,{{\"统计日期\", type date}, {\"访问次数\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【访问次数】",
            "expression": "SUM('通讯录统计'[访问次数])",
            "formatString": "0",
            "lineageTag": "af87e9a6-6d6b-4122-bd56-ffec3994732c"
          }
        ]
      },
      {
        "name": "登录其他系统_新",
        "columns": [
          {
            "name": "登录设备",
            "dataType": "string",
            "sourceColumn": "登录设备"
          },
          {
            "name": "用户编码",
            "dataType": "string",
            "sourceColumn": "用户编码"
          },
          {
            "name": "用户名",
            "dataType": "string",
            "sourceColumn": "用户名"
          },
          {
            "name": "登录次数",
            "dataType": "int64",
            "sourceColumn": "登录次数"
          },
          {
            "name": "登入日期",
            "dataType": "dateTime",
            "sourceColumn": "登入日期"
          },
          {
            "name": "登录IP",
            "dataType": "string",
            "sourceColumn": "登录IP"
          },
          {
            "name": "单位名称",
            "dataType": "string",
            "sourceColumn": "单位名称"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          },
          {
            "name": "职位",
            "dataType": "string",
            "sourceColumn": "职位"
          },
          {
            "name": "登录系统类别",
            "dataType": "string",
            "sourceColumn": "登录系统类别"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_ACCESS_V = PICC{[Name=\"CC_COUNT_ACCESS_SYSTEM_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_ACCESS_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名\"}, {\"ACCESS_SYSTEM_NAME\", \"登录系统类别\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职位\"}, {\"DEPT_NAME\", \"单位名称\"}, {\"ACCESS_DATE\", \"登入日期\"}, {\"ACCESS_NUM\", \"登录次数\"}, {\"LOGIN_IP\", \"登录IP\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"登录设备\", \"用户编码\", \"用户名\", \"登录次数\", \"登入日期\", \"登录IP\", \"单位名称\", \"岗位\", \"职位\", \"登录系统类别\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登入日期\", type date}, {\"登录次数\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_ACCESS_V = PICC{[Name=\"CC_COUNT_ACCESS_SYSTEM_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_ACCESS_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名\"}, {\"ACCESS_SYSTEM_NAME\", \"登录系统类别\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职位\"}, {\"DEPT_NAME\", \"单位名称\"}, {\"ACCESS_DATE\", \"登入日期\"}, {\"ACCESS_NUM\", \"登录次数\"}, {\"LOGIN_IP\", \"登录IP\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列,{\"登录设备\", \"用户编码\", \"用户名\", \"登录次数\", \"登入日期\", \"登录IP\", \"单位名称\", \"岗位\", \"职位\", \"登录系统类别\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登入日期\", type date}, {\"登录次数\", Int64.Type}})",
                  "in",
                  "    更改的类型</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_ACCESS_V = PICC{[Name=\"CC_COUNT_ACCESS_SYSTEM_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_ACCESS_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名\"}, {\"ACCESS_SYSTEM_NAME\", \"登录系统类别\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职位\"}, {\"DEPT_NAME\", \"单位名称\"}, {\"ACCESS_DATE\", \"登入日期\"}, {\"ACCESS_NUM\", \"登录次数\"}, {\"LOGIN_IP\", \"登录IP\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"登录设备\", \"用户编码\", \"用户名\", \"登录次数\", \"登入日期\", \"登录IP\", \"单位名称\", \"岗位\", \"职位\", \"登录系统类别\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登入日期\", type date}, {\"登录次数\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_ACCESS_V = PICC{[Name=\"CC_COUNT_ACCESS_SYSTEM_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_ACCESS_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名\"}, {\"ACCESS_SYSTEM_NAME\", \"登录系统类别\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职位\"}, {\"DEPT_NAME\", \"单位名称\"}, {\"ACCESS_DATE\", \"登入日期\"}, {\"ACCESS_NUM\", \"登录次数\"}, {\"LOGIN_IP\", \"登录IP\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列,{\"登录设备\", \"用户编码\", \"用户名\", \"登录次数\", \"登入日期\", \"登录IP\", \"单位名称\", \"岗位\", \"职位\", \"登录系统类别\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登入日期\", type date}, {\"登录次数\", Int64.Type}})",
                  "in",
                  "    更改的类型</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_ACCESS_V = PICC{[Name=\"CC_COUNT_ACCESS_SYSTEM_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_ACCESS_V, each [S_ATIME] >= \"2024-01-01\" and [S_ATIME] < \"2025-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"MODULE_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"USER_NAME\", \"用户名\"}, {\"ACCESS_SYSTEM_NAME\", \"登录系统类别\"}, {\"USER_POST_NAME\", \"岗位\"}, {\"USER_LEVEL_NAME\", \"职位\"}, {\"DEPT_NAME\", \"单位名称\"}, {\"ACCESS_DATE\", \"登入日期\"}, {\"ACCESS_NUM\", \"登录次数\"}, {\"LOGIN_IP\", \"登录IP\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"登录设备\", \"用户编码\", \"用户名\", \"登录次数\", \"登入日期\", \"登录IP\", \"单位名称\", \"岗位\", \"职位\", \"登录系统类别\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登入日期\", type date}, {\"登录次数\", Int64.Type}})",
                "in",
                "    更改的类型"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【登录其他系统次数_new】",
            "expression": "SUM('登录其他系统_新'[登录次数])",
            "formatString": "0",
            "lineageTag": "4e075862-2d27-46a3-ba79-e5f8ab550764"
          },
          {
            "name": "【登录其它系统天数_new】",
            "expression": "DATEDIFF(MIN('登录其他系统_新'[登入日期]), MAX('登录其他系统_新'[登入日期]),DAY)+1",
            "formatString": "0",
            "lineageTag": "41ee7e69-c847-49aa-ba55-9242fc4a903d"
          },
          {
            "name": "【其它系统次数/每天_new】",
            "expression": "DIVIDE([【登录其他系统次数_new】],[【登录其它系统天数_new】])",
            "lineageTag": "0dfb7901-8126-40f9-b9ec-45e65dfb1b2d",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ]
      },
      {
        "name": "登录系统_新",
        "columns": [
          {
            "name": "用户编码",
            "dataType": "string",
            "sourceColumn": "用户编码"
          },
          {
            "name": "用户名",
            "dataType": "string",
            "sourceColumn": "用户名"
          },
          {
            "name": "IP",
            "dataType": "string",
            "sourceColumn": "IP"
          },
          {
            "name": "登录设备",
            "dataType": "string",
            "sourceColumn": "登录设备"
          },
          {
            "name": "最后登录时间",
            "dataType": "dateTime",
            "sourceColumn": "最后登录时间"
          },
          {
            "name": "登录日期",
            "dataType": "dateTime",
            "sourceColumn": "登录日期"
          },
          {
            "name": "当日登录次数",
            "dataType": "int64",
            "sourceColumn": "当日登录次数"
          },
          {
            "name": "部门名称",
            "dataType": "string",
            "sourceColumn": "部门名称"
          },
          {
            "name": "职务",
            "dataType": "string",
            "sourceColumn": "职务"
          },
          {
            "name": "岗位",
            "dataType": "string",
            "sourceColumn": "岗位"
          },
          {
            "name": "最后开屏时刻",
            "dataType": "int64",
            "sourceColumn": "最后开屏时刻"
          }
        ],
        "partitions": [
          {
            "name": "2018-2022",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_LOGIN_V = PICC{[Name=\"CC_COUNT_USER_LOGIN_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_LOGIN_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_NAME\", \"用户名\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"LOGIN_DATE\", \"登录日期\"}, {\"LOGIN_NUM\", \"当日登录次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职务\"}, {\"USER_LEVEL_NAME\", \"岗位\"}, {\"LOGIN_LAST_TIME\", \"最后登录时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"用户编码\", \"用户名\", \"IP\", \"登录设备\", \"最后登录时间\", \"登录日期\", \"当日登录次数\", \"部门名称\", \"职务\", \"岗位\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登录日期\", type date}, {\"当日登录次数\", Int64.Type}, {\"最后登录时间\", type datetime}}),",
                "    插入的小时开头 = Table.AddColumn(更改的类型, \"最后开屏时刻\", each Time.Hour([最后登录时间]), Int64.Type)",
                "in",
                "    插入的小时开头"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_LOGIN_V = PICC{[Name=\"CC_COUNT_USER_LOGIN_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_LOGIN_V, each [S_ATIME] >= \"2018-01-01\" and [S_ATIME] < \"2023-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_NAME\", \"用户名\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"LOGIN_DATE\", \"登录日期\"}, {\"LOGIN_NUM\", \"当日登录次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职务\"}, {\"USER_LEVEL_NAME\", \"岗位\"}, {\"LOGIN_LAST_TIME\", \"最后登录时间\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列,{\"用户编码\", \"用户名\", \"IP\", \"登录设备\", \"最后登录时间\", \"登录日期\", \"当日登录次数\", \"部门名称\", \"职务\", \"岗位\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登录日期\", type date}, {\"当日登录次数\", Int64.Type}, {\"最后登录时间\", type datetime}})",
                  "in",
                  "    更改的类型</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2023",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_LOGIN_V = PICC{[Name=\"CC_COUNT_USER_LOGIN_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_LOGIN_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_NAME\", \"用户名\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"LOGIN_DATE\", \"登录日期\"}, {\"LOGIN_NUM\", \"当日登录次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职务\"}, {\"USER_LEVEL_NAME\", \"岗位\"}, {\"LOGIN_LAST_TIME\", \"最后登录时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"用户编码\", \"用户名\", \"IP\", \"登录设备\", \"最后登录时间\", \"登录日期\", \"当日登录次数\", \"部门名称\", \"职务\", \"岗位\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登录日期\", type date}, {\"当日登录次数\", Int64.Type}, {\"最后登录时间\", type datetime}}),",
                "    已添加自定义 = Table.AddColumn(更改的类型, \"最后开屏时刻\", each Time.Hour([最后登录时间]), Int64.Type)",
                "in",
                "    已添加自定义"
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    源 = picc,",
                  "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                  "    CC_COUNT_LOGIN_V = PICC{[Name=\"CC_COUNT_USER_LOGIN_V\"]}[Data],",
                  "    筛选的行 = Table.SelectRows(CC_COUNT_LOGIN_V, each [S_ATIME] >= \"2023-01-01\" and [S_ATIME] < \"2024-01-01\"),",
                  "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_NAME\", \"用户名\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"LOGIN_DATE\", \"登录日期\"}, {\"LOGIN_NUM\", \"当日登录次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职务\"}, {\"USER_LEVEL_NAME\", \"岗位\"}, {\"LOGIN_LAST_TIME\", \"最后登录时间\"}}),",
                  "    删除的其他列 = Table.SelectColumns(重命名的列,{\"用户编码\", \"用户名\", \"IP\", \"登录设备\", \"最后登录时间\", \"登录日期\", \"当日登录次数\", \"部门名称\", \"职务\", \"岗位\"}),",
                  "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登录日期\", type date}, {\"当日登录次数\", Int64.Type}, {\"最后登录时间\", type datetime}})",
                  "in",
                  "    更改的类型</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "2024",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    源 = picc,",
                "    PICC = 源{[Schema=\"PICC\"]}[Data],",
                "    CC_COUNT_LOGIN_V = PICC{[Name=\"CC_COUNT_USER_LOGIN_V\"]}[Data],",
                "    筛选的行 = Table.SelectRows(CC_COUNT_LOGIN_V, each [S_ATIME] >= \"2024-01-01\" and [S_ATIME] < \"2025-01-01\"),",
                "    重命名的列 = Table.RenameColumns(筛选的行,{{\"USER_NAME\", \"用户名\"}, {\"ACCESS_DEVICE\", \"登录设备\"}, {\"USER_CODE\", \"用户编码\"}, {\"LOGIN_DATE\", \"登录日期\"}, {\"LOGIN_NUM\", \"当日登录次数\"}, {\"DEPT_NAME\", \"部门名称\"}, {\"USER_POST_NAME\", \"职务\"}, {\"USER_LEVEL_NAME\", \"岗位\"}, {\"LOGIN_LAST_TIME\", \"最后登录时间\"}}),",
                "    删除的其他列 = Table.SelectColumns(重命名的列,{\"用户编码\", \"用户名\", \"IP\", \"登录设备\", \"最后登录时间\", \"登录日期\", \"当日登录次数\", \"部门名称\", \"职务\", \"岗位\"}),",
                "    更改的类型 = Table.TransformColumnTypes(删除的其他列,{{\"登录日期\", type date}, {\"当日登录次数\", Int64.Type}, {\"最后登录时间\", type datetime}}),",
                "    已添加自定义 = Table.AddColumn(更改的类型, \"最后开屏时刻\", each Time.Hour([最后登录时间]), Int64.Type)",
                "in",
                "    已添加自定义"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "【登录次数_new】",
            "expression": "SUM('登录系统_新'[当日登录次数])",
            "formatString": "0",
            "lineageTag": "eec1f845-47a9-4a4d-9b9e-0b26d593f105"
          },
          {
            "name": "【登录天数_new】",
            "expression": "DATEDIFF(MIN('登录系统_新'[登录日期]), MAX('登录系统_新'[登录日期]),DAY)+1",
            "formatString": "0",
            "lineageTag": "6a3963e0-285c-406d-8a8f-f83a0eadb180"
          },
          {
            "name": "【登录次数/每天_new】",
            "expression": "DIVIDE([【登录次数_new】],[【登录天数_new】])",
            "lineageTag": "5d645874-97b2-4c7b-a15e-34c9bc0469d9",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "【开屏次数_new】",
            "expression": "SUM('登录系统_新'[当日登录次数])",
            "formatString": "0",
            "lineageTag": "eb5a7faf-b1ce-4915-bc22-9ff66261e364"
          },
          {
            "name": "登录人数",
            "expression": "DISTINCTCOUNT('登录系统_新'[用户编码] )",
            "formatString": "0",
            "lineageTag": "9bdac637-ca0c-48ef-bccc-d3b29107832f"
          }
        ]
      },
      {
        "name": "日历",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]"
          },
          {
            "type": "calculated",
            "name": "年月日",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "FORMAT('日历'[Date],\"yyyy-mm-dd\")",
            "lineageTag": "a94d6958-f2e3-45f9-ba6e-4247752be7f0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "年",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "year('日历'[Date])",
            "lineageTag": "5ccff92f-8209-4bd7-85e8-6dae167ae820"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " CALENDAR(\"2017-1-1\",\"2024-12-31\")"
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "a1772723-c18a-4aab-9143-78564601000d",
        "fromTable": "登录系统_新",
        "fromColumn": "登录日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "d5cf8067-7611-4009-9f0f-2795d5423394",
        "fromTable": "登录其他系统_新",
        "fromColumn": "登入日期",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "198df571-6a7b-4a14-93a2-b0f414810a9d",
        "fromTable": "待办事务",
        "fromColumn": "创建时间",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "caccdc2e-aee5-427d-aa31-4ec3677259ea",
        "fromTable": "处理业务设备",
        "fromColumn": "最后处理时间",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "38a989b7-b0bf-48bc-9d0c-05220af21e04",
        "fromTable": "消息推送统计",
        "fromColumn": "推送时间",
        "toTable": "日历",
        "toColumn": "Date"
      },
      {
        "name": "b3c1b4ca-91e3-4b87-9871-b1b5f15b6483",
        "fromTable": "通讯录统计",
        "fromColumn": "统计日期",
        "toTable": "日历",
        "toColumn": "Date"
      }
    ],
    "expressions": [
      {
        "name": "picc",
        "kind": "m",
        "expression": [
          "let",
          "    源 = Oracle.Database(\"172.16.8.127/racdb.com\", [HierarchicalNavigation=true])",
          "in",
          "    源"
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "700"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  },
  "id": "SemanticModel"
}