table 延迟段
	lineageTag: 160f3eb6-60fc-4f1e-81c8-45841ca0c9c9

	column 天数
		dataType: int64
		formatString: 0
		lineageTag: d69af30e-d7a4-4c6b-99c4-f91026fadb6e
		summarizeBy: none
		sourceColumn: 天数

		annotation SummarizationSetBy = Automatic

	column 超期段
		dataType: string
		lineageTag: 6f5cf3d0-38fc-4c97-a826-632966770ea9
		summarizeBy: none
		sourceColumn: 超期段

		annotation SummarizationSetBy = Automatic

	partition 延迟段 = m
		mode: import
		source =
				let
				    源 = {0..5000},
				    转换为表 = Table.FromList(源, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    重命名的列 = Table.RenameColumns(转换为表,{{"Column1", "天数"}}),
				    已添加自定义 = Table.AddColumn(重命名的列, "超期段", each Text.From(([天数])*30) &"~" &Text.From(([天数]+1)*30)),
				    更改的类型 = Table.TransformColumnTypes(已添加自定义,{{"天数", Int64.Type}, {"超期段", type text}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

