table 货币单位
	lineageTag: 95444010-29fd-4fec-bdd5-c437ede099b0

	column 货币单位
		dataType: string
		lineageTag: 2b5447bf-3bec-45c4-9b2a-49d489531c1b
		summarizeBy: none
		sourceColumn: 货币单位

		annotation SummarizationSetBy = Automatic

	column 系数
		dataType: double
		lineageTag: e8426c2b-534b-4e6a-8073-2a8751a32189
		summarizeBy: sum
		sourceColumn: 系数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 货币单位 = m
		mode: import
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WetrarKSjZKgUqxOt9GRHO4htAAQQ/q79MD5ELBYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [货币单位 = _t, 系数 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"系数", type number}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

