table D-责任体
	excludeFromModelRefresh
	lineageTag: 87e8a0c8-870b-4155-a0f5-4ab4d03f7919

	column 责任体
		dataType: string
		lineageTag: c4ea918c-0f44-4281-b446-7c7c780698c0
		summarizeBy: none
		sourceColumn: 责任体

		annotation SummarizationSetBy = Automatic

	column 排序
		dataType: int64
		formatString: 0
		lineageTag: a2381a50-4c04-4a88-902b-223af707af46
		summarizeBy: none
		sourceColumn: 排序

		annotation SummarizationSetBy = Automatic

	column 责任体简称
		dataType: string
		lineageTag: 5bd14c49-8833-4f09-9840-6d17472e399a
		summarizeBy: none
		sourceColumn: 责任体简称

		annotation SummarizationSetBy = Automatic

	partition D-责任体 = m
		mode: import
		queryGroup: 维度表
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("XZBLDoIwEEDvMmsW4t+zEO5iNBqJgK40sS4lccFSYyUxXKYjeAun04KVxSz65uWlbRAArnLcyUrc6n0GHvg0BkHoBaDkGeMjbtaWedCnMZQFTNKOMNAFpo2gdUcYGoFoW0j+CiNbSEyhzsqOMKYxlIUqz5Wcq2Kr5OmzvNJyogvpgmgrFLErTK1QxL9C5AqzphA1AgrhCn7PGITZeN8feDnohf4he+L3PUv1Eu71ff5kxhCGXw==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [责任体 = _t, 排序 = _t, 责任体简称 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"责任体", type text}, {"排序", Int64.Type}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

