table F_下游合同完成量
	isHidden
	lineageTag: c310d441-a5c6-4c72-bdd7-92ed88391f51

	column KEYID
		dataType: string
		isHidden
		lineageTag: 793f9a19-6bce-45b9-8266-ac20b47d6aed
		summarizeBy: none
		sourceColumn: KEYID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: dcd3de3a-f310-476a-871a-d90ee8f51a80
		summarizeBy: none
		sourceColumn: 日期

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 价税合计
		dataType: double
		isHidden
		lineageTag: d467b51a-fa4b-47c0-84f7-7ab4cf38b7d9
		summarizeBy: sum
		sourceColumn: 价税合计

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目名称
		dataType: string
		lineageTag: 2b230374-a53a-4cf9-8363-f7c40e5323ac
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 客商名称
		dataType: string
		lineageTag: 0e732a1d-3a60-4c33-95a7-3dc60b4a987a
		summarizeBy: none
		sourceColumn: 客商名称

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		lineageTag: 452c3668-9e8d-4832-a20d-c3283288074d
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: e1fa2f6d-0656-4f5a-8f90-2b0afafae63b
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_下游合同完成量 = m
		mode: import
		queryGroup: 下游合同\合同组\合同完成量
		source =
				let
				    源 = Table.Combine({#"DW_FB_BLMX（分包报量）", #"DW_WZ_DZMX（物资对账）", #"DW_WZ_ZLMX（租赁对账）",#"DW_WZ_JCMX（物资进场）",#"DW_WZ_TCMX（物资退场）"}),
				    #"合并的查询（参照完整性）" = Table.NestedJoin(源, {"KEYID"}, D_下游合同_参照完整, {"KEYID"}, "D_下游合同", JoinKind.Inner),
				    #"展开的“D_下游合同”" = Table.ExpandTableColumn(#"合并的查询（参照完整性）", "D_下游合同", {"项目名称", "客商名称"}, {"项目名称", "客商名称"}),
				    // 0值对计数产生干扰
				    #"筛选的行（去掉0）" = Table.SelectRows(#"展开的“D_下游合同”", each [价税合计] <> 0)
				in
				    #"筛选的行（去掉0）"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = 导航

