table F_下游合同评审
	lineageTag: 462d2171-3e5d-4337-92be-333db82b3fd3

	column KEYID
		dataType: string
		isHidden
		lineageTag: 568a9549-6a4b-4b9c-b8af-245946ce3549
		summarizeBy: none
		sourceColumn: KEYID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 合同版本
		dataType: string
		isHidden
		lineageTag: 08a923aa-46e2-45ef-9a8d-1911916ca0e7
		summarizeBy: none
		sourceColumn: 合同版本

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		isHidden
		formatString: Long Date
		lineageTag: 831bc795-d7af-419f-83b7-80bfbe33a7cb
		summarizeBy: none
		sourceColumn: 日期

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 价税合计
		dataType: double
		isHidden
		lineageTag: a3aad4e6-ccc6-4bd2-b777-05d021d46ec4
		summarizeBy: sum
		sourceColumn: 价税合计

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目名称
		dataType: string
		isHidden
		lineageTag: fa2a01f7-5da0-45d7-a542-2813a952d800
		summarizeBy: none
		sourceColumn: 项目名称

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 客商名称
		dataType: string
		isHidden
		lineageTag: a4bbee75-aed6-4a37-91e9-be04eee27f7f
		summarizeBy: none
		sourceColumn: 客商名称

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		isHidden
		lineageTag: 4d0633e8-86fa-42c9-be0d-c24649b98027
		summarizeBy: sum
		sourceColumn: 金额

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税额
		dataType: double
		isHidden
		lineageTag: 8f5943fc-e400-49f9-ab36-c2006ad32e4c
		summarizeBy: sum
		sourceColumn: 税额

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 合同编号
		dataType: string
		isHidden
		lineageTag: 24e7cb7e-d15c-4e94-90f0-a8bd5ea588ab
		summarizeBy: none
		sourceColumn: 合同编号

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 补充协议号
		dataType: string
		isHidden
		lineageTag: 6152c7f9-9dcf-4311-8789-69f20c998865
		summarizeBy: none
		sourceColumn: 补充协议号

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 签约方式
		dataType: string
		lineageTag: 75d66387-2e05-4f34-953e-66b2e5855d77
		summarizeBy: none
		sourceColumn: 签约方式

		annotation SummarizationSetBy = Automatic

	partition F_下游合同评审 = m
		mode: import
		queryGroup: 下游合同\合同组\合同评审
		source =
				let
				    源 = Table.Combine({#"DW_FB_HTPCMX（分包合同评审）", #"DW_WZ_HTPCMX（物资合同评审）"}),
				    #"合并的查询（参照完整性）" = Table.NestedJoin(源, {"KEYID"}, D_下游合同_参照完整, {"KEYID"}, "D_下游合同", JoinKind.Inner),
				    #"展开的“D_下游合同”" = Table.ExpandTableColumn(#"合并的查询（参照完整性）", "D_下游合同", {"项目名称", "客商名称"}, {"项目名称", "客商名称"})
				in
				    #"展开的“D_下游合同”"

	changedProperty = IsHidden

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = 导航

