table 货币单位
	excludeFromModelRefresh
	lineageTag: a8470b2f-3a25-4be4-96da-23268e5484c1

	column 货币单位
		dataType: string
		lineageTag: 53573b47-873a-4573-b4b6-72547ebace6a
		summarizeBy: none
		sourceColumn: 货币单位

		annotation SummarizationSetBy = Automatic

	column 系数
		dataType: int64
		formatString: 0
		lineageTag: 4816a77c-c0ea-48ec-863a-b8ca374d68d5
		summarizeBy: sum
		sourceColumn: 系数

		annotation SummarizationSetBy = Automatic

	partition 货币单位 = m
		mode: import
		queryGroup: 维度表
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WetrarKSjZKgUqxOt9GRHO4htAAQQ/q79MD5ELBYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [货币单位 = _t, 系数 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"系数", Int32.Type}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

