DEFINE
	VAR __DS0FilterTable = 
		FILTER(
			KEEPFILTERS(VALUES('D_项目信息'[项目名称])),
			NOT('D_项目信息'[项目名称] IN {BLANK()})
		)

	VAR __DS0FilterTable2 = 
		TREATAS({"元"}, '货币单位'[货币单位])

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			'D_日历'[年月名称], 
			__DS0FilterTable,
			__DS0FilterTable2,
			"度量值", '指标'[度量值]
		)

	

EVALUATE
	__DS0Core
