table 货币单位
	excludeFromModelRefresh
	lineageTag: d05b5466-2363-4a14-b388-5710661f87b7

	column 货币单位
		dataType: string
		lineageTag: 3423208d-5adb-448e-9c4c-3b56b8ba6fb7
		summarizeBy: none
		sourceColumn: 货币单位

		annotation SummarizationSetBy = Automatic

	column 系数
		dataType: int64
		formatString: 0
		lineageTag: 8516a6db-3a58-418e-91b3-9a45de07d7e9
		summarizeBy: sum
		sourceColumn: 系数

		annotation SummarizationSetBy = Automatic

	partition 货币单位 = m
		mode: import
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WetrarKSjZKgUqxOt9GRHO4htAAQQ/q79MD5ELBYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [货币单位 = _t, 系数 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"系数", Int32.Type}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

