table 开发费用
	lineageTag: 2c84abc1-71e8-4340-b761-6e6592ff6788

	measure 开发费用 = SUM('开发费用'[开发费用（万元）])
		formatString: #,0.00
		lineageTag: 6d49b85c-fd84-43ea-9c4b-a8ef0b27dc45

	measure 修改数量 = SUM('开发费用'[修改功能数量])
		formatString: 0
		lineageTag: 3b8d940d-fbb1-4e6d-9de1-5822c8fa9e6d

	measure 扩展数量 = SUM('开发费用'[扩展功能数量])
		formatString: 0
		lineageTag: a3bd5511-cbfd-4d94-bcfb-a252f41c621c

	measure 部门轴最大值 = MAXX(VALUES('开发费用'[所属业务部门]),[开发费用])*2.2
		lineageTag: b026bc7a-a3d1-4559-9425-c190aad3b251

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 部门轴最小值 = MAXX(VALUES('开发费用'[所属业务部门]),[修改数量])*(-2)
		formatString: 0
		lineageTag: 39935a5d-41a5-4b7a-ab9e-3459b8394582

	measure 年度费用标题 = SELECTEDVALUE('开发费用'[所属业务部门]) & "各年度开发费用"
		lineageTag: 3543de93-fcb2-4798-80f3-adec806ac253

	measure 年度数量标题 = SELECTEDVALUE('开发费用'[所属业务部门]) & "各年度修改、扩展数量"
		lineageTag: 4204a0d9-8bd0-4302-9fb0-6f5bcf5d1da2

	measure 年度轴最大值 = MAXX(VALUES('开发费用'[年度]),[开发费用])*2.2
		lineageTag: ec55a0b6-0d42-4d16-920c-566b88d8c4dd

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 年度轴最小值 = MAXX(VALUES('开发费用'[年度]),[修改数量])*(-1.2)
		formatString: 0
		lineageTag: dd9ca547-845e-49da-a7a0-153a5d20aef5

	column 年度
		dataType: string
		lineageTag: c2322843-519a-49c9-8d11-e7f92e6dcdc9
		summarizeBy: none
		sourceColumn: 年度

		annotation SummarizationSetBy = Automatic

	column 所属业务部门
		dataType: string
		lineageTag: c278c296-9e1f-464b-a06d-028d4822d07e
		summarizeBy: none
		sourceColumn: 所属业务部门

		annotation SummarizationSetBy = Automatic

	column 业务内容
		dataType: string
		lineageTag: a7bc8b62-810b-4292-8200-01bf7b7ed834
		summarizeBy: none
		sourceColumn: 业务内容

		annotation SummarizationSetBy = Automatic

	column 经济效益
		dataType: string
		lineageTag: e1ee4bea-269b-4572-80cf-1bd5b3359406
		summarizeBy: none
		sourceColumn: 经济效益

		annotation SummarizationSetBy = Automatic

	column 所用人天（天）
		dataType: double
		lineageTag: 594c2a76-53a0-4612-ba18-756dafa5bbb2
		summarizeBy: sum
		sourceColumn: 所用人天（天）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 开发费用（万元）
		dataType: double
		formatString: #,0.00
		lineageTag: 5eb8cf6f-74c6-4257-867d-db84e6c34af7
		summarizeBy: sum
		sourceColumn: 开发费用（万元）

		annotation SummarizationSetBy = Automatic

	column 扩展功能数量
		dataType: double
		lineageTag: 3995e299-ebcf-4f90-8e23-654b9a0d9b8c
		summarizeBy: sum
		sourceColumn: 扩展功能数量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 修改功能数量
		dataType: int64
		formatString: 0
		lineageTag: d63315ed-a169-4dfa-a85a-d431db2ce36b
		summarizeBy: sum
		sourceColumn: 修改功能数量

		annotation SummarizationSetBy = Automatic

	partition 开发费用 = m
		mode: import
		source =
				let
				    源 = Excel.Workbook(File.Contents("C:\Users\jiahe\Downloads\各部门研发费用数据统计3 (1).xlsx"), null, true),
				    筛选的行 = Table.SelectRows(源, each ([Kind] = "Sheet") and ([Item] <> "汇总")),
				    删除的其他列 = Table.SelectColumns(筛选的行,{"Name", "Data"}),
				    #"展开的“Data”" = Table.ExpandTableColumn(删除的其他列, "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7"}),
				    提升的标题 = Table.PromoteHeaders(#"展开的“Data”", [PromoteAllScalars=true]),
				    筛选的行1 = Table.SelectRows(提升的标题, each ([所属业务部门] <> "所属业务部门")),
				    重命名的列 = Table.RenameColumns(筛选的行1,{{"2021", "年度"}}),
				    更改的类型 = Table.TransformColumnTypes(重命名的列,{{"所属业务部门", type text}, {"业务内容", type text}, {"经济效益", type text}, {"所用人天（天）", type number}, {"开发费用（万元）", type number}, {"扩展功能数量", type number}, {"修改功能数量", Int64.Type}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

