table 收入成本分析
	lineageTag: 0fc6b601-862d-4984-b96f-42d01785b7c0

	column 项目名称
		dataType: string
		lineageTag: 8ceb7e27-c097-4ebc-a3a1-0c8368e0d2e7
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		lineageTag: cd8bd056-7cc4-4e52-a4a9-5d03e12bfb4f
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 责任体
		dataType: string
		lineageTag: 3c8cea2d-d605-45ba-99ee-ba3708cfce15
		summarizeBy: none
		sourceColumn: 责任体

		annotation SummarizationSetBy = Automatic

	column 项目性质
		dataType: string
		lineageTag: 0eb7c48a-4de1-4776-afcf-2a6c21d8d748
		summarizeBy: none
		sourceColumn: 项目性质

		annotation SummarizationSetBy = Automatic

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"收入成本分析","TableItemName":"项目性质 (组)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column 工程类别[一级]
		dataType: string
		lineageTag: 6ec7bf24-db0b-44cc-a65b-7c5bb96cb00d
		summarizeBy: none
		sourceColumn: 工程类别[一级]

		annotation SummarizationSetBy = Automatic

	column 工程类别[二级]
		dataType: string
		lineageTag: f690e473-35e4-42d5-b481-7b9f1289c1ca
		summarizeBy: none
		sourceColumn: 工程类别[二级]

		annotation SummarizationSetBy = Automatic

	column 建筑面积
		dataType: double
		lineageTag: aa99a92d-09be-4cfb-88d5-41c6f799cb55
		summarizeBy: sum
		sourceColumn: 建筑面积

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 累计合同额
		dataType: double
		lineageTag: c0517ff4-a2ed-48a6-81a7-782f5426d809
		summarizeBy: sum
		sourceColumn: 累计合同额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 累计自施收入
		dataType: double
		lineageTag: ab3276dd-df78-4409-bcd8-7ff582bf5a04
		summarizeBy: sum
		sourceColumn: 累计自施收入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 累计目标成本
		dataType: double
		lineageTag: dc7f506e-7d15-41bf-901b-0c0219262b93
		summarizeBy: sum
		sourceColumn: 累计目标成本

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 临设费收入（累计）
		dataType: double
		lineageTag: 30c93373-6f8d-490d-a15e-303d1a657dc6
		summarizeBy: sum
		sourceColumn: 临设费收入（累计）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 临设费目标成本（累计）
		dataType: double
		lineageTag: 46f28c20-daa3-4da4-a43f-e335d7dc0632
		summarizeBy: sum
		sourceColumn: 临设费目标成本（累计）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 临设费收入（累计）单方造价
		dataType: double
		lineageTag: 7cb9260b-29f0-4971-9e15-23b8e668d031
		summarizeBy: sum
		sourceColumn: 临设费收入（累计）单方造价

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 临设费成本（累计）单方造价
		dataType: double
		lineageTag: 538dc844-caa3-4dfc-b58d-4839ea0b65a9
		summarizeBy: sum
		sourceColumn: 临设费成本（累计）单方造价

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 临建标准
		dataType: double
		lineageTag: a911d76f-f6c8-4f97-b5b2-ca325bd7d3c1
		summarizeBy: sum
		sourceColumn: 临建标准

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 临建占比
		dataType: double
		lineageTag: 15cfba16-d1b5-47d7-8b78-88f1f97900ae
		summarizeBy: sum
		sourceColumn: 临建占比

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 投标管理部门
		dataType: string
		lineageTag: d233a2b1-6bb2-4b34-8593-2aafb87845a6
		summarizeBy: none
		sourceColumn: 投标管理部门

		annotation SummarizationSetBy = Automatic

	column 项目全径
		dataType: string
		lineageTag: 323609f9-63c8-4317-9cfa-ec848adc3e76
		summarizeBy: none
		sourceColumn: 项目全径

		annotation SummarizationSetBy = Automatic

	column '项目性质 (组)' =
			SWITCH(
				TRUE,
				ISBLANK('收入成本分析'[项目性质]),
				"(空白)",
				'收入成本分析'[项目性质] IN {"工业厂房"},
				"工业厂房",
				'收入成本分析'[项目性质] IN {"公共建筑"},
				"公共建筑",
				'收入成本分析'[项目性质] IN {"基础设施",
					"其他",
					"其他专业类施工（装修、改造、土方、桩基等）"},
				"其它",
				'收入成本分析'[项目性质] IN {"住宅"},
				"住宅",
				'收入成本分析'[项目性质]
			)
		dataType: string
		lineageTag: dc01e1c8-38ea-4b86-a482-720528ef147f
		summarizeBy: none
		isDataTypeInferred

		extendedProperty GroupingMetadata =
				{
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "收入成本分析"
				          }
				        },
				        "Property": "项目性质"
				      }
				    }
				  ],
				  "version": 0
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"收","Entity":"收入成本分析"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"收"}},"Property":"项目性质"}}],"GroupItems":[{"DisplayName":"(空白)","BlankDefaultPlaceholder":true},{"DisplayName":"工业厂房","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"收"}},"Property":"项目性质"}}],"Values":[[{"Literal":{"Value":"'工业厂房'"}}]]}}},{"DisplayName":"公共建筑","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"收"}},"Property":"项目性质"}}],"Values":[[{"Literal":{"Value":"'公共建筑'"}}]]}}},{"DisplayName":"其它","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"收"}},"Property":"项目性质"}}],"Values":[[{"Literal":{"Value":"'基础设施'"}}],[{"Literal":{"Value":"'其他'"}}],[{"Literal":{"Value":"'其他专业类施工（装修、改造、土方、桩基等）'"}}]]}}},{"DisplayName":"住宅","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"收"}},"Property":"项目性质"}}],"Values":[[{"Literal":{"Value":"'住宅'"}}]]}}}]}

		annotation SummarizationSetBy = Automatic

	partition 收入成本分析 = m
		mode: import
		queryGroup: 成本分析
		source =
				let
				    源 = Table.Combine({初始目标成本, 调整目标成本}),
				    #"已添加条件列（临设费收入（累计）单方造价）" = Table.AddColumn(源, "临设费收入（累计）单方造价", each if [建筑面积] = 0 then 0 else Number.Round([#"临设费收入（累计）"]/[建筑面积],2),type number),
				    #"已添加条件列（临设费成本（累计）单方造价）" = Table.AddColumn(#"已添加条件列（临设费收入（累计）单方造价）", "临设费成本（累计）单方造价", each if [建筑面积] = 0 then 0 else Number.Round([#"临设费目标成本（累计）"]/[建筑面积],2),type number),
				    #"添加的条件列（合同额临建标准）" = Table.AddColumn(#"已添加条件列（临设费成本（累计）单方造价）", "合同额临建标准", each if [累计自施收入] > 10000000000 then 0.004 else if [累计自施收入] >= 5000000000 then 0.005 else if [累计自施收入] >= 3000000000 then 0.006 else if [累计自施收入] >= 2000000000 then 0.008 else if [累计自施收入] >= 1500000000 then 0.01 else if [累计自施收入] >= 1000000000 then 0.011 else if [累计自施收入] >= 800000000 then 0.012 else if [累计自施收入] >= 500000000 then 0.013 else if [累计自施收入] >= 300000000 then 0.015 else 0, type number),
				    #"添加的条件列（建筑面积临建标准）" = Table.AddColumn(#"添加的条件列（合同额临建标准）", "建筑面积临建标准", each if [建筑面积] > 3000000 then 0.004 else if [建筑面积] >= 2000000 then 0.005 else if [建筑面积] >= 1500000 then 0.006 else if [建筑面积] >= 1000000 then 0.008 else if [建筑面积] >= 750000 then 0.01 else if [建筑面积] >= 500000 then 0.011 else if [建筑面积] >= 400000 then 0.012 else if [建筑面积] >= 250000 then 0.013 else if [建筑面积] >= 150000 then 0.015 else 0, type number),
				    #"已添加自定义（临建标准）" = Table.AddColumn(#"添加的条件列（建筑面积临建标准）", "临建标准", each List.Max({[合同额临建标准],[建筑面积临建标准]}),type number),
				    #"替换的值（临建标准为0，固定450万）" = Table.ReplaceValue(#"已添加自定义（临建标准）",0,4500000,Replacer.ReplaceValue,{"临建标准"}),
				    #"已添加自定义（临建占比）" = Table.AddColumn(#"替换的值（临建标准为0，固定450万）", "临建占比", each Number.Round([#"临设费目标成本（累计）"]/[累计目标成本],4),type number),
				    删除的列1 = Table.RemoveColumns(#"已添加自定义（临建占比）",{"合同额临建标准", "建筑面积临建标准", "FID"}),
				    #"合并的查询（取营销管理中心的项目）" = Table.NestedJoin(删除的列1, {"项目编码"}, 项目信息, {"项目编码"}, "项目信息", JoinKind.LeftOuter),
				    #"展开的“项目信息”" = Table.ExpandTableColumn(#"合并的查询（取营销管理中心的项目）", "项目信息", {"工程类别[二级]", "工程类别[一级]", "投标管理部门", "项目性质", "责任体"}, {"工程类别[二级]", "工程类别[一级]", "投标管理部门", "项目性质", "责任体"}),
				    筛选的行 = Table.SelectRows(#"展开的“项目信息”", each ([投标管理部门] <> null)),
				    已添加自定义 = Table.AddColumn(筛选的行, "项目全径", each [项目名称]&" （"&[责任体]&"）",type text),
				    重排序的列 = Table.ReorderColumns(已添加自定义,{"项目名称", "项目编码", "责任体", "项目性质", "工程类别[一级]", "工程类别[二级]", "建筑面积", "累计合同额", "累计自施收入", "累计目标成本", "临设费收入（累计）", "临设费目标成本（累计）", "临设费收入（累计）单方造价", "临设费成本（累计）单方造价", "临建标准", "临建占比", "投标管理部门"})
				in
				    重排序的列

	annotation PBI_ResultType = Table

