table 160应结未结
	lineageTag: 43b11aff-9342-4faf-a2c4-12ab1e1f204c

	measure 'cnt.合同数.160' = DISTINCTCOUNT('160应结未结'[合同号])
		lineageTag: 38f5b95e-4636-44a4-8ce1-d4ed06991ef1

		formatStringDefinition = "共：0份"

	measure 'cnt.合同数.未结.160' = CALCULATE([cnt.合同数.160],'160应结未结'[结算状态]="未结")
		lineageTag: d4b5277b-b78e-4e0a-8b22-f50a932a6d43

		formatStringDefinition = "未结：0份"

	measure 'R.未结率.160' = DIVIDE([cnt.合同数.未结.160],[cnt.合同数.160])
		lineageTag: 620002e7-c276-40f8-bf44-2883fa0fcef0

		formatStringDefinition = "0.00%;-0.00%;0.00%"

	column 股份公司四级单位
		dataType: string
		lineageTag: a42d4296-f8ff-4dd6-99b9-ccaa1c6a76dd
		summarizeBy: none
		sourceColumn: 股份公司四级单位

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 29da1aa7-434d-4600-9597-b5dfbc986088
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 分供商单位名称
		dataType: string
		lineageTag: ebced4e7-8f39-4bdb-bd45-6e595af43194
		summarizeBy: none
		sourceColumn: 分供商单位名称

		annotation SummarizationSetBy = Automatic

	column 分供商专业类别
		dataType: string
		lineageTag: cac89b56-7448-4c68-82ad-b53ef1423f53
		summarizeBy: none
		sourceColumn: 分供商专业类别

		annotation SummarizationSetBy = Automatic

	column 合同号
		dataType: string
		lineageTag: f022f95c-9998-43a8-a074-9417d2f686c4
		summarizeBy: none
		sourceColumn: 合同号

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: cee6ae82-d594-4960-82da-bcaf123b647b
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KEYID
		dataType: string
		lineageTag: 099de8b6-9910-4023-b721-48fb8536b980
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 73387f68-bedb-4185-b940-cf93b6f8c7f6
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 合同名称
		dataType: string
		lineageTag: 28414051-b172-454c-8133-80dbad3684c4
		summarizeBy: none
		sourceColumn: 合同名称

		annotation SummarizationSetBy = Automatic

	column 客商名称
		dataType: string
		lineageTag: 6be79b1f-4846-4d19-a3ea-a36c233cfbd5
		summarizeBy: none
		sourceColumn: 客商名称

		annotation SummarizationSetBy = Automatic

	column 结算状态
		dataType: string
		lineageTag: d5f53999-8e3f-4345-b2f0-ab3121ed0198
		summarizeBy: none
		sourceColumn: 结算状态

		annotation SummarizationSetBy = Automatic

	partition 160应结未结 = m
		mode: import
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("zV3ZcuJIFv2Xeu6KALyU/dgz0zP90B0zETMPHdXR/wKmMItZDWYTGGMbG7ywGDAg", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"股份公司#(lf)四级单位" = _t, 项目名称 = _t, 分供商单位名称 = _t, 分供商专业类别 = _t, 合同号 = _t]),
				    合并的查询1 = Table.NestedJoin(源, {"合同号"}, D_下游合同, {"合同编号"}, "D_下游合同", JoinKind.LeftOuter),
				    #"展开的“D_下游合同”" = Table.ExpandTableColumn(合并的查询1, "D_下游合同", {"KEYID", "合同编号", "合同名称", "客商名称"}, {"KEYID", "合同编号", "合同名称", "客商名称"}),
				    合并的查询 = Table.NestedJoin(#"展开的“D_下游合同”", {"KEYID"}, F_下游合同结算, {"KEYID"}, "F_下游合同结算", JoinKind.LeftOuter),
				    #"展开的“F_下游合同结算”" = Table.ExpandTableColumn(合并的查询, "F_下游合同结算", {"价税合计"}, {"价税合计"}),
				    已添加条件列 = Table.AddColumn(#"展开的“F_下游合同结算”", "结算状态", each if [价税合计] = null then "未结" else "已结",type text)
				in
				    已添加条件列

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

