table 963应结未结
	lineageTag: 33ffa6c0-649e-431e-8c87-0f22f4cb3dbb

	measure 'cnt.合同数.963' = DISTINCTCOUNT('963应结未结'[合同编号])
		formatString: 0
		lineageTag: 29717ed0-1e6e-4582-84df-ae64dc7d9c15

	measure 'cnt.合同数.未结.963' = CALCULATE([cnt.合同数.963],'963应结未结'[结算状态]="未结")
		formatString: 0
		lineageTag: 08788217-1125-4938-bce9-f8ff0d5a7a89

	measure 'R.未结率.963' = DIVIDE([cnt.合同数.未结.963],[cnt.合同数.963])
		lineageTag: c2bc0c13-e6a2-494c-b68b-0aca0958bd95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 责任体
		dataType: string
		lineageTag: c9c03817-e3a9-47b2-9452-675e4b721e61
		summarizeBy: none
		sourceColumn: 责任体

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 2fd61fb9-f00e-4f71-97f5-09422f5eed50
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: b2fd20a0-a1de-4ae3-9148-de2bee25eecd
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 结算状态
		dataType: string
		lineageTag: 796b841b-ef4c-4560-892d-6925f480b0ac
		summarizeBy: none
		sourceColumn: 结算状态

		annotation SummarizationSetBy = Automatic

	column 合同名称
		dataType: string
		lineageTag: 63c7fbea-2733-4e91-b4c3-fc9c870f5430
		summarizeBy: none
		sourceColumn: 合同名称

		annotation SummarizationSetBy = Automatic

	column 客商名称
		dataType: string
		lineageTag: 5856803e-b0ea-49fd-8796-d69a18c14f6f
		summarizeBy: none
		sourceColumn: 客商名称

		annotation SummarizationSetBy = Automatic

	column KEYID
		dataType: string
		lineageTag: 2c48afda-1c04-496c-9b71-57dca3bd782f
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: 61ca98e4-c556-46c4-9d91-850c6d007ff9
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 963应结未结 = m
		mode: import
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vZ1bbxw3soD/S/blHGAFTF/m9pjN5mSxyMEG2ADr48W+79s+7B+QrOhqXWNZF89II8WSZa+tuxyNRhoLOH/lDLt7nvYvHPZlptnNJruHrGogMBLF+opNFotFslj1179+5X76RFqtQe/loPtmOPv+q99+5Z08kfOl4e6at3Qx6C75/7c7S1Z69Idu/9xZfKJ/5w8/Tv3X777789TXjZoxZVZMY6pSqVhf/e23WsBn/50ENoCBRhUa2AQGmgY00AQEmv6gQLYwANahgZBq4wONCjQQug8NGxoIOVMCYA0YCDpTAiCk+bKgZ0oAhJzLFrTFDoCQahMAIdXGgp56ARByUGzoUbahDawNbWAD4HgZHXSnWSDZWPRenJBW3+t/cLYv3Y975P520Ds1K9/95e/k+HTwuOMcLpCFeXfrs7d8weKbTXs8s+uoeNtCwyc1FqX1FeDO+eM3I9ejYaI23MLt9gryqNZwRxW372M7j4NvoOIN3M6JnTEcPG7fG8i2uIKLx5u1AR53aE3coTVxbY6FO7QW8nKCO7QWrkmzcfvextWcKm7rq3iaE3gKeJpj4a61FoL/l8bj6b2Fu3OwcD0FC9dTsHA9BVvmYzpXHe/lOplb9J5aZPk9WW5RjnN1SCXQv0NWtodH927r/N+Pi4PeitPu/PtxiRKoROf8c0KW3chdeBFkGSKVRZAlNE0IsizRXEGQZWP2YYEtJvAn+bLsMoeqRFk10eKLoe6ixQZhvITLMoIss0Q9LMsUBrJKMoVGiebJkB3ZIeh8WXpoytwhjGWyRLsh9MMwZJWoG8JTQAxZJdnewM6X6UKVqPM10Vk8hiyRzg+6y87nO3L8gVzfuL/cULh7NEdWl8nF46D/ytnfcLb3EsyamWsfJmEWcL80mihUUw2mcMlUZFoyM6HBrIjMgc63i6aiTjsRmMLlRIcJrJ9St1KHiTDuwvsrHSbwt0uvknSYCDZEeFajw0T4duHphQ4TYtlI2yWEtUN4+6PDRBgjYUCCBtMSuSY6TIQxEl7b6zARxshCsMkW8Lgno8wAmcDjLo2n0GECj7v0PkSHCWw/pXcHikw71qVBt01WdsjiPJn7RNa79C+T8yXype8tt537bffNNlndISsP5OzdcO8X8vjS7fxKrq7oT+h/suQ6czAhIjvXi8PdG+fmkvTuBvcvyfmv9CekdZbk1FPaTlbX0i08PiUbK4PumTez5T48eUvX9CfO60tn9Tzag3V6pH3JYhu2lXIYoLFmU4B1rm/8nzz0nOXXw9ZPtHv/9264sEl712n/y9k/IZ21cMNIx9YfYbpnTGwV/cj7plEd+49YcgL9COUwvgW6HFM0ytByaiXJKanfrJL6LfIL8OVUy5FjlySnapUkR2TOoOWUpNfVkuxbdBWGKofxhdDlGCJ7MNz/mVy36MJL5qgE8vaerN8l1rB6LbXnz2hrf5XsLzvTR/5h5/UXcjFPWi2n3TF+Y/6GrL1wFp+cds/dSratMu7ritCGaHKx2itaKwb3K2Tuklx0SHeWPH10ll46ez1vtj/obUaOQveMPM0mlm4z/WgOHCvqhQmxQSfEWKEDoIkVzW91LBNGDI0Vzio9rNDpUcfaCQXznW/WtQ2CgFjPm7r41PP27yXanYy50KilvHlYponArCIwawjMOgKzAc80gMfdlurS7hKZu3W6F2Sl5zy8p3taX8+Pz8n9E2n3omUwuEz79odvEnDLHptBVLhwZmnC5VMMAi7UYQC4IZzIEHAbEy40FxBw4RzXhFtS4wkBx9JzS2qiAzjpvnC2F8jKtrfUc9oX/EpXb8ZP3eU9PAnKqsChhL23ujPoffLmvnjnF+H/pQu6d37knu9kHCoZY7NjCCevApAJ5IEDmkJtVAVC9iFzqQMDtKTmWhUI+cnMKwU4oNgUr+4Mp984Vx1qEIa7T8OFlTFQuHOpNPJX1cmw4fYtxjZRsGKPSA8rmUE6WJy+hdKENFZi6HSwwmVCCyuzUTpYnL41hbsDLax43dTD4swy2dKsg8UZMkuyZulgcWaZhWNvbRxNsHHsrQ0/ZPKjEj0s/HQwcxwPHSy8BTNxlkj5vlUZmzw88a/k2TPDbttbO/jTDz/8KdyYOfdfWFzyRCa8TW7yhyY60PAqIoaaGNC6CNpv+REJ3ReBN/sm3Ir62WlWeqmtaL1hZdyiA9DiXZUuzZSNib/XvjsYPO2TxQ9+yp25WapCCUi9kdtdE0EaAgjV4eHOe//n65uk1SJnbxMEJtrVEhHurkj7xg+5OHtHO2TQ7TuHR7RbEhzb4t3ObM7ckrO7Rn99uLDpHax6RzvJ9li5kyji7C7R3iCv58nyUcZO347vXGr6HKtA/xTh2MnLmiyON7PlzN6QxZb/Avh001meJq0z9+GRbCxmTbp0WjNh85ZW6RQePB05MxfOwS9ur5/RSCs+phZNOiWakTMEE9JE80WJZoos4Gg4VgbdN3QUnPZFGFnlvt4bPOw5twcZs6A5ngWmfDh4LP3T3er4f+3ilfNynjwkydX8gXbXD/0Is3CmB2d9yZkVX8CJhqMQgTm18M1j6usWN4azffpncF/W8+5uvPtP/vX56o53d9Ek63dUrem3+fPk1cygv07O58ZX5067kzjUYG4ijZLlVUuWVy9Xnlni+DE+bHnySvw+5oVQefLk+uL9fO0v+/fH1KOhC+xw5hVZPnCPv9AWhCvJoP8qaV3qKW9L+CXdD5RMOb/7/keWUK2lY0pFBN8Yt/r0e4dvD5zLTX9NO+55K7NR3GbrLLyaSHx41S6ouJpw+axXhzO7QyS4qOW+x3e3T8nDvbnQp/DOv9B9zBj7NWlfkv2xDxbkjub2HPBcUWeQx0P/lnr9bXjw7UxPO/sn7uYBWdmRxFXUmXtrkaUZLqyS3jyF+HHNlLPXc96eOwc75HJ9+Hph3G6q2v8RTr3/TLn9jWY6sBdXSLRTwRMiNZSgQkTaCSpEZBJBhTTKEIKtXUw4ALKQMgbeEK29oELK0C6jDO0yytAuU7RuQAmxZIsIqBDs9US6nQIVgj1PpI4plBDmZCh4Y7XEJ1Bz9n71XdzeCll74f+zfETWl4dzq+RkJ3Stv7crpN0Z77Cf/eH5s6mvm9V6qqd4vvuwSuZu/WdHyxfD1jz13PxMbHcXI86P/xNNgCqb+FERwb7IVEDYU0bDFnVUYUSNfVuuhqg2VVsRDEs9fqYpz29OFj84ux3vaGU49zPp7XAdatc1q4KEDWJyzNc0M7gngEwcNxxQt3gCB4zTsQIAk+95oYCQfci8QgIEQn+yDamHARBypiQzyUIBNasx8EDImRIAoWdKFVptqtBqE6dhggJCj3INepRrkKPs+zZ1Yc7l+6dBtx3eRZO7W/pP5o20c33j9DboP6TjHzhS0dSXCt0efkW0hYluEYSJk8Xtn5G7A//ioXc3/LjrfrwIeu6aOoXk1Qz13dzeL+R4e/B46PzUoa6Cu7TgHm6R9c3/m54ZJ/JKdKfdHC3RVXmu3eHjWvDy/pIcvHR2v7jHvchPDJpBvRFythE+zXe3On57mMjL0dDFz8pB8/qOuo5+RRM2hTs7KDWhBqiRA5ctTnUsTDgHhEduPfCApvA2aJJsvvWgBWp4PGgObh4PrPIMnrmkQMPjdQ5zDImFh02vzuNBqxbweLxpFVh5XMUU5t8CwuNZTGlWQxi8MJkWEB63c4TpsGDwsLVGeDxoCR8ej9v3sJVSeDxotQ5uMRTngg8SUwy6l86v79yHdefzGnmc9oN3VnphHgrqrXpH753LW/8gdHQKSr1Y92jaO//ibPfTzqZhCTPBwQurNBCz94/EGFMVS7irghOTPrJFEkNHyBRuNGA7TZjGDbTTbMTiA8zXmE283NcJMXipwyOzEGZvo5PHEObVBJblW7gGpjKkZCFWKeFk1Ur8rhpeSnROVh1zVqVllThe9RL7sFmibpRlN6gsA7GUAi+rPN0whJt6DFlljhem95LWw/Lml4FYqYzvwzJllaiHwlzlCLLM8r6r0ijRzjdKXCsb5dmNSrNMO1+iPayUZw8N1E1QWlaZtrdM3cArtZWQxYRmlyJLeNKMIEt47Iwhq6S1MhmhhC9LeHyMIatEnRfWRMDYm5d45iC8A8SQVaJvg1hdlpdV4h4WseQbf5ZSom4glpfjZZWoG7US57Iw0ATD7y3PnzcAaq5FzLjeh9A+KDKDm1n9+ikc0wL+dun1uk479WuycEzhxZUOE7idzEtLWKZ+zSCeqV/XietP6LlpyvYXOjqP0E6AGmG8fkLVIQrJda54NgY5ynVx/+Qn+OHy/Tird+TnlTDXBfvCOuI0x/opTAM/USki5lmM1RSVGJiQGEa8WqNLQWHSfnUsc58EjW2KagGoY/3RquNU3IlmRFyZpFmSnBpORZeEHGMKrdIKLwekvEbi3l2kn0pEJphDmxh8epx6xQJqaApbFdVK0sPWQAqWJLDBKbh+xYKICVr9gmfqV+ngmcKcgxpM/YoaPFO/UgXHFKdx1GDqV/7gmcI0qepME7C6QwTHqaiRgDP7PIW0+yM3KrYnkizPRdKdZ0R0abOCt8GaufGzFw4AlmZVgcSbdKC+91lNoHb5MaDiiaHAAtIJnwU1jgEL8BstoHG0pgxmW6PKCjzvcQkHQ7dAQgLo72dkScbVgOAt1KxawQFl2bSVgFXNUiI8ULNqBQesgaTkToQVg2Q6j9ZC6JTkPBYkvzWPBerWNBanb6sgWeR5LE7fVkEy9PNYkDoYHLYGUgKCx+L0bR1HE+og6d4T2OTZGCi2AT95mQg0cKw88f9wYZNcHdCdEowRD0+xnc/v6M/95/tMYoXkMS7jNoksd2FW8MXVynhDJ1JSZaBoZFSAlmzjpgoUeiYhcNBdcE836YD779yCTOiksxZmheC3xo1qnOJf/uHKWGHlgOLFDUZHl81UAIykgABZ65D76+Hse/90gOr8Ss//98V5Z+uJ9NrOzqm79GHQfTN4Oncfz52t++H0Ia/5DVGWb0lRAFbba8Js9YJ6ANFWPb6Ry0uzLsh3z+atqMpT3csztWfkDtED+fuduk7u+KiLrIwjHRAaaNssoQIo0XKKOhSnWfFFNxQNbBSs+PEZAM1OeMrZNGotguzJ9E9qEpydw+GbtvvLqtNe5aZVuN7WxtNTVMhkoroFowO6sc2sytWmeN2CiFyNc9EJu+K+5ecUDyyS3xWdNW/5inoKCU4jo1BcweoFiffGkxZPGJnF+DNwSwOwD3AtwGTno8UxPtQV5YGdNAV3onuFecg1oHVRImwtqChRqTrUqFTgW2qYTWioPWXY4oTxE0PD6Tm2eA2o1O48GSEVL5v4ACOfcDTtmNTxKB+REmIg5BPmhSBkq04IYTwsZCEIKbE5IRZCLnReSBljYiMk9+aFYE9GZi+HLAQhJXZCiBUfRiILwZ4n6Vw3E2SLfv78+fdTbLZoQzN3aAhkUh9XNPOvJoDJUFIgoKGZf5UHgiYji4aISWMHmqmNx4Pm2+LxoMnIeDxy34Om8+LxoPm2OLzwhT0QHrfvhW/2gfB4zwEjWcxzW7ynUbwsvFQinCzElBu8rBL7EDH1Cy8L78kXLwvvmWNCljnFVmnAlyV8il38GUfEBH3CwjP1n7AkmEBPl/h2ivREh6n/dIln6j/X45hCm6bDRBgjoY3SYQpv/iePj43gTPCtMCZIEy4PQZ/kuj7CxqEQOdWsC14fhFjm+gCj/lO0LWHO0OT7nMxCQKMSxuMSlIZ8O5cPSTrpOhB5gZmCEJDPUaiwxEPk29pikJytbEGI5hFAVHgMrpxSAlhAfxSA0C00NIvE8EDNUw8OaGrWFuKBmjVdeKBmBakE0AI4OUoA7XyLqgCE7EM730gqAPF2yaEsxotHTDzEyUJM0JOQZUxJ0p4jfBdi8kG+D0vSDUO2I0GQhZiwjJOFmACLl1WSHqaLjyruTiImaIKSBJOpKQv9lDuSEz/ltkqSY+M8TU/IYXbJ+HLMkuSInrEDyrHieQGyCY7g8Q7bANxhJ+DMeZ7C89Zox9GM3W95J0yEEsYZFw9eHg3SeNNbEQVeSqKKo5bVG+ORFgXjTgTJCU8VRBdHHDvtuepzciKMC3OgvisnDLUoxwBqj5ETsluYUwXi5AT9FuaoRbnzHHmgrzez5czehLG+7ummszxNWmfuwyPZWMyasHHQgVy9lbE6IdPRt8fB4UbOHJyQphPrz9N0wrkTtCJWazJaXr9drrtXN6TVH+7NOdMPoUcYj2a1wS+9Ome5oxVofJab03UqWGaNzAgQbbXI3X74vaFKe+dfvPOj8eHw16R9SfYTp30NZm0ThUBpcJmFGJ6L1V6EI/hISBzUpnLc/Px5GEqf7lmdeKVnydNP/QCoZ6DnszwQ/JM1D9p4oOZBGw/Uj5tLATWPpHmg/NpjcqCheSTNA6EVGyA68lniSNqAVGwrET0CBYRUbCv/BlEBCKnYdiJSBQqoH7KaBJZV1iB4oV5iyQth/AZGyYsSyxqUVbLJSEwHfFlmSSUUAlllluYrs2RTqBv6SXwjRzEmMxsc1DSrDZyz0vB7GDmVsuTgnM3zckTJR6HliHKnQsuR581QzkchSuiiiRU+ZZ1oIznKyRVnugi5Y9nBQ81Pzw0zTH/pZ2heexf+X3J34r5/ye4Vq9wmKmyW27r1Nk7GNB9y9o6aG//PwCJ863sNx6fOyWPi/KDGRa6p4r77cxIH3DobFleDxdVhcQ0wHGvmoXBVWFyBjw1Wtdn33tu5wVMitUtIMyrMfZlEjam/7C+JQTKC6D6L/rVRRoRRy+y0mVdBhbPBLjK5JkUBtkoykhP0VZ7KTopqgqFGl84QyiCZRJOiAFUUZgTNHJM4AcrK66vuhfPlJrpT5WZy3UpXHFSH5FqDoi0xJUtZIUiu/hSG6H6Olacz3Tl/lCOzuzPov/JeXA/fzSdQdpwsR7LuDY96g/ulMPEM9Q1t74huT3qDp/3hm7YzfTror6eCCGsVa9xESY+rcpknYeBc2dzR4kqGSpWbp0daXMnapKUPCOOWZx60uJJ+oDN0+PMBWXuR+vW6PS5UNvrcTs89mqZ7C2e772/G9s/I3QHdWgxfzVhk/c7tPYX3SeEuwdntOEcnXv+d92U+FU5Ujy+YRpePCOiRwcZotYmCZk0YBrqKh7bx0Ih9XcNDV/DQeLMRcaJXcIaRdTox0Dgawh5yYZgnxGFEtNcWGtrEmY3MOycUNI7yWXgT3cKb6KwbA4wWuziD+33/4W2Yz/Hp43C6491dDJg0jqN413RYhTYnW2Mn4zBdFh/uru44uyt+PtLuC+dyM9yeURoVEXUXF09YN4zU2ALQJCt7EHVGf5G0e97lrPfqJ+fq0Ln5PNzpuh8TryAaJhfNr4L64zdRgwyB6qo0SGDMlFDZWq+Eyl4pC6H8s7oIZYgtiFKr4FBAKiUxNkoojW5nUJKtmFK3Zy/lSt0O84GSlUkJle1hKaGyl2KlEYSzDAI/T+kDYVpliY/ejz84tyfDhU3vYNU72vErBnX7zv12tFSvL5Or1+5xLxVPXDWbaSsBiJUcwWljs08MtbHwfcueDEBjs4+dtLGZ8zoMe3Yub0m741wd+f9y/JO7MU/WXkSX60sfxlnLmVW/0sj0HSbEhW/NuBtTUGamkdVkZto1TWamKVFnitcqTSaEGjFM8eqlyUw73cXiM8I4j2qc1aQuucDKvycfJcgHCgrgcbCtM7SiRxI4M+diSQEnu8FTwRX4WGHIQkgbhSzkRUDIb15HLYurDyhf4iZQwa2n8oU3j1K+peZRysEBfF8pBwfwKNkN8YQo5b4avQOy04tNJmp62uls+TWUWjPO4bYf0ddZJ7fb/r3U/ua3Jh/BVq2Nr32rmRFsvldx0//nP/7+Dz6srhqHv0VJWxR/WXoVL7u7jjo6vru2pBfyk6Fgrj1DLnON2IC5Bk9wg+hlicFR5QZVC2Guwfn2wlz/8lyEcQu4kjnsthaHs/3Qifg96Z2S82MyP0eOt7NWirhmjWAjIrhRHmnoOBNKVWLrivy6ZAByfp3JZ5Te7I4K+7gzK8OPu8PpjtNuDbot9+SQdk+wU3npfnhK+lhM3cHs8yIVaLQgc+ERGGjEVmcfCqn3sukXcAe7AhiVxBofzDTArrYSaL8rGmA3lDwap0PYyrcYaLDLTw5dA7vr49Fgt2Y8GuzWjEeD3avyaDzlq+FMGdYtwEAj6jWOeQrQYHfYHLqONxvreLOxjjcb63izsY6j14EHiaPXJnMshbE24ihfgMZRvgCdqSG5V/+JetqZtmIiRPYyWgARfE0cgJCtlJNzsv0cBY5q7zIcU7iHmJxTVQsY4TlA31UF6OeAo6qCKU62izE5J3u1UOAAtccG6B8rNkRqITkRzYhbVYGiMflaoWjK8QrRk9f4itpSDhPhUDYgSvk6n0cpB6/wfaUc25FAScIwlVAw3R6gYPRKEmGvhAK56Y8OrOMoiuzlb6ILyiidQnyRmh18p8fMfryh2c7MSaHJxOhP/Ut5jmnqX0zz7cQYo8x5rcnUD5zgmfoBCQmmOKRSk1ngcbzwajisyJN4za58CRuVEIovFk3ld+M8SuFBbATRe9+bgLCmcPJLvAgVX+IBveEMueybU5g3hjw3+/Rh8uP+sdbFNwlgxzGjQlYIbywSaEO4NOR6+BGnns7hp88Bak92LJZCe5R91KhSGES0PY9SduF4lL6/MSoT10gxtZL1IGSIkdk9lRwscMl62IGAwmmFqnE4WRIAFRxs3+kF0vG4AkNRMLuOmaPGxRNQyOKSikDsPM+oaGYPWZhhcYjUBykK0c0xIon/nhAii0YsnDJFN1EJnLLp6klePpIoku7xkGz8NHz95OxvUreNnM8lUc2U3hYKf4tWkTD8Lf9jJkvdIp2Ek6EkE0Ar+4nE7mtxEbLW5K2iWllrsLgI2U/yItW9p7Zz+9Kdbjmf7xK/3qikN2I6T3EZtUydhrsP6+Rxmn7L99/+3nfazjbCuhLk7LNfBuy4563MUtF0L8LPxBo3EwFe5priea39cCd7jmtjs+elNlbL8xlFPwP5tDwOuHW5fpnzeo/+6Z5uuodbKY7NOGS5zmxBjoL/Ed0Yxat+Q8ETinrGKjRuk8ZlK2c6G6VKrgHbdj5kWj2uN4ispTP8b/8P", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [责任体 = _t, 项目名称 = _t, 合同编号 = _t]),
				    删除的副本 = Table.Distinct(源, {"合同编号"}),
				    合并的查询2 = Table.NestedJoin(删除的副本, {"合同编号"}, D_下游合同, {"合同编号"}, "D_下游合同", JoinKind.LeftOuter),
				    #"展开的“D_下游合同”1" = Table.ExpandTableColumn(合并的查询2, "D_下游合同", {"KEYID", "合同名称", "客商名称"}, {"KEYID", "合同名称", "客商名称"}),
				    合并的查询 = Table.NestedJoin(#"展开的“D_下游合同”1", {"KEYID"}, F_下游合同结算, {"KEYID"}, "F_下游合同结算", JoinKind.LeftOuter),
				    #"展开的“F_下游合同结算”" = Table.ExpandTableColumn(合并的查询, "F_下游合同结算", {"价税合计"}, {"价税合计"}),
				    已添加条件列 = Table.AddColumn(#"展开的“F_下游合同结算”", "结算状态", each if [价税合计] = null then "未结" else "已结",type text)
				in
				    已添加条件列

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

