table 963应结未结
	lineageTag: 33ffa6c0-649e-431e-8c87-0f22f4cb3dbb

	measure 'cnt.合同数.963' = DISTINCTCOUNT('963应结未结'[合同编号])
		formatString: 0
		lineageTag: 29717ed0-1e6e-4582-84df-ae64dc7d9c15

	measure 'cnt.合同数.未结.963' = CALCULATE([cnt.合同数.963],'963应结未结'[结算状态]="未结")
		formatString: 0
		lineageTag: 08788217-1125-4938-bce9-f8ff0d5a7a89

	measure 'R.未结率.963' = DIVIDE([cnt.合同数.未结.963],[cnt.合同数.963])
		lineageTag: c2bc0c13-e6a2-494c-b68b-0aca0958bd95

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 责任体
		dataType: string
		lineageTag: c9c03817-e3a9-47b2-9452-675e4b721e61
		summarizeBy: none
		sourceColumn: 责任体

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 2fd61fb9-f00e-4f71-97f5-09422f5eed50
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: b2fd20a0-a1de-4ae3-9148-de2bee25eecd
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 结算状态
		dataType: string
		lineageTag: 796b841b-ef4c-4560-892d-6925f480b0ac
		summarizeBy: none
		sourceColumn: 结算状态

		annotation SummarizationSetBy = Automatic

	column 合同名称
		dataType: string
		lineageTag: 63c7fbea-2733-4e91-b4c3-fc9c870f5430
		summarizeBy: none
		sourceColumn: 合同名称

		annotation SummarizationSetBy = Automatic

	column 客商名称
		dataType: string
		lineageTag: 5856803e-b0ea-49fd-8796-d69a18c14f6f
		summarizeBy: none
		sourceColumn: 客商名称

		annotation SummarizationSetBy = Automatic

	column KEYID
		dataType: string
		lineageTag: 2c48afda-1c04-496c-9b71-57dca3bd782f
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: 61ca98e4-c556-46c4-9d91-850c6d007ff9
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 963应结未结 = m
		mode: import
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("vZ1bbxw3soD/S/blHGAFTF/m9pjN5mSxyMEG2ADr48W+79s+7B+QrOhqXWNZF89I", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [责任体 = _t, 项目名称 = _t, 合同编号 = _t]),
				    删除的副本 = Table.Distinct(源, {"合同编号"}),
				    合并的查询2 = Table.NestedJoin(删除的副本, {"合同编号"}, D_下游合同, {"合同编号"}, "D_下游合同", JoinKind.LeftOuter),
				    #"展开的“D_下游合同”1" = Table.ExpandTableColumn(合并的查询2, "D_下游合同", {"KEYID", "合同名称", "客商名称"}, {"KEYID", "合同名称", "客商名称"}),
				    合并的查询 = Table.NestedJoin(#"展开的“D_下游合同”1", {"KEYID"}, F_下游合同结算, {"KEYID"}, "F_下游合同结算", JoinKind.LeftOuter),
				    #"展开的“F_下游合同结算”" = Table.ExpandTableColumn(合并的查询, "F_下游合同结算", {"价税合计"}, {"价税合计"}),
				    已添加条件列 = Table.AddColumn(#"展开的“F_下游合同结算”", "结算状态", each if [价税合计] = null then "未结" else "已结",type text)
				in
				    已添加条件列

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

