table D-责任体
	excludeFromModelRefresh
	lineageTag: a59a6d57-0600-4821-bedc-5bedd989655a

	column 责任体
		dataType: string
		lineageTag: 57761bb7-804e-4f45-8149-1811b93db330
		summarizeBy: none
		sourceColumn: 责任体
		sortByColumn: 排序

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 排序
		dataType: int64
		formatString: 0
		lineageTag: 456ad9ac-e1b6-4d97-851a-ce14dd880504
		summarizeBy: none
		sourceColumn: 排序

		annotation SummarizationSetBy = Automatic

	partition D-责任体-94ab983a-7053-4398-b239-4d008d7f7ba2 = m
		mode: import
		queryGroup: 维度表
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wetq65mn/juezt7yYsFRJR8lQKVYnWunJjjlPe6Y/7WiDyALFjcDiT3v70MSNYeIgLUjiJnD1vSjqTcHiL5buRxM3A4s/X7PmyY6GJ7u6n+yY9bJ5BVDcHC6+qwdZ3AKhvhNZ3BIm/nT2bGRxQwOwxLOt258umQbiQz20c/+TvbORHWIIDIFYAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [责任体 = _t, 排序 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"责任体", type text}, {"排序", Int64.Type}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

