table D_承包合同
	lineageTag: 8a9eded0-26dc-4a6f-9f11-fbe482e44fa2

	column 合同标识 = 'D_承包合同'[合同名称]&"("& 'D_承包合同'[合同编号]&")"
		dataType: string
		lineageTag: 45cfa641-09a8-4c6c-8098-2ba20452dc3d
		summarizeBy: none
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	column FID
		dataType: string
		lineageTag: 5d5d3b65-60a9-407d-b77f-22c6f421014f
		summarizeBy: none
		sourceColumn: FID

		annotation SummarizationSetBy = Automatic

	column 合同分类[1]
		dataType: string
		lineageTag: 460f5e6d-1e6b-43b5-b2cc-e3ee19fe0139
		summarizeBy: none
		sourceColumn: 合同分类[1]

		annotation SummarizationSetBy = Automatic

	column 合同分类[2]
		dataType: string
		lineageTag: 1ac1d00b-8453-48c2-9f74-a979828c6133
		summarizeBy: none
		sourceColumn: 合同分类[2]

		annotation SummarizationSetBy = Automatic

	column 备案合同编号
		dataType: string
		lineageTag: 9ed98522-dcdc-4bf5-b8b4-46ba08cdd5ad
		summarizeBy: none
		sourceColumn: 备案合同编号

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 5509c996-3fa7-4ceb-8030-0e55b9aae32f
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 合同名称
		dataType: string
		lineageTag: 9b1d1ea5-c254-462a-b22d-f43010ce0ec0
		summarizeBy: none
		sourceColumn: 合同名称

		annotation SummarizationSetBy = Automatic

	column 份数
		dataType: double
		lineageTag: 90ca780e-056f-4999-b5c7-03f059e6aceb
		summarizeBy: sum
		sourceColumn: 份数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 补充协议类型
		dataType: string
		lineageTag: 86880e90-0a55-4031-bc4a-bbc0285217fb
		summarizeBy: none
		sourceColumn: 补充协议类型

		annotation SummarizationSetBy = Automatic

	column 第X份补充变更协议
		dataType: double
		lineageTag: 4bc49409-a9ee-4def-871b-4f4a2a727933
		summarizeBy: sum
		sourceColumn: 第X份补充变更协议

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 补充变更协议编号
		dataType: string
		lineageTag: 86b52cef-df42-4e17-9fc7-ffc0185ca0f7
		summarizeBy: none
		sourceColumn: 补充变更协议编号

		annotation SummarizationSetBy = Automatic

	column 对应工程编码
		dataType: string
		lineageTag: 9e8e81a3-2fae-4e7f-bfc0-e2b4a53995ee
		summarizeBy: none
		sourceColumn: 对应工程编码

		annotation SummarizationSetBy = Automatic

	column 对应工程编号
		dataType: string
		lineageTag: 4e559fca-613f-467c-8420-a9068c8e7484
		summarizeBy: none
		sourceColumn: 对应工程编号

		annotation SummarizationSetBy = Automatic

	column 对应工程名称
		dataType: string
		lineageTag: 87a416f7-96e5-4b1d-acc6-eee4e3cd8140
		summarizeBy: none
		sourceColumn: 对应工程名称

		annotation SummarizationSetBy = Automatic

	column 对应承包合同编号
		dataType: string
		lineageTag: aa0bf857-e819-47fc-bf03-5b305fb88467
		summarizeBy: none
		sourceColumn: 对应承包合同编号

		annotation SummarizationSetBy = Automatic

	column 对应承包合同
		dataType: string
		lineageTag: 418537a0-74ef-45e2-816a-c71147bc3d1f
		summarizeBy: none
		sourceColumn: 对应承包合同

		annotation SummarizationSetBy = Automatic

	column 对应执行/备案合同编号
		dataType: string
		lineageTag: 8e72dd60-e212-4bed-82d4-815b84ae5c94
		summarizeBy: none
		sourceColumn: 对应执行/备案合同编号

		annotation SummarizationSetBy = Automatic

	column FDUIYINGBEIANHETONGNO
		dataType: string
		lineageTag: a816136a-bef4-4639-87d5-3c14f5f18a6d
		summarizeBy: none
		sourceColumn: FDUIYINGBEIANHETONGNO

		annotation SummarizationSetBy = Automatic

	column 对应执行/备案合同
		dataType: string
		lineageTag: bd22c8f2-841d-448e-89cb-d889ca1f7700
		summarizeBy: none
		sourceColumn: 对应执行/备案合同

		annotation SummarizationSetBy = Automatic

	column 工程承包单位
		dataType: string
		lineageTag: c2029219-9e80-45d0-8b2c-0658d1b1927b
		summarizeBy: none
		sourceColumn: 工程承包单位

		annotation SummarizationSetBy = Automatic

	column 履约责任单位
		dataType: string
		lineageTag: f0b946d5-61c9-46f0-876b-7e45883eb4cb
		summarizeBy: none
		sourceColumn: 履约责任单位

		annotation SummarizationSetBy = Automatic

	column 设计单位
		dataType: string
		lineageTag: 4794d4f9-cbfb-4ae8-aba5-39ee593179bf
		summarizeBy: none
		sourceColumn: 设计单位

		annotation SummarizationSetBy = Automatic

	column 监理单位
		dataType: string
		lineageTag: d3479a40-6489-4882-ac34-7dfe6f9458f1
		summarizeBy: none
		sourceColumn: 监理单位

		annotation SummarizationSetBy = Automatic

	column 合同签订日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 138f0aea-b874-4b4d-8934-5a0b1fc71177
		summarizeBy: none
		sourceColumn: 合同签订日期

		annotation SummarizationSetBy = Automatic

	column 项目经理
		dataType: string
		lineageTag: f338b985-fda0-4246-a71e-f8bc8dc64ff6
		summarizeBy: none
		sourceColumn: 项目经理

		annotation SummarizationSetBy = Automatic

	column 承包方式
		dataType: string
		lineageTag: 785c0ede-28a0-41cf-a234-22bbf843f2d2
		summarizeBy: none
		sourceColumn: 承包方式

		annotation SummarizationSetBy = Automatic

	column 专业分类
		dataType: string
		lineageTag: 56cc2388-938f-4afc-b4b3-359ad67ec676
		summarizeBy: none
		sourceColumn: 专业分类

		annotation SummarizationSetBy = Automatic

	column 外部联合签约主体
		dataType: string
		lineageTag: 4465e83b-73a8-4856-a59f-4497f84fc627
		summarizeBy: none
		sourceColumn: 外部联合签约主体

		annotation SummarizationSetBy = Automatic

	column 承包范围
		dataType: string
		lineageTag: 6afb9557-1822-45c9-8399-580676f33364
		summarizeBy: none
		sourceColumn: 承包范围

		annotation SummarizationSetBy = Automatic

	column 用章情况
		dataType: string
		lineageTag: 1fa3d90e-d345-427b-b6cd-4d1259e1e58b
		summarizeBy: none
		sourceColumn: 用章情况

		annotation SummarizationSetBy = Automatic

	column 国内/外
		dataType: string
		lineageTag: 6040b87a-432d-49f0-a645-7b1aabe0b51e
		summarizeBy: none
		sourceColumn: 国内/外

		annotation SummarizationSetBy = Automatic

	column 省
		dataType: string
		lineageTag: ebdb3e87-7a2c-4ca0-a7cf-bfdaecc82770
		summarizeBy: none
		sourceColumn: 省

		annotation SummarizationSetBy = Automatic

	column 市
		dataType: string
		lineageTag: 6aacd6bd-e716-414c-aeff-510a125c078e
		summarizeBy: none
		sourceColumn: 市

		annotation SummarizationSetBy = Automatic

	column 县/区
		dataType: string
		lineageTag: e0122f9f-9115-42fb-946a-1d191fdead65
		summarizeBy: none
		sourceColumn: 县/区

		annotation SummarizationSetBy = Automatic

	column 具体地址
		dataType: string
		lineageTag: 872e09fd-bbe4-4e55-b663-304a3608cfab
		summarizeBy: none
		sourceColumn: 具体地址

		annotation SummarizationSetBy = Automatic

	column 工程类别[一级]
		dataType: string
		lineageTag: 26e09b0d-d7ca-4c63-a464-adf42874832f
		summarizeBy: none
		sourceColumn: 工程类别[一级]

		annotation SummarizationSetBy = Automatic

	column 工程类别[二级]
		dataType: string
		lineageTag: 2c6f6f70-ea80-458a-bb5d-3aca98c812f0
		summarizeBy: none
		sourceColumn: 工程类别[二级]

		annotation SummarizationSetBy = Automatic

	column 投资来源
		dataType: string
		lineageTag: cc8eee0c-fcbe-4598-9238-dbcc61e5b1ba
		summarizeBy: none
		sourceColumn: 投资来源

		annotation SummarizationSetBy = Automatic

	column 建筑高度(m)
		dataType: double
		lineageTag: 2ae8cd76-011d-4f2d-ba6e-991284c2e87d
		summarizeBy: sum
		sourceColumn: 建筑高度(m)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 建筑面积(㎡)
		dataType: double
		lineageTag: c6814c67-7980-4f5a-8205-1e7a8c532b4a
		summarizeBy: sum
		sourceColumn: 建筑面积(㎡)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 主体结构
		dataType: string
		lineageTag: a32f6034-8719-4e8d-b9ab-8d79cafdd597
		summarizeBy: none
		sourceColumn: 主体结构

		annotation SummarizationSetBy = Automatic

	column 地上层数
		dataType: double
		lineageTag: 4522695d-9440-4a3b-a23b-77d9725a28d6
		summarizeBy: sum
		sourceColumn: 地上层数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 地下层数
		dataType: double
		lineageTag: 5bca56e6-f868-442a-825c-87db0b1d031c
		summarizeBy: sum
		sourceColumn: 地下层数

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 基础结构
		dataType: string
		lineageTag: 5a20a727-a80c-4a07-aa50-d14455877d15
		summarizeBy: none
		sourceColumn: 基础结构

		annotation SummarizationSetBy = Automatic

	column 开工具体日期
		dataType: dateTime
		formatString: General Date
		lineageTag: e9f33478-ec54-473d-9939-ed0d2dca588c
		summarizeBy: none
		sourceColumn: 开工具体日期

		annotation SummarizationSetBy = Automatic

	column 合同总工期（天）
		dataType: string
		lineageTag: dd434ff4-b8e6-4c9b-aa7c-93252452c5c6
		summarizeBy: none
		sourceColumn: 合同总工期（天）

		annotation SummarizationSetBy = Automatic

	column 竣工具体日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 88c9e543-8161-4bbc-82fa-d8f8bfa5ed2c
		summarizeBy: none
		sourceColumn: 竣工具体日期

		annotation SummarizationSetBy = Automatic

	column 其他特殊工期（天）
		dataType: string
		lineageTag: ea4462c7-b1e9-4ecb-8831-d617696ade17
		summarizeBy: none
		sourceColumn: 其他特殊工期（天）

		annotation SummarizationSetBy = Automatic

	column 质量目标
		dataType: string
		lineageTag: c3919d9a-4375-474c-b8c2-78a552ee71d9
		summarizeBy: none
		sourceColumn: 质量目标

		annotation SummarizationSetBy = Automatic

	column 合同价款类型
		dataType: string
		lineageTag: 96e5654f-d6e2-4962-b832-fb08b9322377
		summarizeBy: none
		sourceColumn: 合同价款类型

		annotation SummarizationSetBy = Automatic

	column 计价依据
		dataType: string
		lineageTag: 4eaa87bc-f974-4b28-8435-2e3d8fdadb43
		summarizeBy: none
		sourceColumn: 计价依据

		annotation SummarizationSetBy = Automatic

	column 主材价款是否可调
		dataType: string
		lineageTag: 1b04a85b-df00-4430-91cd-6ef56676f4bf
		summarizeBy: none
		sourceColumn: 主材价款是否可调

		annotation SummarizationSetBy = Automatic

	column 合同金额是否价税分离
		dataType: string
		lineageTag: 005e4678-51bd-4003-890b-e13328a5df7c
		summarizeBy: none
		sourceColumn: 合同金额是否价税分离

		annotation SummarizationSetBy = Automatic

	column 合同金额含税（元）
		dataType: double
		lineageTag: 50c9d267-2b85-47d8-a29f-6568a22fc14a
		summarizeBy: sum
		sourceColumn: 合同金额含税（元）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 合同金额无税（元）
		dataType: double
		lineageTag: 67c05b0e-8876-4b14-827c-eb43f6f09a04
		summarizeBy: sum
		sourceColumn: 合同金额无税（元）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目回购
		dataType: string
		lineageTag: 0d808622-0400-4a32-b063-ae2d57f25999
		summarizeBy: none
		sourceColumn: 项目回购

		annotation SummarizationSetBy = Automatic

	column 回购担保
		dataType: string
		lineageTag: fc92ee6b-5417-4890-8d4c-2eaa6cc62a1a
		summarizeBy: none
		sourceColumn: 回购担保

		annotation SummarizationSetBy = Automatic

	column 合同价款调整约定
		dataType: string
		lineageTag: 15f98861-ba47-4114-9001-4150742ff7d0
		summarizeBy: none
		sourceColumn: 合同价款调整约定

		annotation SummarizationSetBy = Automatic

	column 施工完成量审核约定
		dataType: string
		lineageTag: 7d8ed111-0d81-470c-98ad-957cba9e35fe
		summarizeBy: none
		sourceColumn: 施工完成量审核约定

		annotation SummarizationSetBy = Automatic

	column 施工完成量业主/监理审核周期
		dataType: string
		lineageTag: 02191646-e499-47ad-be3d-db5a0de44c10
		summarizeBy: none
		sourceColumn: 施工完成量业主/监理审核周期

		annotation SummarizationSetBy = Automatic

	column 洽商变更索赔约定
		dataType: string
		lineageTag: 9f23017c-1b76-4960-a22e-5ae73753fe1d
		summarizeBy: none
		sourceColumn: 洽商变更索赔约定

		annotation SummarizationSetBy = Automatic

	column 合同结算约定
		dataType: string
		lineageTag: d28ee52d-e8ab-4a88-b1dd-3d48692b70c0
		summarizeBy: none
		sourceColumn: 合同结算约定

		annotation SummarizationSetBy = Automatic

	column 竣工结算审核期限
		dataType: string
		lineageTag: 6c0b25e2-fcac-429d-908a-6c214f9b4eaf
		summarizeBy: none
		sourceColumn: 竣工结算审核期限

		annotation SummarizationSetBy = Automatic

	column 审核参与单位
		dataType: string
		lineageTag: 15cccdeb-c636-4e26-8bdd-186809848871
		summarizeBy: none
		sourceColumn: 审核参与单位

		annotation SummarizationSetBy = Automatic

	column 是否有工程预付款
		dataType: string
		lineageTag: 9d3e1d67-d94b-4344-bd61-67e297b04801
		summarizeBy: none
		sourceColumn: 是否有工程预付款

		annotation SummarizationSetBy = Automatic

	column 预付款支付比例
		dataType: double
		lineageTag: 0f2caf2a-e8f6-4539-ad0b-156fbd16d149
		summarizeBy: sum
		sourceColumn: 预付款支付比例

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 进度款支付约定
		dataType: string
		lineageTag: 26420a22-f467-4dc4-8c08-5251aa716bd6
		summarizeBy: none
		sourceColumn: 进度款支付约定

		annotation SummarizationSetBy = Automatic

	column 进度款支付方式
		dataType: string
		lineageTag: bdfa9317-7fdd-409e-bae1-51dfaf998fb1
		summarizeBy: none
		sourceColumn: 进度款支付方式

		annotation SummarizationSetBy = Automatic

	column 进度款支付比例
		dataType: double
		lineageTag: 09a48d29-0951-4db7-9f5d-7ad74fb1aeaf
		summarizeBy: sum
		sourceColumn: 进度款支付比例

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 竣工时累计支付比例
		dataType: double
		lineageTag: 2aa46505-6211-45d9-8ef8-1fafd28dbbfe
		summarizeBy: sum
		sourceColumn: 竣工时累计支付比例

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 进度款审核期限
		dataType: string
		lineageTag: ddc6b29e-5c68-4c4b-8a9f-cc9e4c9fd7f7
		summarizeBy: none
		sourceColumn: 进度款审核期限

		annotation SummarizationSetBy = Automatic

	column 进度款支付期限
		dataType: string
		lineageTag: f7362438-82f4-4b38-bf1e-203a3ec96986
		summarizeBy: none
		sourceColumn: 进度款支付期限

		annotation SummarizationSetBy = Automatic

	column 结算后累计支付比例
		dataType: double
		lineageTag: 76ceee9f-911e-4fa1-a4b1-e5150097c130
		summarizeBy: sum
		sourceColumn: 结算后累计支付比例

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 保修金预留及返还约定
		dataType: string
		lineageTag: 649ce9c6-963d-4470-997c-8a2419b3fd41
		summarizeBy: none
		sourceColumn: 保修金预留及返还约定

		annotation SummarizationSetBy = Automatic

	column 保修金预留方式
		dataType: string
		lineageTag: d338dae4-4281-4f7a-b0fb-abca6c68d5e5
		summarizeBy: none
		sourceColumn: 保修金预留方式

		annotation SummarizationSetBy = Automatic

	column 保修金预留比例
		dataType: double
		lineageTag: 1ef0ede6-04a1-4e95-a405-ead492d87734
		summarizeBy: sum
		sourceColumn: 保修金预留比例

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工期奖罚约定
		dataType: string
		lineageTag: cdf776e3-de38-4526-8b84-3fb8da389c6b
		summarizeBy: none
		sourceColumn: 工期奖罚约定

		annotation SummarizationSetBy = Automatic

	column 工期拖期违约金比例
		dataType: string
		lineageTag: 0d1f90fc-d405-4541-8df9-dbdf638e5537
		summarizeBy: none
		sourceColumn: 工期拖期违约金比例

		annotation SummarizationSetBy = Automatic

	column 工期拖期违约金有无上限
		dataType: string
		lineageTag: b1881cd7-d7c5-44d5-b295-75653089e538
		summarizeBy: none
		sourceColumn: 工期拖期违约金有无上限

		annotation SummarizationSetBy = Automatic

	column 上限比例
		dataType: string
		lineageTag: 2e3a6d15-8100-4a60-a17a-af61d521e236
		summarizeBy: none
		sourceColumn: 上限比例

		annotation SummarizationSetBy = Automatic

	column 其它奖罚约定
		dataType: string
		lineageTag: f85a39d7-4ad4-4795-a471-e808b51bbefb
		summarizeBy: none
		sourceColumn: 其它奖罚约定

		annotation SummarizationSetBy = Automatic

	column 担保约定
		dataType: string
		lineageTag: 106e3440-3755-4f02-921a-5b5131878620
		summarizeBy: none
		sourceColumn: 担保约定

		annotation SummarizationSetBy = Automatic

	column 预付款担保形式
		dataType: string
		lineageTag: 3a7b9ae5-7fc7-4375-bf1a-8b2e747926c6
		summarizeBy: none
		sourceColumn: 预付款担保形式

		annotation SummarizationSetBy = Automatic

	column 预付款担保额度
		dataType: double
		lineageTag: f57da5e8-6c96-4c9a-a17a-0e62620012c7
		summarizeBy: sum
		sourceColumn: 预付款担保额度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预付款担保期限
		dataType: string
		lineageTag: b6f8c5e6-1b22-4a34-b7c9-815e63da2b19
		summarizeBy: none
		sourceColumn: 预付款担保期限

		annotation SummarizationSetBy = Automatic

	column 履约担保形式
		dataType: string
		lineageTag: 54381a02-863b-43d3-8372-37e35d7f926c
		summarizeBy: none
		sourceColumn: 履约担保形式

		annotation SummarizationSetBy = Automatic

	column 履约担保额度
		dataType: double
		lineageTag: 4bf933f4-e659-471a-86bc-740cd5233609
		summarizeBy: sum
		sourceColumn: 履约担保额度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 履约担保期限
		dataType: string
		lineageTag: 0114b27d-6b07-43db-8ab9-c0ae4da84246
		summarizeBy: none
		sourceColumn: 履约担保期限

		annotation SummarizationSetBy = Automatic

	column 支付担保形式
		dataType: string
		lineageTag: d6faea3f-6095-41b5-9bab-bfb3016f682d
		summarizeBy: none
		sourceColumn: 支付担保形式

		annotation SummarizationSetBy = Automatic

	column 支付担保额度
		dataType: double
		lineageTag: fe8efd0d-0ffa-4e75-a0a9-a4c98dde3345
		summarizeBy: sum
		sourceColumn: 支付担保额度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 支付担保期限
		dataType: string
		lineageTag: fb406162-36dc-400d-97b0-f9e4789c6049
		summarizeBy: none
		sourceColumn: 支付担保期限

		annotation SummarizationSetBy = Automatic

	column 争议解决方式约定
		dataType: string
		lineageTag: eb9fbf46-5395-4fc7-8fa3-854b8c8ea422
		summarizeBy: none
		sourceColumn: 争议解决方式约定

		annotation SummarizationSetBy = Automatic

	column 是否分别签订执行和备案合同
		dataType: string
		lineageTag: 494e8a3f-cd35-401b-9e30-fa7187740953
		summarizeBy: none
		sourceColumn: 是否分别签订执行和备案合同

		annotation SummarizationSetBy = Automatic

	column 承包方签约主体
		dataType: string
		lineageTag: b91fb39a-9d7b-4dda-b1a4-6dcbbdaa773b
		summarizeBy: none
		sourceColumn: 承包方签约主体

		annotation SummarizationSetBy = Automatic

	column 评审级别
		dataType: string
		lineageTag: 0d3466f9-8204-4240-a657-3666d514b8dd
		summarizeBy: none
		sourceColumn: 评审级别

		annotation SummarizationSetBy = Automatic

	column 是否需要向集团借款
		dataType: string
		lineageTag: 9ab96e8b-1e7c-4ad1-9369-fb7a4a05bcce
		summarizeBy: none
		sourceColumn: 是否需要向集团借款

		annotation SummarizationSetBy = Automatic

	column 高峰借款金额(元)
		dataType: double
		lineageTag: 49896d4a-cf32-432b-8a9c-dd9ca345a3e1
		summarizeBy: sum
		sourceColumn: 高峰借款金额(元)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预收益率是否低于底线要求
		dataType: string
		lineageTag: 4fc04886-ee7c-4983-a5fa-318b7ccc19df
		summarizeBy: none
		sourceColumn: 预收益率是否低于底线要求

		annotation SummarizationSetBy = Automatic

	column 是否承诺放弃工程价款优先受偿权
		dataType: string
		lineageTag: fb0118b7-3b0b-4f63-b662-aa6190f779a6
		summarizeBy: none
		sourceColumn: 是否承诺放弃工程价款优先受偿权

		annotation SummarizationSetBy = Automatic

	column 是否以现金形式支付履约保证金
		dataType: string
		lineageTag: dfd946fe-c062-48d0-afa1-4eb4b7d21796
		summarizeBy: none
		sourceColumn: 是否以现金形式支付履约保证金

		annotation SummarizationSetBy = Automatic

	column 是否以行为事实放弃工程价款优先受偿权
		dataType: string
		lineageTag: d220845c-3f60-48ec-ab63-0cb17fdf93c0
		summarizeBy: none
		sourceColumn: 是否以行为事实放弃工程价款优先受偿权

		annotation SummarizationSetBy = Automatic

	column 施工完成量业主/监理审核周期是否大于一个月
		dataType: string
		lineageTag: 250c328d-9fc8-49b9-ac97-28ed8f4dbb3e
		summarizeBy: none
		sourceColumn: 施工完成量业主/监理审核周期是否大于一个月

		annotation SummarizationSetBy = Automatic

	column 竣工交付时工程款支付额度是否低于85%
		dataType: string
		lineageTag: ed98a046-4bf4-457b-bfc8-2a4ebb9de226
		summarizeBy: none
		sourceColumn: 竣工交付时工程款支付额度是否低于85%

		annotation SummarizationSetBy = Automatic

	column 是否存在我方须无条件退场条款
		dataType: string
		lineageTag: f22df17d-9a73-4d2b-b26c-abbd71332bc6
		summarizeBy: none
		sourceColumn: 是否存在我方须无条件退场条款

		annotation SummarizationSetBy = Automatic

	column 工程延误的处罚是否高于日万分之四
		dataType: string
		lineageTag: 2d01adbb-e5d4-4a49-a6d5-fd0b68390508
		summarizeBy: none
		sourceColumn: 工程延误的处罚是否高于日万分之四

		annotation SummarizationSetBy = Automatic

	column 发包人是否出现两个及以上法人单位
		dataType: string
		lineageTag: 04d89f58-4881-4d91-b32d-f834d5795428
		summarizeBy: none
		sourceColumn: 发包人是否出现两个及以上法人单位

		annotation SummarizationSetBy = Automatic

	column 工期延误的处罚是否无上限
		dataType: string
		lineageTag: b7a09755-7351-4ee9-b74c-dac9e870ba66
		summarizeBy: none
		sourceColumn: 工期延误的处罚是否无上限

		annotation SummarizationSetBy = Automatic

	column 工程进度款支付额度是否低于每月75%或工程进度款支付方式为节点付款
		dataType: string
		lineageTag: 01c255cd-c56c-425d-af78-9220c68ec275
		summarizeBy: none
		sourceColumn: 工程进度款支付额度是否低于每月75%或工程进度款支付方式为节点付款

		annotation SummarizationSetBy = Automatic

	column 该项目是否尚未取得规划许可证或建设用地许可证
		dataType: string
		lineageTag: b2d5e1d9-9a64-4da9-9495-d2aa3fd6d1c9
		summarizeBy: none
		sourceColumn: 该项目是否尚未取得规划许可证或建设用地许可证

		annotation SummarizationSetBy = Automatic

	column 是否约定合同争议解决方式为仲裁裁决
		dataType: string
		lineageTag: 13c414e7-837a-487c-b221-179c9049dba8
		summarizeBy: none
		sourceColumn: 是否约定合同争议解决方式为仲裁裁决

		annotation SummarizationSetBy = Automatic

	column 主表ID
		dataType: string
		lineageTag: a8dc9395-f1ba-4cd1-b8c0-573f3dd3513a
		summarizeBy: none
		sourceColumn: 主表ID

		annotation SummarizationSetBy = Automatic

	column 创建时间
		dataType: dateTime
		formatString: General Date
		lineageTag: c5845706-4100-46ee-850a-878787e15b28
		summarizeBy: none
		sourceColumn: 创建时间

		annotation SummarizationSetBy = Automatic

	column 最后修改时间
		dataType: dateTime
		formatString: General Date
		lineageTag: da72832e-0241-4e5a-a41c-941def555586
		summarizeBy: none
		sourceColumn: 最后修改时间

		annotation SummarizationSetBy = Automatic

	column 是否需要缴纳印花税
		dataType: string
		lineageTag: 2bc3d205-ac0e-40c4-823c-91ffee129e85
		summarizeBy: none
		sourceColumn: 是否需要缴纳印花税

		annotation SummarizationSetBy = Automatic

	column 是否存在商票支付条款
		dataType: string
		lineageTag: 5aa381ac-7a77-4b3c-89c7-3ee05740a551
		summarizeBy: none
		sourceColumn: 是否存在商票支付条款

		annotation SummarizationSetBy = Automatic

	column 预付款是否需要抵扣
		dataType: string
		lineageTag: 3657873f-5d2f-400c-8e50-4c72bed66897
		summarizeBy: none
		sourceColumn: 预付款是否需要抵扣

		annotation SummarizationSetBy = Automatic

	column 股份财务一体化项目名称
		dataType: string
		lineageTag: 15b22f9b-19d9-40b9-8cf5-bb459b932b14
		summarizeBy: none
		sourceColumn: 股份财务一体化项目名称

		annotation SummarizationSetBy = Automatic

	column 股份财务一体化项目编码
		dataType: string
		lineageTag: 1fcfdd8c-00f4-449c-b282-95cae3a16d01
		summarizeBy: none
		sourceColumn: 股份财务一体化项目编码

		annotation SummarizationSetBy = Automatic

	column 合同计价方式(股份)
		dataType: string
		lineageTag: 7dd7319c-e206-4b63-b8b4-d356cd0c52ab
		summarizeBy: none
		sourceColumn: 合同计价方式(股份)

		annotation SummarizationSetBy = Automatic

	column 竣工结算审核期限(股份)
		dataType: string
		lineageTag: 06bbcf30-b8e7-4b20-9308-77651848d73f
		summarizeBy: none
		sourceColumn: 竣工结算审核期限(股份)

		annotation SummarizationSetBy = Automatic

	column 工期违约金上限比例(股份)(%)
		dataType: double
		lineageTag: 0cf4f042-029b-4d22-8c11-3558271d9e50
		summarizeBy: sum
		sourceColumn: 工期违约金上限比例(股份)(%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 股份财务一体化组织机构名称
		dataType: string
		lineageTag: 5231084b-36bd-4b4c-a461-47dea43fbd8f
		summarizeBy: none
		sourceColumn: 股份财务一体化组织机构名称

		annotation SummarizationSetBy = Automatic

	column FHTWBLX
		dataType: string
		lineageTag: 0066db05-0496-4bbd-b792-c72dd65bd65d
		summarizeBy: none
		sourceColumn: FHTWBLX

		annotation SummarizationSetBy = Automatic

	column FXMCJLX
		dataType: string
		lineageTag: 5305d8b8-9a4c-4a91-8144-c77813b82f67
		summarizeBy: none
		sourceColumn: FXMCJLX

		annotation SummarizationSetBy = Automatic

	column FSFZJJTNBJY
		dataType: string
		lineageTag: ae41b38a-3c5a-490b-8b4a-3584490325fa
		summarizeBy: none
		sourceColumn: FSFZJJTNBJY

		annotation SummarizationSetBy = Automatic

	column FSFZJYJNBJY
		dataType: string
		lineageTag: bea75c1c-9099-4621-acdf-30b35375a076
		summarizeBy: none
		sourceColumn: FSFZJYJNBJY

		annotation SummarizationSetBy = Automatic

	column FGCCBDWZX
		dataType: string
		lineageTag: b2011084-d323-467e-8d62-397511d84589
		summarizeBy: none
		sourceColumn: FGCCBDWZX

		annotation SummarizationSetBy = Automatic

	column SCOUNTRY
		dataType: string
		lineageTag: 6a3840d1-9b0d-4a48-bc1f-1d0c440d4f96
		summarizeBy: none
		sourceColumn: SCOUNTRY

		annotation SummarizationSetBy = Automatic

	column FHTGQSFQD
		dataType: string
		lineageTag: 9aa13741-34fa-43f7-b535-9b6c4f3e5573
		summarizeBy: none
		sourceColumn: FHTGQSFQD

		annotation SummarizationSetBy = Automatic

	column FJJBZ
		dataType: string
		lineageTag: 6b1df38e-13b1-4bc1-a757-fe7d00da71a6
		summarizeBy: none
		sourceColumn: FJJBZ

		annotation SummarizationSetBy = Automatic

	column FHTSE
		dataType: double
		lineageTag: 7410b928-d656-4fc9-b28c-10881a68870f
		summarizeBy: sum
		sourceColumn: FHTSE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FZSHTSE
		dataType: double
		lineageTag: ebdf23fd-7c06-4103-acbd-8eacba153a95
		summarizeBy: sum
		sourceColumn: FZSHTSE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FJTJSSHQX
		dataType: string
		lineageTag: 9fa89679-597a-400c-913e-64ffe7741aa9
		summarizeBy: none
		sourceColumn: FJTJSSHQX

		annotation SummarizationSetBy = Automatic

	column FJGJSSFDSFSJ
		dataType: string
		lineageTag: fa9b7b16-6819-41a2-8d04-ca58ecee6761
		summarizeBy: none
		sourceColumn: FJGJSSFDSFSJ

		annotation SummarizationSetBy = Automatic

	column FJDKZSFCZFXJZFBF
		dataType: string
		lineageTag: 1d5dcdd4-7154-4d4f-8191-a6d3411f4756
		summarizeBy: none
		sourceColumn: FJDKZSFCZFXJZFBF

		annotation SummarizationSetBy = Automatic

	column FFXJZFXS
		dataType: string
		lineageTag: e94ca826-edf3-4ab1-80e4-118429e9f100
		summarizeBy: none
		sourceColumn: FFXJZFXS

		annotation SummarizationSetBy = Automatic

	column FFXJZFBL
		dataType: double
		lineageTag: d2e8cf4a-688d-4f7a-9077-7b7aac2cfb6f
		summarizeBy: sum
		sourceColumn: FFXJZFBL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FBXJQBFHSJ
		dataType: double
		lineageTag: e959a893-5958-4d29-bdde-334ebfbf121a
		summarizeBy: sum
		sourceColumn: FBXJQBFHSJ

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FCNYXFQSCQ
		dataType: string
		lineageTag: 0bc769b7-19de-43a2-832c-f4a1bd2dd7e9
		summarizeBy: none
		sourceColumn: FCNYXFQSCQ

		annotation SummarizationSetBy = Automatic

	column FYFKDBED
		dataType: double
		lineageTag: de55720c-e6df-4f06-a962-c71d77ee60ad
		summarizeBy: sum
		sourceColumn: FYFKDBED

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FGQTQWYJJTBL
		dataType: double
		lineageTag: 6a22afac-ceaf-413b-a427-b38ef8f0f1fa
		summarizeBy: sum
		sourceColumn: FGQTQWYJJTBL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FSXJTBL
		dataType: double
		lineageTag: 657db7e5-a1fe-4d6d-ab9c-6c7547b1aa6a
		summarizeBy: sum
		sourceColumn: FSXJTBL

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FLYDBED
		dataType: double
		lineageTag: 4d43a91e-e97b-47e9-9ae7-5e4e0f3a2088
		summarizeBy: sum
		sourceColumn: FLYDBED

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FYFKKHFS
		dataType: string
		lineageTag: be796c3a-0aa6-4c59-bf87-d410e626c95c
		summarizeBy: none
		sourceColumn: FYFKKHFS

		annotation SummarizationSetBy = Automatic

	column 计价模式
		dataType: string
		lineageTag: ee31d5ac-5aea-4f60-8936-7022962c79b1
		summarizeBy: none
		sourceColumn: 计价模式

		annotation SummarizationSetBy = Automatic

	column 合同文本
		dataType: string
		lineageTag: 81786ec4-5b00-4a80-9adc-7ea80b3c8dc2
		summarizeBy: none
		sourceColumn: 合同文本

		annotation SummarizationSetBy = Automatic

	column 合同中是否约定按月上报/审批进度款
		dataType: string
		lineageTag: 5d8a47bb-ad55-489f-a8b2-407ced58804a
		summarizeBy: none
		sourceColumn: 合同中是否约定按月上报/审批进度款

		annotation SummarizationSetBy = Automatic

	column 合同签订后几日开具保函(天)
		dataType: double
		lineageTag: c39e672f-4e2c-448f-8103-9bb8af3dd15f
		summarizeBy: sum
		sourceColumn: 合同签订后几日开具保函(天)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其中银行保函履约担保额度
		dataType: double
		lineageTag: 96c84f43-bcc2-40db-a602-6d50af28a9f2
		summarizeBy: sum
		sourceColumn: 其中银行保函履约担保额度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其中银行保函履约担保额度%
		dataType: double
		lineageTag: 0de27eb1-ed86-4750-b175-22056e69922e
		summarizeBy: sum
		sourceColumn: 其中银行保函履约担保额度%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其中银行保函履约担保期限
		dataType: string
		lineageTag: 81063cc9-8c61-401f-ba84-6271462bf6ee
		summarizeBy: none
		sourceColumn: 其中银行保函履约担保期限

		annotation SummarizationSetBy = Automatic

	column 其中现金履约担保额度
		dataType: double
		lineageTag: 9d0c9040-e89b-4bd3-b68f-e9e9abe1cd97
		summarizeBy: sum
		sourceColumn: 其中现金履约担保额度

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其中现金履约担保额度%
		dataType: double
		lineageTag: ccbf106f-839b-40e6-b185-7581b9c0286c
		summarizeBy: sum
		sourceColumn: 其中现金履约担保额度%

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其中现金履约担保期限
		dataType: string
		lineageTag: c8d60484-c683-4599-a888-c23599f3af2c
		summarizeBy: none
		sourceColumn: 其中现金履约担保期限

		annotation SummarizationSetBy = Automatic

	column 支付担保额度(%)
		dataType: double
		lineageTag: 9969a007-37f1-4a7b-9ac5-0235500c5930
		summarizeBy: sum
		sourceColumn: 支付担保额度(%)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 合同盖章日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 9360c4f2-f057-4c04-abf3-171ad14b4283
		summarizeBy: none
		sourceColumn: 合同盖章日期

		annotation SummarizationSetBy = Automatic

	column 人工费是否可调
		dataType: string
		lineageTag: 94ec4167-7cd6-4056-83e3-73f9e7a0b925
		summarizeBy: none
		sourceColumn: 人工费是否可调

		annotation SummarizationSetBy = Automatic

	column 工程所在地区
		dataType: string
		lineageTag: 38be939f-1cf0-45bc-a7d7-5340fe605ecd
		summarizeBy: none
		sourceColumn: 工程所在地区

		annotation SummarizationSetBy = Automatic

	column 工程所在国家
		dataType: string
		lineageTag: cb7c37ea-9e0f-4d40-8e36-926c028606aa
		summarizeBy: none
		sourceColumn: 工程所在国家

		annotation SummarizationSetBy = Automatic

	column 当前付款比例
		dataType: double
		lineageTag: 6d53c7db-541d-4ff8-8ef6-45fc1bc909fc
		summarizeBy: sum
		sourceColumn: 当前付款比例

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 当前付款节点描述
		dataType: string
		lineageTag: 19cf3f9e-9b00-41ed-be87-9ade6e7c312a
		summarizeBy: none
		sourceColumn: 当前付款节点描述

		annotation SummarizationSetBy = Automatic

	column 计价货币兑人民币汇率
		dataType: double
		lineageTag: a6db98ef-a5d8-4c0d-aae4-5c5eb658aa23
		summarizeBy: sum
		sourceColumn: 计价货币兑人民币汇率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 是否完成交底
		dataType: string
		lineageTag: edefdf67-b4fd-4eaf-b80f-1743b017075a
		summarizeBy: none
		sourceColumn: 是否完成交底

		annotation SummarizationSetBy = Automatic

	column 评审单号
		dataType: string
		lineageTag: dc32ff78-5da0-4f29-826a-29bd8a3a75cf
		summarizeBy: none
		sourceColumn: 评审单号

		annotation SummarizationSetBy = Automatic

	column FSHEJIZHOUQI
		dataType: string
		lineageTag: 85b5ff20-4b0d-453b-a703-47669a4ba37c
		summarizeBy: none
		sourceColumn: FSHEJIZHOUQI

		annotation SummarizationSetBy = Automatic

	column 设计内容
		dataType: string
		lineageTag: 9cc50a53-fd89-4223-9409-f9ab965f3a3f
		summarizeBy: none
		sourceColumn: 设计内容

		annotation SummarizationSetBy = Automatic

	column FSFYDJTFXJZFBL
		dataType: string
		lineageTag: 894cf93c-fc63-48b1-bdcc-1e91ef382d2b
		summarizeBy: none
		sourceColumn: FSFYDJTFXJZFBL

		annotation SummarizationSetBy = Automatic

	column 支付比例控制类型（催收清欠）
		dataType: string
		lineageTag: 5318d891-6e0c-44a3-8392-d642c25505e0
		summarizeBy: none
		sourceColumn: 支付比例控制类型（催收清欠）

		annotation SummarizationSetBy = Automatic

	column 承包合同交底日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 8c333cf2-a169-4811-996f-f150b887960a
		summarizeBy: none
		sourceColumn: 承包合同交底日期

		annotation SummarizationSetBy = Automatic

	column 股份合同编号
		dataType: string
		lineageTag: 63f0466b-d29f-402a-a133-6b13a2a82038
		summarizeBy: none
		sourceColumn: 股份合同编号

		annotation SummarizationSetBy = Automatic

	column 是否需要垫资
		dataType: string
		lineageTag: 4034745f-dd5d-40ed-8787-b903b722c848
		summarizeBy: none
		sourceColumn: 是否需要垫资

		annotation SummarizationSetBy = Automatic

	column 内部统计期号
		dataType: dateTime
		formatString: General Date
		lineageTag: dd28736d-6780-4694-a163-b94629d89b13
		summarizeBy: none
		sourceColumn: 内部统计期号

		annotation SummarizationSetBy = Automatic

	column 股份统计期号
		dataType: dateTime
		formatString: General Date
		lineageTag: 4fafe719-b1b5-4de4-a170-1d81eaae4449
		summarizeBy: none
		sourceColumn: 股份统计期号

		annotation SummarizationSetBy = Automatic

	column 备注
		dataType: string
		lineageTag: 2fecb64d-5f0d-453f-a2e3-d1d80d931de5
		summarizeBy: none
		sourceColumn: 备注

		annotation SummarizationSetBy = Automatic

	column 营销归属责任体
		dataType: string
		lineageTag: 2a9e0c1a-0e89-4132-ab4a-38b412d8e98b
		summarizeBy: none
		sourceColumn: 营销归属责任体

		annotation SummarizationSetBy = Automatic

	column 直管机构
		dataType: string
		lineageTag: 9d2256bd-1a0f-4f19-b7e5-3222829348b1
		summarizeBy: none
		sourceColumn: 直管机构

		annotation SummarizationSetBy = Automatic

	column 直管机构编码
		dataType: string
		lineageTag: 629a4876-9121-4b1a-9785-26e5a5ff9fd8
		summarizeBy: none
		sourceColumn: 直管机构编码

		annotation SummarizationSetBy = Automatic

	column 设计费用
		dataType: double
		lineageTag: abd0cf01-3bec-4494-b5ec-e12422ec4563
		summarizeBy: sum
		sourceColumn: 设计费用

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 设计支付约定
		dataType: string
		lineageTag: 4b7bfc4d-d7ae-430c-9457-a8c8566e132e
		summarizeBy: none
		sourceColumn: 设计支付约定

		annotation SummarizationSetBy = Automatic

	column 设计进度延误的处罚
		dataType: string
		lineageTag: e6fa58cd-a526-442d-b6d5-84dcb8b0c0a3
		summarizeBy: none
		sourceColumn: 设计进度延误的处罚

		annotation SummarizationSetBy = Automatic

	column 设计质量缺陷责任的处罚
		dataType: string
		lineageTag: 90df354b-4bac-4d45-bb73-09113e554b86
		summarizeBy: none
		sourceColumn: 设计质量缺陷责任的处罚

		annotation SummarizationSetBy = Automatic

	column KEYID
		dataType: string
		lineageTag: 1e9ff962-2f84-4c27-a74d-f51ed11259d9
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 发包单位
		dataType: string
		lineageTag: 7d9e248a-89b2-4a76-8ada-82367abee117
		summarizeBy: none
		sourceColumn: 发包单位

		annotation SummarizationSetBy = Automatic

	partition D_承包合同-c95bfe6b-a500-492b-a12a-407d5a42e0c2 = m
		mode: import
		queryGroup: 承包合同
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="DATA_DW"]}[Data],
				    GSPM_HETONGPINGSHEN = GSPM{[Name="DW_CBHTXXB"]}[Data],
				    删除的副本 = Table.Distinct(GSPM_HETONGPINGSHEN, {"FHETONGBIANHAO"}),
				    重命名的列 = Table.RenameColumns(删除的副本,承包合同字段名,MissingField.Ignore),
				    已添加自定义 = Table.AddColumn(重命名的列, "KEYID", each [合同编号]&"@"&[对应工程编码],Text.Type),
				    删除的副本1 = Table.Distinct(已添加自定义, {"KEYID"}),
				    筛选的行 = Table.SelectRows(删除的副本1, each [KEYID] <> null and [KEYID] <> "")
				in
				    筛选的行

	annotation PBI_ResultType = Table

