table D_施工专业
	excludeFromModelRefresh
	lineageTag: 266c5a32-bf96-4b40-8b34-bc1339c155cd

	column 施工专业
		dataType: string
		lineageTag: 1c62bc11-6b4c-4160-8b49-b0417fe2f47f
		summarizeBy: none
		sourceColumn: 施工专业
		sortByColumn: 排序

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 排序
		dataType: int64
		formatString: 0
		lineageTag: 0d260bf4-c101-4d80-bb05-8a8de4f52cff
		summarizeBy: sum
		sourceColumn: 排序

		annotation SummarizationSetBy = Automatic

	partition D_施工专业-c7c08096-4c1d-4721-b9a3-72050ae045fc = m
		mode: import
		queryGroup: 维度表
		source =
				let
				    源 = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45Wejpn/tPdu5R0lAyVYnWilZ7N2fV8ylYg10gpNhYA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [施工专业 = _t, 排序 = _t]),
				    更改的类型 = Table.TransformColumnTypes(源,{{"排序", Int64.Type}})
				in
				    更改的类型

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = 导航

