table D_标准合同
	lineageTag: 5a1db6a6-1b5b-4578-9760-d5a9a5971dc2

	column 标准合同编号
		dataType: string
		lineageTag: c4973a63-ec4e-4073-acd2-22d70349e3a3
		summarizeBy: none
		sourceColumn: 标准合同编号

		annotation SummarizationSetBy = Automatic

	column 标准合同名称
		dataType: string
		lineageTag: f546eed2-a392-4a4f-ae22-d8f81454e7dd
		summarizeBy: none
		sourceColumn: 标准合同名称

		annotation SummarizationSetBy = Automatic

	column 合同分类
		dataType: string
		lineageTag: 5307fce5-fd97-4888-9f67-fc9afb86e737
		summarizeBy: none
		sourceColumn: 合同分类

		annotation SummarizationSetBy = Automatic

	column 商务科目ID
		dataType: string
		lineageTag: c5e0dd31-8879-4f75-b897-106dbd854412
		summarizeBy: none
		sourceColumn: 商务科目ID

		annotation SummarizationSetBy = Automatic

	column 财务科目ID
		dataType: string
		lineageTag: 0443b29e-db1c-4780-8374-c1adc964b0f6
		summarizeBy: none
		sourceColumn: 财务科目ID

		annotation SummarizationSetBy = Automatic

	column 合同类型
		dataType: string
		lineageTag: 572c50a5-1a10-4a02-b693-05befd7d2e46
		summarizeBy: none
		sourceColumn: 合同类型

		annotation SummarizationSetBy = Automatic

	partition D_标准合同-6638aaf5-4dc1-49f5-8df7-73a769b632ca = m
		mode: import
		queryGroup: 维度表
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_BIAOZHUNHETONG = GSPM{[Name="GSPM_BIAOZHUNHETONG2020"]}[Data],
				    重命名的列 = Table.RenameColumns(GSPM_BIAOZHUNHETONG,fx_RN("GSPM","GSPM_BIAOZHUNHETONG")),
				    删除的其他列 = Table.SelectColumns(重命名的列,{"标准合同编号", "标准合同名称", "合同分类", "商务科目ID", "财务科目ID"}),
				    删除的副本 = Table.Distinct(删除的其他列, {"标准合同编号"}),
				    筛选的行 = Table.SelectRows(删除的副本, each [标准合同编号] <> null and [标准合同编号] <> ""),
				    已添加自定义 = Table.AddColumn(筛选的行, "合同类型", each if List.Contains(集采劳务合同标准合同编码[编号],[标准合同编号]) then "集采劳务合同" else "其它",Text.Type)
				in
				    已添加自定义

	annotation PBI_ResultType = Table

