table D_租赁物资合同
	lineageTag: 94e7f6bb-b138-45fe-bc99-3797c2fa2eb4

	column 项目名称
		dataType: string
		lineageTag: 82ea939c-27a7-4651-9976-9755e3c1f3b6
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 58ca91a6-00f8-47c4-8a38-50ceb7f0a0e7
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 合同名称
		dataType: string
		lineageTag: 1d5003ee-0173-49c9-b950-28d81dad36fc
		summarizeBy: none
		sourceColumn: 合同名称

		annotation SummarizationSetBy = Automatic

	column 标准合同名称
		dataType: string
		lineageTag: 7fdea5d0-bbe3-4949-9e00-13cf26ea3d2c
		summarizeBy: none
		sourceColumn: 标准合同名称

		annotation SummarizationSetBy = Automatic

	column 分包类型
		dataType: string
		lineageTag: 755a5e93-3651-4726-a07b-d1fb9fe94548
		summarizeBy: none
		sourceColumn: 分包类型

		annotation SummarizationSetBy = Automatic

	column 供方编码
		dataType: string
		lineageTag: e272031e-90d5-4425-bf54-338a242506b9
		summarizeBy: none
		sourceColumn: 供方编码

		annotation SummarizationSetBy = Automatic

	column 供方名称
		dataType: string
		lineageTag: f9909f40-93a3-4e45-bc65-759a46fdfcbd
		summarizeBy: none
		sourceColumn: 供方名称

		annotation SummarizationSetBy = Automatic

	column KEYID
		dataType: string
		lineageTag: a8c96a47-7dad-4e3b-9b37-4edd24a594fc
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		lineageTag: c1e3862e-29b0-416a-a008-9b61db28b334
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 采购模式
		dataType: string
		lineageTag: 970e4d2b-9395-41f8-9401-9e9dbff041f6
		summarizeBy: none
		sourceColumn: 采购模式

		annotation SummarizationSetBy = Automatic

	column 集采区域
		dataType: string
		lineageTag: 590f8572-7e74-4aa7-8a24-9f45ae08d6e9
		summarizeBy: none
		sourceColumn: 集采区域

		annotation SummarizationSetBy = Automatic

	column 采购O租赁
		dataType: string
		lineageTag: f98b5191-b076-45ba-8962-cd3e3b6fe7c4
		summarizeBy: none
		sourceColumn: 采购O租赁

		annotation SummarizationSetBy = Automatic

	column 标准合同编号
		dataType: string
		lineageTag: 0d49037d-1671-4412-8078-989df91d65ea
		summarizeBy: none
		sourceColumn: 标准合同编号

		annotation SummarizationSetBy = Automatic

	column 施工专业
		dataType: string
		lineageTag: 8e842e0d-979c-4c72-9c23-6d5d3fa5a50e
		summarizeBy: none
		sourceColumn: 施工专业

		annotation SummarizationSetBy = Automatic

	column 供方类别
		dataType: string
		lineageTag: e479d4ea-13b7-4f4c-8a3f-1e8c849ddea6
		summarizeBy: none
		sourceColumn: 供方类别

		annotation SummarizationSetBy = Automatic

	column 纳税人性质
		dataType: string
		lineageTag: 61667653-bbbc-4c6e-a0da-6d3f75ab02e1
		summarizeBy: none
		sourceColumn: 纳税人性质

		annotation SummarizationSetBy = Automatic

	column 股份系统项目名称
		dataType: string
		lineageTag: 9c8b277f-dd20-4122-bb5f-f7da831cb366
		summarizeBy: none
		sourceColumn: 股份系统项目名称

		annotation SummarizationSetBy = Automatic

	column 股份系统项目编码
		dataType: string
		lineageTag: f0d9e1ca-4018-4968-8eea-27780139b0da
		summarizeBy: none
		sourceColumn: 股份系统项目编码

		annotation SummarizationSetBy = Automatic

	column 付款模式
		dataType: string
		lineageTag: 85634d80-c091-4e62-a2a3-0d5a1b9ce650
		summarizeBy: none
		sourceColumn: 付款模式

		annotation SummarizationSetBy = Automatic

	column 分供类别
		dataType: string
		lineageTag: c785577a-502f-4f15-8165-a8a339801e33
		summarizeBy: none
		sourceColumn: 分供类别

		annotation SummarizationSetBy = Automatic

	column 付款比率
		dataType: string
		lineageTag: 3f7375fa-f111-48f7-bdcc-df0b3ac428c9
		summarizeBy: none
		sourceColumn: 付款比率

		annotation SummarizationSetBy = Automatic

	column 股份合同号
		dataType: string
		lineageTag: cc06e64b-02b8-4b9a-830e-403e0171d1f0
		summarizeBy: none
		sourceColumn: 股份合同号

		annotation SummarizationSetBy = Automatic

	partition D_租赁物资合同-226d2726-1c87-447d-aba0-9487d5d405e4 = m
		mode: import
		queryGroup: 成本\物资\租赁
		source =
				let
				    源 = #"DW_WZHTXXB（物资合同）",
				    筛选的行 = Table.SelectRows(源, each ([采购O租赁] = "租赁合同")),
				    删除的其他列 = Table.SelectColumns(筛选的行,{"KEYID", "项目编码", "项目名称", "合同编号", "合同名称", "采购O租赁", "标准合同编号", "标准合同名称", "施工专业", "分包类型", "供方编码", "供方名称", "供方类别", "纳税人性质", "股份系统项目名称", "股份系统项目编码", "采购模式", "付款模式", "分供类别", "集采区域", "付款比率", "股份合同号"}),
				    删除的副本 = Table.Distinct(删除的其他列, {"KEYID"})
				in
				    删除的副本

	annotation PBI_ResultType = Table

