table F_业主结算进展
	lineageTag: 83fa6eff-dbc3-44b2-9709-14ee0de58c3a

	column 项目编码
		dataType: string
		lineageTag: e61a5d0c-ff14-49a8-9217-be775149f8cd
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: cf1fb7f0-1e21-4ef7-aae3-41bd3432bc4a
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 自施结算状态
		dataType: string
		lineageTag: e16fdf91-f0e9-4e84-a8d3-3f2137149273
		summarizeBy: none
		sourceColumn: 自施结算状态

		annotation SummarizationSetBy = Automatic

	column 业务板块
		dataType: string
		lineageTag: e3ac2b85-3412-4d40-aece-afca05f95307
		summarizeBy: none
		sourceColumn: 业务板块

		annotation SummarizationSetBy = Automatic

	column 分包类型
		dataType: string
		lineageTag: e301ebad-72b3-46be-8720-8bc240e77b5e
		summarizeBy: none
		sourceColumn: 分包类型

		annotation SummarizationSetBy = Automatic

	column 施工专业
		dataType: string
		lineageTag: 10441bf3-a7b9-4fce-b980-cea1847dcb8e
		summarizeBy: none
		sourceColumn: 施工专业

		annotation SummarizationSetBy = Automatic

	column 预计结算价税合计
		dataType: double
		lineageTag: c1ea3571-1f7b-4e2b-8ef9-24f0da1289ba
		summarizeBy: sum
		sourceColumn: 预计结算价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计结算金额
		dataType: double
		lineageTag: 00d4cec3-56e8-439c-88a0-4b2cabcd93ca
		summarizeBy: sum
		sourceColumn: 预计结算金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计结算税金
		dataType: double
		lineageTag: 8cf482ab-fe6f-4de8-a3eb-5011eae61f26
		summarizeBy: sum
		sourceColumn: 预计结算税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计成本价税合计
		dataType: double
		lineageTag: 6b38cfe6-875c-4290-9ac3-da6bc528697f
		summarizeBy: sum
		sourceColumn: 预计成本价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计成本金额
		dataType: double
		lineageTag: 354d4c6c-7367-44a8-9d57-481a4aa4be9a
		summarizeBy: sum
		sourceColumn: 预计成本金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计成本税金
		dataType: double
		lineageTag: bdbeeb87-4801-4051-82ef-7b4f5d1dfac7
		summarizeBy: sum
		sourceColumn: 预计成本税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 核定收益额
		dataType: double
		lineageTag: 8b7e4498-1f4f-4330-8c05-e8660e2e7fb2
		summarizeBy: sum
		sourceColumn: 核定收益额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计成本降低
		dataType: double
		lineageTag: b1f551f0-13ce-4d7f-9f9f-ca8af35ea9ce
		summarizeBy: sum
		sourceColumn: 预计成本降低

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计总收益额
		dataType: double
		lineageTag: abbba404-2c1b-40a4-84ab-083a41241392
		summarizeBy: sum
		sourceColumn: 预计总收益额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 初始合同收入
		dataType: double
		lineageTag: 5ccd43c0-cd7b-41bf-a9be-0e4ed53b9f31
		summarizeBy: sum
		sourceColumn: 初始合同收入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 核定收益率
		dataType: double
		lineageTag: 0063ec4e-6a98-4785-a453-d753df7fa3d2
		summarizeBy: sum
		sourceColumn: 核定收益率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预计结算收益率
		dataType: double
		lineageTag: f089202f-e4fd-452d-9987-f0187bafe695
		summarizeBy: sum
		sourceColumn: 预计结算收益率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 累计发放各类奖励金额
		dataType: double
		lineageTag: 41f2e613-3a6e-4c9b-a4ec-8dff4395c821
		summarizeBy: sum
		sourceColumn: 累计发放各类奖励金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其他收入
		dataType: double
		lineageTag: 89affd5f-5629-4b74-81db-3863d52c1921
		summarizeBy: sum
		sourceColumn: 其他收入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 营业外收入
		dataType: double
		lineageTag: 7d256db4-4265-49b3-bf5f-c70a1347dad2
		summarizeBy: sum
		sourceColumn: 营业外收入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 单方造价
		dataType: double
		lineageTag: 8ec0a0e9-236c-48a7-a09d-0a04d467c75d
		summarizeBy: sum
		sourceColumn: 单方造价

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: d492956c-9f9f-4488-bb21-027b635a7387
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 索引
		dataType: int64
		formatString: 0
		lineageTag: 519bbf85-dbd0-4faf-9434-461911642664
		summarizeBy: sum
		sourceColumn: 索引

		annotation SummarizationSetBy = Automatic

	partition F_业主结算进展 = m
		mode: import
		queryGroup: 结算进展
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="DATA_DW"]}[Data],
				    DW_WZDZMX = GSPM{[Name="DW_CBHTYZJSJZMX"]}[Data],
				    重命名的列 = Table.RenameColumns(DW_WZDZMX,{{"FXIANGMUBIANMA", "项目编码"}, {"FXIANGMUMINGCHENG", "项目名称"}, {"FYZZSJSZT", "自施结算状态"}, {"FSUOSHUBANKUAI", "业务板块"}, {"FHETONGLEIXING", "分包类型"}, {"FSHIGONGZHUANYE", "施工专业"}, {"YJJSJIASHUIHEJI", "预计结算价税合计"}, {"YJJSJINE", "预计结算金额"}, {"YJJSSHUIJIN", "预计结算税金"}, {"YJCBJIASHUIHEJI", "预计成本价税合计"}, {"YJCBJINE", "预计成本金额"}, {"YJCBSHUIJIN", "预计成本税金"}, {"HDSYE", "核定收益额"}, {"YJCBJD", "预计成本降低"}, {"YJZSYE", "预计总收益额"}, {"CSHTSR", "初始合同收入"}, {"HDSYL", "核定收益率"}, {"YJJSSYL", "预计结算收益率"}, {"FLJFAFANGJIANGJIN", "累计发放各类奖励金额"}, {"FQTSR", "其他收入"}, {"FYYWSR", "营业外收入"}, {"DFZJ", "单方造价"}, {"FRQ", "日期"}}),
				    删除的其他列 = Table.SelectColumns(重命名的列,{"项目编码", "项目名称", "自施结算状态", "业务板块", "分包类型", "施工专业", "预计结算价税合计", "预计结算金额", "预计结算税金", "预计成本价税合计", "预计成本金额", "预计成本税金", "核定收益额", "预计成本降低", "预计总收益额", "初始合同收入", "核定收益率", "预计结算收益率", "累计发放各类奖励金额", "其他收入", "营业外收入", "单方造价", "日期"}),
				    排序的行 = Table.Sort(删除的其他列,{{"项目编码", Order.Ascending}, {"分包类型", Order.Ascending}, {"施工专业", Order.Ascending}, {"日期", Order.Descending}}),
				    已添加索引 = Table.AddIndexColumn(排序的行, "索引", 0, 1, Int64.Type),
				    删除的副本 = Table.Distinct(已添加索引, {"项目编码", "分包类型", "施工专业"})
				in
				    删除的副本

	annotation PBI_ResultType = Table

