table F_全期现金流
	lineageTag: f91b77d4-fbbd-4042-9571-ca183f32bcc7

	measure 'M.保证金退还.Sum' = SUM('F_全期现金流'[保证金退还])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 38d07b3d-a9fd-47ec-9ac7-1f0e221e8dae

	measure 'M.材料款.Sum' = SUM('F_全期现金流'[材料款])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 4aa420ae-41a1-475e-bb0a-fad18ffe0631

	measure 'M.材料款:转贴票据支付.Sum' = SUM('F_全期现金流'[材料款:转贴票据支付])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: b25195a9-8878-49d6-a417-0dd0108bf7a3

	measure 'M.产值税额.Sum' = SUM('F_全期现金流'[产值税额])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: b0c7a2f2-df7a-4280-bfbc-d1c6abd6f5cd

	measure 'M.到期归还预算内借款.Sum' = SUM('F_全期现金流'[到期归还预算内借款])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: f0b97d83-88f6-4f52-b082-650a2e604d86

	measure 'M.到期归还预算外借款.Sum' = SUM('F_全期现金流'[到期归还预算外借款])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 45ff5701-d9f5-4fed-9010-726fe3c3390e

	measure 'M.非现金流支出.Sum' = SUM('F_全期现金流'[非现金流支出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: e93a44a9-7f72-4b84-a352-963a6d5ab823

	measure 'M.分包支出.Sum' = SUM('F_全期现金流'[分包支出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: ea1c7eba-5483-48ab-bd1a-3e629c4524bb

	measure 'M.分包支出:转贴票据支付.Sum' = SUM('F_全期现金流'[分包支出:转贴票据支付])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 2e0555cc-2ad8-4b23-85bf-c5d0853dda6a

	measure 'M.各类保证金支出.Sum' = SUM('F_全期现金流'[各类保证金支出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 815decb2-ed9d-48db-a91b-ad5b15113482

	measure 'M.工程款非现金流入.Sum' = SUM('F_全期现金流'[工程款非现金流入])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 2cb3af48-95f1-482b-a27e-d922b679f754

	measure 'M.工程款流入（全口径）.Sum' = SUM('F_全期现金流'[工程款流入（全口径）])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 1e4d021e-445e-40f2-bb3e-837387882142

	measure 'M.工程款流入（现金口径）.Sum' = SUM('F_全期现金流'[工程款流入（现金口径）])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 599cb85b-c2b0-4f05-9234-c9306e0ffc7d

	measure 'M.工程款现金流入.Sum' = SUM('F_全期现金流'[工程款现金流入])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: c909feb1-e4ce-44eb-aec8-8b36f42291a3

	measure 'M.公司内部借款.Sum' = SUM('F_全期现金流'[公司内部借款])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 4883d628-2db9-4e9f-bf2f-60e7ebe236bb

	measure 'M.机械使用费.Sum' = SUM('F_全期现金流'[机械使用费])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 9febe743-b535-4cff-9d5f-4bdee716b391

	measure 'M.机械使用费:转贴票据支付.Sum' = SUM('F_全期现金流'[机械使用费:转贴票据支付])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 20b50567-453f-4128-8351-ac6e67defe13

	measure 'M.间接费指出.Sum' = SUM('F_全期现金流'[间接费指出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 0578f771-453f-4751-8bea-1ec10e34fef5

	measure 'M.借款余额.Sum' = SUM('F_全期现金流'[借款余额])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: db84cea7-c22d-4a78-b9d7-8f5e7509a582

	measure 'M.拟持有至到期票据收取.Sum' = SUM('F_全期现金流'[拟持有至到期票据收取])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 9872822f-f152-4d79-b7fc-bcdf8b116fb4

	measure 'M.拟转帖票据收取.Sum' = SUM('F_全期现金流'[拟转帖票据收取])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 66beb25e-ca5a-4eb8-84b1-5bf1f84e39f2

	measure 'M.票据到期现金流入.Sum' = SUM('F_全期现金流'[票据到期现金流入])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 6d7f3132-ae17-4277-bcbd-3258275b103c

	measure 'M.其他非现金工程款流入.Sum' = SUM('F_全期现金流'[其他非现金工程款流入])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 5063e494-404c-458b-8a85-a44403029e43

	measure 'M.其他非现金流出.Sum' = SUM('F_全期现金流'[其他非现金流出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: a6a8fa40-f807-439a-84b8-6a98e9dd3e2f

	measure 'M.其他现金流入.Sum' = SUM('F_全期现金流'[其他现金流入])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: c5623066-57b7-4ed3-ba73-5aafeee58dc6

	measure 'M.其他直接费.Sum' = SUM('F_全期现金流'[其他直接费])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: a9e5340d-85ab-447f-be84-6793eb04c7b2

	measure 'M.融资业务到期兑付支出.Sum' = SUM('F_全期现金流'[融资业务到期兑付支出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: e252decb-3c24-4227-9382-8d315a3dc2f2

	measure 'M.商务产值（不含税）.Sum' = SUM('F_全期现金流'[商务产值（不含税）])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: ab8b2001-8590-411c-82e2-2bb881b1a1bd

	measure 'M.商务产值（含税）.Sum' = SUM('F_全期现金流'[商务产值（含税）])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 359411aa-5334-42e8-b8cb-515cd69e1401

	measure 'M.上交公司预收益.Sum' = SUM('F_全期现金流'[上交公司预收益])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 597c585f-fac1-40c9-8123-81f50b1cd706

	measure 'M.施工产值.Sum' = SUM('F_全期现金流'[施工产值])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: e0126119-a4d0-41ae-9483-70b1e324995e

	measure 'M.税金.Sum' = SUM('F_全期现金流'[税金])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: e954468c-19da-4bce-8e72-99f268fecc41

	measure 'M.现金流出.Sum' = SUM('F_全期现金流'[现金流出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 18efc3aa-2d57-4a11-b8f5-625471cc7213

	measure 'M.现金流入.Sum' = SUM('F_全期现金流'[现金流入])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: d7224e35-8993-4f61-87b4-214110b2a5a9

	measure 'M.项目累计现金净流量（还款后）.Sum' = SUM('F_全期现金流'[项目累计现金净流量（还款后）])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: f4104625-2cb8-439f-8707-8c1e66c7076b

	measure 'M.项目累计现金净流量.Sum' = SUM('F_全期现金流'[项目累计现金净流量])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: f98ddb70-fa22-4118-a996-ffe3739a6b05

	measure 'M.项目月度现金净流量.Sum' = SUM('F_全期现金流'[项目月度现金净流量])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 222709ce-ace3-475a-ab4a-a5a88fd65c29

	measure 'M.业主确认量.Sum' = SUM('F_全期现金流'[业主确认量])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 6568456e-fa8c-4121-ba76-7b8e24212064

	measure 'M.预算内借款.Sum' = SUM('F_全期现金流'[预算内借款])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 476fc422-dab0-41b8-89b1-eac29062a025

	measure 'M.预算内借款余额.Sum' = SUM('F_全期现金流'[预算内借款余额])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: 81ad4c34-ef79-4940-9f61-25b579b2c250

	measure 'M.预算外借款.Sum' = SUM('F_全期现金流'[预算外借款])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: a47f6cac-bca5-4df6-bf2b-9f6558ac841f

	measure 'M.直接费支出.Sum' = SUM('F_全期现金流'[直接费支出])
		formatString: #,0.00
		displayFolder: 指标
		lineageTag: c97b3b35-a331-46f1-bff0-c974d4d68a8d

	column 项目名称
		dataType: string
		displayFolder: 源列
		lineageTag: 981b4e48-a266-4e35-8de5-012f4efb1e64
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		displayFolder: 源列
		lineageTag: 75035dfb-1560-49fb-a5e2-962b185d6be0
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 评审状态
		dataType: string
		displayFolder: 源列
		lineageTag: a57662e0-0937-4ccc-85d7-4ed86d836679
		summarizeBy: none
		sourceColumn: 评审状态

		annotation SummarizationSetBy = Automatic

	column 年度
		dataType: int64
		formatString: 0
		displayFolder: 源列
		lineageTag: a284ac1d-4a58-4a27-8bc3-6b5a014f5c42
		summarizeBy: sum
		sourceColumn: 年度

		annotation SummarizationSetBy = Automatic

	column 月份
		dataType: int64
		formatString: 0
		displayFolder: 源列
		lineageTag: 5ed7507a-cdfc-47f0-8566-72df53858b9b
		summarizeBy: sum
		sourceColumn: 月份

		annotation SummarizationSetBy = Automatic

	column 商务产值（含税）
		dataType: double
		displayFolder: 源列
		lineageTag: d4df931e-4878-4033-ba81-8952efeb9044
		summarizeBy: sum
		sourceColumn: 商务产值（含税）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 业主确认量
		dataType: double
		displayFolder: 源列
		lineageTag: 9c4b55b2-a5a4-4664-95a7-321f6d5bdb48
		summarizeBy: sum
		sourceColumn: 业主确认量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 现金流入
		dataType: double
		displayFolder: 源列
		lineageTag: a9e0fbf0-20e4-4e02-bacb-a1a2c42488d6
		summarizeBy: sum
		sourceColumn: 现金流入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工程款现金流入
		dataType: double
		displayFolder: 源列
		lineageTag: b065a431-789e-46b2-ac3e-73948105aa10
		summarizeBy: sum
		sourceColumn: 工程款现金流入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 保证金退还
		dataType: double
		displayFolder: 源列
		lineageTag: 29394be0-6c40-422e-81f8-dfc12543cb08
		summarizeBy: sum
		sourceColumn: 保证金退还

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其他现金流入
		dataType: double
		displayFolder: 源列
		lineageTag: c6afe97e-053d-415a-93fa-0b447c95c746
		summarizeBy: sum
		sourceColumn: 其他现金流入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工程款回收率
		dataType: double
		displayFolder: 源列
		lineageTag: a7f9ee78-02df-4c6b-a021-773ff7d46e93
		summarizeBy: sum
		sourceColumn: 工程款回收率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 现金流出
		dataType: double
		displayFolder: 源列
		lineageTag: 7fc8f423-e846-4045-b86a-353a69455c2b
		summarizeBy: sum
		sourceColumn: 现金流出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 直接费支出
		dataType: double
		displayFolder: 源列
		lineageTag: 5634f283-3240-4dba-896f-d11d7c10ad15
		summarizeBy: sum
		sourceColumn: 直接费支出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 分包支出
		dataType: double
		displayFolder: 源列
		lineageTag: d62b5f26-af30-485b-b42b-bda8c6a1c3b7
		summarizeBy: sum
		sourceColumn: 分包支出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 材料款
		dataType: double
		displayFolder: 源列
		lineageTag: 2845a19c-d184-47c5-837c-63f47c595083
		summarizeBy: sum
		sourceColumn: 材料款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 机械使用费
		dataType: double
		displayFolder: 源列
		lineageTag: 242aaa23-2670-4edb-9737-60112527c18f
		summarizeBy: sum
		sourceColumn: 机械使用费

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其他直接费
		dataType: double
		displayFolder: 源列
		lineageTag: 49af755e-1b12-4310-86d9-68e84646ecc5
		summarizeBy: sum
		sourceColumn: 其他直接费

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 间接费指出
		dataType: string
		displayFolder: 源列
		lineageTag: 1786f7af-9eb9-4e9e-a825-dd06d9b3588e
		summarizeBy: none
		sourceColumn: 间接费指出

		annotation SummarizationSetBy = Automatic

	column 上交公司预收益
		dataType: double
		displayFolder: 源列
		lineageTag: 086b86e3-e17b-4070-86fa-d474701f84a4
		summarizeBy: sum
		sourceColumn: 上交公司预收益

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		displayFolder: 源列
		lineageTag: 5f7b66c0-30dd-4b9f-8af8-f0b4a99dde1c
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 融资业务到期兑付支出
		dataType: double
		displayFolder: 源列
		lineageTag: f0b97c6d-2032-44b8-98d6-33a1a6d5da36
		summarizeBy: sum
		sourceColumn: 融资业务到期兑付支出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 各类保证金支出
		dataType: double
		displayFolder: 源列
		lineageTag: a05c80ff-5d64-43f5-948b-56e2f3733591
		summarizeBy: sum
		sourceColumn: 各类保证金支出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 支付率
		dataType: double
		displayFolder: 源列
		lineageTag: f7f28d5b-e6a1-4b28-bf85-f1d882382d5a
		summarizeBy: sum
		sourceColumn: 支付率

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目月度现金净流量
		dataType: double
		displayFolder: 源列
		lineageTag: ea3aa0f5-4558-484e-b227-d59f5276ab70
		summarizeBy: sum
		sourceColumn: 项目月度现金净流量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目累计现金净流量
		dataType: double
		displayFolder: 源列
		lineageTag: e6ff45e4-2d91-4ce6-a097-afc69f7dd853
		summarizeBy: sum
		sourceColumn: 项目累计现金净流量

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 公司内部借款
		dataType: double
		displayFolder: 源列
		lineageTag: d568f585-9a99-4345-a1b4-d563314e8848
		summarizeBy: sum
		sourceColumn: 公司内部借款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预算内借款
		dataType: double
		displayFolder: 源列
		lineageTag: a8df734d-4156-490d-af1c-62f39dde36cd
		summarizeBy: sum
		sourceColumn: 预算内借款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预算外借款
		dataType: double
		displayFolder: 源列
		lineageTag: 11d03646-88d2-4468-9073-29f66a1fdc67
		summarizeBy: sum
		sourceColumn: 预算外借款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 到期归还预算内借款
		dataType: double
		displayFolder: 源列
		lineageTag: bdaa1d3a-fdb1-4f74-aeed-b6df475e5f48
		summarizeBy: sum
		sourceColumn: 到期归还预算内借款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 借款余额
		dataType: double
		displayFolder: 源列
		lineageTag: e16a2d80-e1a6-4fea-aa3d-a976f5eb56eb
		summarizeBy: sum
		sourceColumn: 借款余额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 项目累计现金净流量（还款后）
		dataType: double
		displayFolder: 源列
		lineageTag: 8fe35587-6a12-43cb-b9dc-e0ff7193f51b
		summarizeBy: sum
		sourceColumn: 项目累计现金净流量（还款后）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 到期归还预算外借款
		dataType: double
		displayFolder: 源列
		lineageTag: c173b2f9-8273-418e-a8e5-1cf8d7d2da27
		summarizeBy: sum
		sourceColumn: 到期归还预算外借款

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 预算内借款余额
		dataType: double
		displayFolder: 源列
		lineageTag: a2e2cac0-fd04-45fd-8bfa-75cc9eccd99a
		summarizeBy: sum
		sourceColumn: 预算内借款余额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column FDATATYPE
		dataType: string
		displayFolder: 源列
		lineageTag: 5228ad4c-b326-4339-bdd1-72e8c6c5843e
		summarizeBy: none
		sourceColumn: FDATATYPE

		annotation SummarizationSetBy = Automatic

	column FXXJD
		dataType: string
		displayFolder: 源列
		lineageTag: 0cc6c217-68f9-40f9-a82f-2e138f209cbd
		summarizeBy: none
		sourceColumn: FXXJD

		annotation SummarizationSetBy = Automatic

	column FSFSKJD
		dataType: string
		displayFolder: 源列
		lineageTag: 065dd7a3-e402-495d-b959-e39ec02ff04c
		summarizeBy: none
		sourceColumn: FSFSKJD

		annotation SummarizationSetBy = Automatic

	column 施工产值
		dataType: double
		displayFolder: 源列
		lineageTag: 432126ca-ba73-43f7-8dc8-b7442ed60b3d
		summarizeBy: sum
		sourceColumn: 施工产值

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 产值税额
		dataType: double
		displayFolder: 源列
		lineageTag: 008404c6-17ed-4ca3-8079-232019dfe26e
		summarizeBy: sum
		sourceColumn: 产值税额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 商务产值（不含税）
		dataType: double
		displayFolder: 源列
		lineageTag: 50e9313f-5f6c-4afe-b38c-79f7693378c7
		summarizeBy: sum
		sourceColumn: 商务产值（不含税）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工程款流入（现金口径）
		dataType: double
		displayFolder: 源列
		lineageTag: 99573516-f9e2-4d26-b42c-220d5e68daa7
		summarizeBy: sum
		sourceColumn: 工程款流入（现金口径）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工程款流入（全口径）
		dataType: double
		displayFolder: 源列
		lineageTag: 69fbc2db-8e16-4025-9b83-edf6ec76f403
		summarizeBy: sum
		sourceColumn: 工程款流入（全口径）

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 拟持有至到期票据收取
		dataType: double
		displayFolder: 源列
		lineageTag: 92484449-8f21-42e7-92c9-451730c43c32
		summarizeBy: sum
		sourceColumn: 拟持有至到期票据收取

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 票据到期现金流入
		dataType: double
		displayFolder: 源列
		lineageTag: f90f4058-73c6-429b-9cee-47b7e6d32a65
		summarizeBy: sum
		sourceColumn: 票据到期现金流入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 工程款非现金流入
		dataType: double
		displayFolder: 源列
		lineageTag: 1e5e0d1a-4824-478a-984f-aec5ba4e28a8
		summarizeBy: sum
		sourceColumn: 工程款非现金流入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 拟转帖票据收取
		dataType: double
		displayFolder: 源列
		lineageTag: f076b374-f288-4842-881a-7cdcd8478b33
		summarizeBy: sum
		sourceColumn: 拟转帖票据收取

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其他非现金工程款流入
		dataType: double
		displayFolder: 源列
		lineageTag: e94f9240-a3cf-4f67-b002-7b66974bf262
		summarizeBy: sum
		sourceColumn: 其他非现金工程款流入

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 非现金流支出
		dataType: double
		displayFolder: 源列
		lineageTag: f2aa9ace-4623-4feb-9084-b04dfa74c52e
		summarizeBy: sum
		sourceColumn: 非现金流支出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 分包支出:转贴票据支付
		dataType: double
		displayFolder: 源列
		lineageTag: a6ff894f-6e9f-44e4-83a3-dae43d2f0c10
		summarizeBy: sum
		sourceColumn: 分包支出:转贴票据支付

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 材料款:转贴票据支付
		dataType: double
		displayFolder: 源列
		lineageTag: 0900eb15-1791-45e3-888d-bf1612e076e8
		summarizeBy: sum
		sourceColumn: 材料款:转贴票据支付

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 机械使用费:转贴票据支付
		dataType: double
		displayFolder: 源列
		lineageTag: 317f84af-5115-4f2a-9144-8413a21c5aee
		summarizeBy: sum
		sourceColumn: 机械使用费:转贴票据支付

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 其他非现金流出
		dataType: double
		displayFolder: 源列
		lineageTag: afcf3a3a-2a7b-44b2-ba10-fa3564f3ddcc
		summarizeBy: sum
		sourceColumn: 其他非现金流出

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: Long Date
		displayFolder: 源列
		lineageTag: aac8af5b-6894-4436-8195-c80bdacf2a85
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition F_全期现金流 = m
		mode: import
		queryGroup: 全期现金流
		source =
				let
				    源 = Table.NestedJoin(全期现金流主表, {"FID"}, 全期现金流明细, {"FZBID"}, "明细", JoinKind.Inner),
				    删除的列 = Table.RemoveColumns(源,{"FID", "SCREATETIME"}),
				    #"展开的“明细”" = Table.ExpandTableColumn(删除的列, "明细", {"年度", "月份", "商务产值（含税）", "业主确认量", "现金流入", "工程款现金流入", "保证金退还", "其他现金流入", "工程款回收率", "现金流出", "直接费支出", "分包支出", "材料款", "机械使用费", "其他直接费", "间接费指出", "上交公司预收益", "税金", "融资业务到期兑付支出", "各类保证金支出", "支付率", "项目月度现金净流量", "项目累计现金净流量", "公司内部借款", "预算内借款", "预算外借款", "到期归还预算内借款", "借款余额", "项目累计现金净流量（还款后）", "到期归还预算外借款", "预算内借款余额", "FDATATYPE", "FXXJD", "FSFSKJD", "施工产值", "产值税额", "商务产值（不含税）", "工程款流入（现金口径）", "工程款流入（全口径）", "拟持有至到期票据收取", "票据到期现金流入", "工程款非现金流入", "拟转帖票据收取", "其他非现金工程款流入", "非现金流支出", "分包支出:转贴票据支付", "材料款:转贴票据支付", "机械使用费:转贴票据支付", "其他非现金流出"}, {"年度", "月份", "商务产值（含税）", "业主确认量", "现金流入", "工程款现金流入", "保证金退还", "其他现金流入", "工程款回收率", "现金流出", "直接费支出", "分包支出", "材料款", "机械使用费", "其他直接费", "间接费指出", "上交公司预收益", "税金", "融资业务到期兑付支出", "各类保证金支出", "支付率", "项目月度现金净流量", "项目累计现金净流量", "公司内部借款", "预算内借款", "预算外借款", "到期归还预算内借款", "借款余额", "项目累计现金净流量（还款后）", "到期归还预算外借款", "预算内借款余额", "FDATATYPE", "FXXJD", "FSFSKJD", "施工产值", "产值税额", "商务产值（不含税）", "工程款流入（现金口径）", "工程款流入（全口径）", "拟持有至到期票据收取", "票据到期现金流入", "工程款非现金流入", "拟转帖票据收取", "其他非现金工程款流入", "非现金流支出", "分包支出:转贴票据支付", "材料款:转贴票据支付", "机械使用费:转贴票据支付", "其他非现金流出"}),
				    更改的类型 = Table.TransformColumnTypes(#"展开的“明细”",{{"年度", Int64.Type}, {"月份", Int64.Type}}),
				    已添加自定义 = Table.AddColumn(更改的类型, "日期", each #date([年度],[月份],1),type date),
				    替换的值 = Table.ReplaceValue(已添加自定义,0,null,Replacer.ReplaceValue,{"商务产值（含税）", "业主确认量", "现金流入", "工程款现金流入", "保证金退还", "其他现金流入", "工程款回收率", "现金流出", "直接费支出", "分包支出", "材料款", "机械使用费", "其他直接费", "间接费指出", "上交公司预收益", "税金", "融资业务到期兑付支出", "各类保证金支出", "支付率", "项目月度现金净流量", "项目累计现金净流量", "公司内部借款", "预算内借款", "预算外借款", "到期归还预算内借款", "借款余额", "项目累计现金净流量（还款后）", "到期归还预算外借款", "预算内借款余额", "FDATATYPE", "FXXJD", "FSFSKJD", "施工产值", "产值税额", "商务产值（不含税）", "工程款流入（现金口径）", "工程款流入（全口径）", "拟持有至到期票据收取", "票据到期现金流入", "工程款非现金流入", "拟转帖票据收取", "其他非现金工程款流入", "非现金流支出", "分包支出:转贴票据支付", "材料款:转贴票据支付", "机械使用费:转贴票据支付", "其他非现金流出"})
				in
				    替换的值

	annotation PBI_ResultType = Table

