table F_应上交收益履约
	lineageTag: 3b8840ad-c539-47b0-99e1-2cdf1fc86ff8

	column 日期
		dataType: dateTime
		formatString: Long Date
		lineageTag: d39558d5-a364-4079-9065-2cc1705645ca
		summarizeBy: none
		sourceColumn: 日期

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 项目编码
		dataType: string
		lineageTag: 65ceead7-82e6-4819-a798-b45e1fbfc474
		summarizeBy: none
		sourceColumn: 项目编码

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 44e5ba20-8206-491f-a342-447ae1cb75b5
		summarizeBy: none
		sourceColumn: 项目名称

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 开工累计应上缴收益
		dataType: double
		lineageTag: 5fab339d-0ee5-4d06-b269-999d97f416fd
		summarizeBy: sum
		sourceColumn: 开工累计应上缴收益

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 开工累计应上缴履约
		dataType: double
		lineageTag: 932f2560-6d6c-4aca-b6a1-07b020a98bde
		summarizeBy: sum
		sourceColumn: 开工累计应上缴履约

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_应上交收益履约-dbbf3a35-892b-46ab-82a8-38705d05bb4b = m
		mode: import
		queryGroup: 应上缴收益履约
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="GSPM"]}[Data],
				    GSPM_PROJECTPROFIT = GSPM{[Name="GSPM_PROJECTPROFIT"]}[Data],
				    删除的其他列 = Table.SelectColumns(GSPM_PROJECTPROFIT,{"IYEAR", "IMONTH", "FXIANGMUBIANMA", "PROJNAME", "HEJI5", "HEJI8"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FXIANGMUBIANMA", "项目编码"}, {"PROJNAME", "项目名称"}, {"HEJI5", "开工累计应上缴收益"}, {"HEJI8", "开工累计应上缴履约"}}),
				    合并的列 = Table.CombineColumns(Table.TransformColumnTypes(重命名的列, {{"IYEAR", type text}, {"IMONTH", type text}}, "zh-CN"),{"IYEAR", "IMONTH"},Combiner.CombineTextByDelimiter("-", QuoteStyle.None),"日期"),
				    已分析的日期 = Table.TransformColumns(合并的列,{{"日期", each Date.From(DateTimeZone.From(_)), type date}})
				in
				    已分析的日期

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

