table F_物资进场
	lineageTag: 05eede1f-80cb-4983-9fbc-e603f582de3d

	column KEYID
		dataType: string
		lineageTag: c7ab90ff-13d0-4767-8252-084866b39a9f
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 税金
		dataType: double
		lineageTag: 944e51b3-1fab-475a-ba30-497867b4f762
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 分包类型
		dataType: string
		lineageTag: 281361f5-e00e-413b-ac96-74f76c491da1
		summarizeBy: none
		sourceColumn: 分包类型

		annotation SummarizationSetBy = Automatic

	column 专业
		dataType: string
		lineageTag: 5c06c53b-a279-4b1a-9824-cf6f05674e62
		summarizeBy: none
		sourceColumn: 专业

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 30f82273-c4b7-44fd-a433-376cd585ab10
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: 8e9e059a-18f9-422a-bcf0-42729e9582dd
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 金额
		dataType: double
		lineageTag: f36f2ef0-5e57-4a20-badd-1a1493985f1b
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_物资进场 = m
		mode: import
		queryGroup: 成本\物资\采购
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="DATA_DW"]}[Data],
				    DW_WZJCCBMX = GSPM{[Name="DW_WZJCCBMX"]}[Data],
				    删除的其他列 = Table.SelectColumns(DW_WZJCCBMX,{"KEYID", "FJIASHUIHEJI", "FJINE", "FSHUIJIN", "FHETONGLEIXING", "FSHIGONGZHUANYE", "FRQ"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FJIASHUIHEJI", "价税合计"}, {"FJINE", "金额"}, {"FSHUIJIN", "税金"}, {"FHETONGLEIXING", "分包类型"}, {"FSHIGONGZHUANYE", "专业"}, {"FRQ", "日期"}}),
				    #"筛选的行(删除垃圾数据)" = Table.SelectRows(重命名的列, each not (([价税合计] = 0 or [价税合计]=null ) and ([金额] = 0 or [金额]=null)))
				in
				    #"筛选的行(删除垃圾数据)"

	annotation PBI_ResultType = Table

