table F_物资调拨
	lineageTag: a5dc34df-48f4-40ca-ae78-cf8c9f0c23b9

	column KEYID
		dataType: string
		lineageTag: 538297cd-88e7-41ec-8d58-5e4706776a55
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 专业
		dataType: string
		lineageTag: bdd1ad2a-ea5a-4335-9b57-160f812947d5
		summarizeBy: none
		sourceColumn: 专业

		annotation SummarizationSetBy = Automatic

	column 分包类型
		dataType: string
		lineageTag: 46944aba-be24-4fed-b1ce-25459be5e535
		summarizeBy: none
		sourceColumn: 分包类型

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 071a5e63-3dc6-4c2c-a054-10ab46498489
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		lineageTag: 7d952986-75e7-4fcb-9a51-12f453ee7212
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 价税合计
		dataType: double
		lineageTag: 51c87f3a-cfe4-4263-9e56-a50ebef76953
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: 555f5607-0fb7-4c6e-ae93-2c75dc077c51
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_物资调拨 = m
		mode: import
		queryGroup: 成本\物资\采购
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="DATA_DW"]}[Data],
				    DW_WZDBMX = GSPM{[Name="DW_WZDBMX"]}[Data],
				    删除的其他列 = Table.SelectColumns(DW_WZDBMX,{"KEYID", "FSHIGONGZHUANYE", "FHETONGLEIXING", "FRQ", "FJINE", "FJIASHUIHEJI", "FSHUIJIN"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FHETONGLEIXING", "分包类型"}, {"FSHIGONGZHUANYE", "专业"}, {"FRQ", "日期"}, {"FJIASHUIHEJI", "价税合计"}, {"FSHUIJIN", "税金"}, {"FJINE", "金额"}}),
				    #"筛选的行（排除垃圾数据）" = Table.SelectRows(重命名的列, each not (([价税合计] = 0 or [价税合计]=null ) and ([金额] = 0 or [金额]=null)))
				in
				    #"筛选的行（排除垃圾数据）"

	annotation PBI_ResultType = Table

