table F_物资租赁对账
	lineageTag: 69b10294-c9a7-4199-ab53-153b496ef068

	column KEYID
		dataType: string
		lineageTag: c32ff3ec-36ca-45e7-8e87-8f91d78a3585
		summarizeBy: none
		sourceColumn: KEYID

		annotation SummarizationSetBy = Automatic

	column 专业
		dataType: string
		lineageTag: 3478785f-f548-45a7-ab86-02cd67a7df8b
		summarizeBy: none
		sourceColumn: 专业

		annotation SummarizationSetBy = Automatic

	column 分包类型
		dataType: string
		lineageTag: 011524ff-9b67-4db1-9ce3-7d973dd38cb7
		summarizeBy: none
		sourceColumn: 分包类型

		annotation SummarizationSetBy = Automatic

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 0422d888-9696-4761-b713-747d91ff2a6b
		summarizeBy: none
		sourceColumn: 日期

		annotation SummarizationSetBy = Automatic

	column 价税合计
		dataType: double
		lineageTag: 98eb2207-e5d5-400b-8ad1-d41c5291eee3
		summarizeBy: sum
		sourceColumn: 价税合计

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 金额
		dataType: double
		lineageTag: ce394a60-2e52-47ec-9a04-ea8553c3cc73
		summarizeBy: sum
		sourceColumn: 金额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: 6af36a9d-59b9-4755-8cd3-3b245f46e561
		summarizeBy: sum
		sourceColumn: 税金

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition F_物资租赁对账 = m
		mode: import
		queryGroup: 成本\物资\租赁
		source =
				let
				    源 = X5,
				    GSPM = 源{[Schema="DATA_DW"]}[Data],
				    DW_WZDZMX = GSPM{[Name="DW_WZDZMX"]}[Data],
				    删除的其他列 = Table.SelectColumns(DW_WZDZMX,{"KEYID", "FSHIGONGZHUANYE", "FHETONGLEIXING", "FRQ", "FWZZLCBJIASHUIHEJI", "FWZZLCBJINE", "FWZZLCBSHUIJIN"}),
				    重命名的列 = Table.RenameColumns(删除的其他列,{{"FSHIGONGZHUANYE", "专业"}, {"FHETONGLEIXING", "分包类型"}, {"FRQ", "日期"}, {"FWZZLCBJIASHUIHEJI", "价税合计"}, {"FWZZLCBJINE", "金额"}, {"FWZZLCBSHUIJIN", "税金"}}),
				    #"筛选的行（排除垃圾数据）" = Table.SelectRows(重命名的列, each not (([价税合计] = 0 or [价税合计]=null ) and ([金额] = 0 or [金额]=null)))
				in
				    #"筛选的行（排除垃圾数据）"

	annotation PBI_ResultType = Table

