table F_租赁物资合同额
	lineageTag: f36efc55-843d-4960-9541-79890a94f335

	column 价税合计
		dataType: double
		lineageTag: 50773ced-e99a-4860-9405-65c5498142ed
		summarizeBy: sum
		sourceColumn: 价税合计

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column KEYID
		dataType: string
		lineageTag: 4240db73-a24b-4812-9866-7dc9ba311660
		summarizeBy: none
		sourceColumn: KEYID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 金额
		dataType: double
		lineageTag: 949cf21c-4bbc-49f8-910b-2a80706e0206
		summarizeBy: sum
		sourceColumn: 金额

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 税金
		dataType: double
		lineageTag: 0c54b5d2-adf6-4915-b6b0-f2aea76e53d8
		summarizeBy: sum
		sourceColumn: 税金

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 日期
		dataType: dateTime
		formatString: General Date
		lineageTag: 4ec8d94e-b331-42ac-9ca4-620c4291bbb0
		summarizeBy: none
		sourceColumn: 日期

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		lineageTag: 3bd68a15-a0a1-4f1b-a8d8-1d98d8eac30a
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 合同协议号
		dataType: string
		lineageTag: 0461c6a2-af6b-4289-af93-1810a64b1336
		summarizeBy: none
		sourceColumn: 合同协议号

		annotation SummarizationSetBy = Automatic

	column 合同编号
		dataType: string
		lineageTag: 0b20940f-8d0c-4620-973f-b438a9a4fadb
		summarizeBy: none
		sourceColumn: 合同编号

		annotation SummarizationSetBy = Automatic

	column 供方编码
		dataType: string
		lineageTag: 4749395c-3cc2-484e-bdac-12f153426503
		summarizeBy: none
		sourceColumn: 供方编码

		annotation SummarizationSetBy = Automatic

	partition F_租赁物资合同额-53cac70d-a880-4ce1-a9ff-f0b13aa72807 = m
		mode: import
		queryGroup: 成本\物资\租赁
		source =
				let
				    源 = #"DW_WZHTXXB（物资合同）",
				    筛选的行 = Table.SelectRows(源, each ([采购O租赁] = "租赁合同")),
				    删除的其他列 = Table.SelectColumns(筛选的行,{"KEYID", "项目编码", "合同协议号", "合同编号", "供方编码", "价税合计", "金额", "税金", "日期"})
				in
				    删除的其他列

	changedProperty = IsHidden

	annotation PBI_ResultType = Table

