/// 合并组织机构、员工账号，取得账号对应项目编码
table 账户
	lineageTag: 7b0b6740-0b9a-4d71-9b76-84d70e7600ec

	column 身份证
		dataType: string
		lineageTag: 173188d6-549b-4bac-bd44-a429313f7881
		summarizeBy: none
		sourceColumn: 身份证

		annotation SummarizationSetBy = Automatic

	column 账号
		dataType: string
		lineageTag: b79ea9d7-b959-4c9c-9176-4a6b8cf8fecd
		summarizeBy: none
		sourceColumn: 账号

		annotation SummarizationSetBy = Automatic

	column 姓名
		dataType: string
		lineageTag: ac142c95-9e16-495d-9168-8aaeb4ef885c
		summarizeBy: none
		sourceColumn: 姓名

		annotation SummarizationSetBy = Automatic

	column 项目编码
		dataType: string
		lineageTag: 7063c6ed-843a-45a4-8e83-3aaaa8ed7881
		summarizeBy: none
		sourceColumn: 项目编码

		annotation SummarizationSetBy = Automatic

	column 项目名称
		dataType: string
		lineageTag: 38ff2a58-1377-4890-9bd6-d5f3ddfc58d7
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	partition 账户 = m
		mode: import
		queryGroup: 账户权限
		source =
				let
				    源 = Table.NestedJoin(门户账户, {"身份证"}, 员工项目, {"身份证"}, "SA_OPORG", JoinKind.Inner),
				    #"展开的“SA_OPORG”" = Table.ExpandTableColumn(源, "SA_OPORG", {"项目编码", "项目名称"}, {"项目编码", "项目名称"}),
				    删除的副本 = Table.Distinct(#"展开的“SA_OPORG”", {"账号", "项目编码"})
				in
				    删除的副本

	annotation PBI_ResultType = Table

