table F_年结算计划
	lineageTag: eb9a8479-0aca-46c0-b542-afa28de56e8f

	column 项目名称
		dataType: string
		lineageTag: 8b44b7d3-e1bc-4c5a-9288-9b2aa511fb41
		summarizeBy: none
		sourceColumn: 项目名称

		annotation SummarizationSetBy = Automatic

	column 含税预计结算额
		dataType: double
		lineageTag: 6eac150a-b81c-4b94-8829-0c8d8a5cf658
		summarizeBy: sum
		sourceColumn: 含税预计结算额

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 26年年度计划
		dataType: string
		lineageTag: e06015c3-71ee-477a-aed7-70e4556ec333
		summarizeBy: none
		sourceColumn: 26年年度计划

		annotation SummarizationSetBy = Automatic

	partition F_年结算计划 = m
		mode: import
		source =
				// F_25年结算计划
				let
				    源 = Excel.Workbook(File.Contents("\\172.16.8.66\经营分析\经营分析会\26年周报\结算进展26.1.16.xlsx"), null, true),
				    #"25年结算计划_Sheet" = 源{[Item="26年结算计划",Kind="Sheet"]}[Data],
				    提升的标题 = Table.PromoteHeaders(#"25年结算计划_Sheet", [PromoteAllScalars=true]),
				    删除的其他列 = Table.SelectColumns(提升的标题,{"项目名称", "合计预计结算总额#(lf)合理值", "26年年度计划"}),
				    筛选的行 = Table.SelectRows(删除的其他列, each ([26年年度计划] = "是")),
				    重命名的列 = Table.RenameColumns(筛选的行,{{"合计预计结算总额#(lf)合理值", "含税预计结算额"}}),
				    更改的类型 = Table.TransformColumnTypes(重命名的列,{{"项目名称", type text}, {"含税预计结算额", type number}, {"26年年度计划", type text}})
				in
				    更改的类型

	annotation PBI_NavigationStepName = 导航

	annotation PBI_ResultType = Table

